### ISSUE TITLE
[9/4 Wednesday] self-taught class

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#1]
I'll be absent on 9/4, so there will be no class in the classroom.  ~~Instead, I will upload a video explaining the course material.~~ Instead, I will upload the slides so that you can study them on your own.  **You are required to study the slides before 9/9.**

**Comment by jeehoonkang** [comment]
- On 9/4, there'll be no class in the classroom.
- By 9/9, please read the [Slide](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit?usp=sharing), page 11-23: "Taming shared mutable states with Rust".

**Comment by Pusnow** [comment]
Would you please add page numbers at the bottom?

**Comment by jeehoonkang** [comment]
@Pusnow Hi Wonsup, I just added slide numbers.  Thanks.

**Comment by zoonoo** [comment]
@jeehoonkang 
On page 23 you have specified a programming HW. 
Is this to be submitted at some point?

**Comment by jeehoonkang** [comment]
@zoonoo No, you're not required to submit anything.  But it's still homework, meaning you're required to do it.. :)

**Comment by RosieBahrani** [comment]
Are we supposed to study the shared memory and relaxed behavior as well?

**Comment by jeehoonkang** [comment]
No, but we'll study those topics in the classroom.
