### ISSUE TITLE
[Question] Can changing the hashmap be completely concurrent?

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#100]
The Cache.rs requires that the invocations of `get_or_insert_with(k, f)` should be concurrent with two different keys.
However, if both `key1` and `key2` do not exist in the in the hashmap, then inserting the keys is changing the hashmap.
Doesn't it require exclusive access for the thread to insert a new entry? I guess it may be possible if it has some peculiar structure, but it's hard to find related document.

**Comment by tomtomjhj** [comment]
Although there does exists a short period of time in which the thread waits for **a** lock to be available, the computation `f` doesn't necessarily need to be run while holding **that** lock.
