### ISSUE TITLE
[Question] join() on drop() for worker always has infinite loop. 

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#102]
I am trying to get `Threadpool::drop` for the last few hours, but it always seems to fail on the same spot. When `Threadpull::drop()` calls `drop(worker)`, my `drop` function for the worker calls `join()` on the worker's thread, similar to the book. However for some reason my code always goes into an infinite loop at this step. I thought that my implementation of the initialization of workers in `Threadpool::new` was incorrect, so I changed it so that the worker will always `break`. However the problem persisted, and I am out of ideas. Did anyone else have a similar problem?

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-690955970 Take a look at the paragraph starting with "We join() each thread in the destructor of Worker..."

**Comment by zhanto97** [comment]
Did you check whether in `ThreadPool::drop` your code reaches `drop(worker)`? My guess would be it doesn't. Maybe your code gets stuck before it even reaches `drop(worker)`. That problem was discussed a few times. Check [here](https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-696038652)

**Comment by Lee-Janggun** [comment]
I think I'm not understanding what it means to drop `Threadpool`. From the book I understood it as joining all of the `Worker` threads, and returning to the main thread. After I read  [#49 (comment)](https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-690955970) I thought what we had to change was so that the `Sender` is properly dropped as well, and being careful of `drop` and message sending order. It seems I am missing something. Any hints? Or should I just read the given hints more carefully?

**Comment by tomtomjhj** [comment]
> message sending order.

We do not use explicit exit message for thread pool.

**Comment by Lee-Janggun** [comment]
> > message sending order.
> 
> We do not use explicit exit message for thread pool.

I read that. So I thought it meant just to `send()` a direct instance of some `FnOnce` to the workers, as I thought that we still needed to send _something_ for it to break out of the loop. Was this an incorrect thought?

**Comment by tomtomjhj** [comment]
> * Each worker thread automatically breaks out of the loop if the channel is disconnected.

**Comment by Lee-Janggun** [comment]
Thank you... will try again. I will come back if I have a better question :)

**Comment by tomtomjhj** [comment]
A very important hint: the solution is **very** simple.

**Comment by Lee-Janggun** [comment]
It's not like I don't see that :(. Still thanks for the hint.

**Comment by Lee-Janggun** [comment]
Now that the due date is over, @tomtomjhj if the solution _is_ really that simple, can you give me an more specific hint? Unfortunately I was not able to improve since my last comment.
