### ISSUE TITLE
[Question] What is the late submission policy for homeworks?

### ISSUE THREAD

**Issue by Electr0phile** [kaist-cp/cs492-concur#103]
What are the late submission scoring rules for homework? Sorry if it was specified elsewhere, I just can't find it in this repository.

**Comment by 16ypark** [comment]
As a related question, how many programming assignments will we have in this course?

**Comment by jeehoonkang** [comment]
- No late submissions.
- There will be 5 or 6 assignments.

**Comment by Electr0phile** [comment]
Isn't it too harsh for a project that requires studying a whole textbook and learning a new language?

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-699729497
