### ISSUE TITLE
[Homework 2] Linked List (due: 2020-10-16 23:59:59+0900)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs492-concur#105]
# HW2: Unsafe Rust Primer
**Implement a doubly linked list in unsafe Rust.**

This homework serves as a brief tutorial for unsafe Rust with focus on the basic raw pointer operations.

The [skeleton code](https://github.com/kaist-cp/cs492-concur/blob/master/homework/src/linked_list.rs) is slightly modified version of [the linked list from Rust standard library](https://doc.rust-lang.org/std/collections/struct.LinkedList.html).  We already provided implementation for several methods e.g. `push_front`.  Your job is to implement their symmetric counterparts e.g. `push_back` and some methods of `IterMut` struct (see `todo!()`s).

 You can look up its implementation from the standard library but we encourage you do it yourself so that you can build enough skill set for upcoming homeworks.  We also recommend you to play with AddressSanitizer and debugger.

* The full score for this homework is 40 points (HW1 was 100) and total lines of code to be written is about 80.

* You can evaluate your solution by running `./scripts/grade-2.sh` in the `homework` directory. 

* submission method: TBA

## Guide
1. Read [Rust Book §19.1](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html)
1. Skim through [Nomicon §1](https://doc.rust-lang.org/nomicon/meet-safe-and-unsafe.html)
1. Read [raw pointer type documentation](https://doc.rust-lang.org/std/primitive.pointer.html) and some of its methods (`is_null`, `as_ref`, `read`, `write`, `replace`, `swap`)
1. Read [`std::mem`](https://doc.rust-lang.org/std/mem/index.html) and [`std::ptr`](https://doc.rust-lang.org/std/ptr/index.html) documentations.
1. Read [`std::iter`](https://doc.rust-lang.org/std/iter/index.html) documentation.

## Other useful resources
* [`*` operator](https://doc.rust-lang.org/stable/reference/expressions/operator-expr.html#the-dereference-operator)
* [`.` operator](https://doc.rust-lang.org/stable/reference/expressions/call-expr.html)
* [type coercion (weakening)](https://doc.rust-lang.org/nomicon/coercions.html)
* [type casting](https://doc.rust-lang.org/nomicon/casts.html)
* [`Box<T>` is special](https://doc.rust-lang.org/stable/reference/special-types-and-traits.html#boxt)
* [`*const T` vs. `*mut T`](https://internals.rust-lang.org/t/what-is-the-real-difference-between-const-t-and-mut-t-raw-pointers/6127)

**Comment by YujinGaya** [comment]
It seems like the current test suite is not testing the `prepend` method. I got full score with `todo!()` in the definition of the method. It'd be better if we have extra test cases for that so that we can check whether we did it right.

**Comment by tomtomjhj** [comment]
Thanks for letting me know that. https://github.com/kaist-cp/cs492-concur/commit/8685265278afa398be5f961d388226b0f46a6f8d

**Comment by YujinGaya** [comment]
We have only one doc test for the `insert_next` method and it doesn't check edge cases like inserting it at the very front and very back of the list.

```rust
use cs492_concur_homework::LinkedList;

let mut list: LinkedList<_> = vec![1, 4].into_iter().collect();

{
    let mut it = list.iter_mut();
    assert_eq!(it.next().unwrap(), &1);
    // insert `2` and `3` after `1`
    it.insert_next(2);
    it.insert_next(3);
}
{
    let vec: Vec<_> = list.into_iter().collect();
    assert_eq!(vec, [1, 2, 3, 4]);
}
```

Maybe we can change the test case a little bit like this?

```rust
use cs492_concur_homework::LinkedList;

let mut list: LinkedList<_> = vec![1, 4].into_iter().collect();

{
    let mut it = list.iter_mut();
    it.insert_next(0);
    assert_eq!(it.next().unwrap(), &1);
    // insert `2` and `3` after `1`
    it.insert_next(2);
    it.insert_next(3);
    assert_eq!(it.next().unwrap(), &4);
    it.insert_next(5);
}
{
    let vec: Vec<_> = list.into_iter().collect();
    assert_eq!(vec, [0, 1, 2, 3, 4, 5]);
}
```

**Comment by tomtomjhj** [comment]
Thanks for the suggestion. Added that and another test for prepend to check the edge cases. https://github.com/kaist-cp/cs492-concur/commit/76f771af6655cc9e8c52549134be92a6bad66a01

**Comment by jeehoonkang** [comment]
Submit your `linked_list.rs` here: https://gg.kaist.ac.kr/course/6/

**Comment by f52985** [comment]
When running <code>./script/grade-2.sh</code> with my source code at the server, the result was 40/40.
However, when I submitted my code to submission site, the test failed and result was 0/40.

Are there additional test cases for submission?
If not, could you check if there is any issue?

**Comment by jeehoonkang** [comment]
@f52985 We figured out the reason.  We'll fix it by tomorrow.  There're no additional test cases.

**Comment by jeehoonkang** [comment]
@f52985 the problem is fixed.

**Comment by qawbecrdtey** [comment]
Just a small typo, but the grading file is in `./scripts/grade-2.sh`, not `./script/grade-2.sh`.

**Comment by tomtomjhj** [comment]
### Tips for debugging
When cargo test fails with error messages like this,
```
thread panicked while panicking. aborting.
error: test failed, to rerun pass '--test linked_list'

Caused by:
  process didn't exit successfully: ... (signal: 4, SIGILL: illegal instruction)
```
try running the test like this 
```
cargo test --test linked_list -- --nocapture --test-threads 1
```
This will give you more informative error messages.
