### ISSUE TITLE
[Question] Suggestion regarding late-hw1 policy.

### ISSUE THREAD

**Issue by BanseokWoo** [kaist-cp/cs492-concur#106]
Hello! I'm writing this post because I've read [https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-699729497](https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-699729497) this announcement regarding the late policy, and I have some thoughts on this matter.

First of all, I agree that the more generous policy becomes, the more it will seem unfair for the students who managed to do perfect work on time. But still I think the homework was really tough since it was a whole new language and it covered whole textbook. So, I appreciate that professor is accepting late submissions, yet the policy seems too harsh.

It says that the maximum score for each module is of form max(30, 40*R) but R is unknown yet. It means that I, as a student, can't know whether I can get higher score than the previous one so it's hard to decide whether to put those effort since it can be worth no points regardless of many hours of effort put in. So I think if this policy is to be adopted, the 'R' value should be known as soon as possible(at least before a week or so before due.) And actually, as a personal opinion, I think it would be much more motivating if the score policy would've been more generous. For example, 30pt for first submission and (30 + a) pt for second, then (30 + S * a) overall for some ratio S.(In this case regardless of the value S, it is still ensured that working on it at least pays for it. Yet still would be better to be known beforehand)

These are my suggestions regarding the policy, and thank you for paying attention. I know that it is likely to be ignored since it is just a request, but I think it is a fair one and I would really appreciate it if you consider the things I've written.

Thank you.

**Comment by jeehoonkang** [comment]
- Actually, for each module, the grading scheme is all-or-nothing: you'll get 40pts or 0pts.  So if you didn't get 40pts for thread pool, it's beneficial for you to work on it for the late submission.
- I promise R >= 0.5.
