### ISSUE TITLE
[Question] (question about raw pointer's characteristicc

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#109]
In rust the book 19.1 said that
raw pointers Aren’t guaranteed to point to valid memory. 
Can I know some concrete situation that such characteristic is useful?
Is there any situation user have to assign variable a invalid memory not by fault?

**Comment by jeehoonkang** [comment]
```rust
let x = ptr::null();
```

Here, `x`'s initial value is the null pointer, which doesn't point to a valid memory location.  It's meant to be reassigned sometime in the future.  Also, it can be checked whether it's reassigned or not (by checking `x.is_null()`).
