### ISSUE TITLE
Inconsistent behavior of the method extract_children in node.rs (ART)

### ISSUE THREAD

**Issue by lumiknit** [kaist-cp/cs492-concur#11]
During testing my ART (based on the commit @20b07e2) with stress test with >30000 ops, I found that the behavior of the method `extract_children` of `NodeBody48<V>` is slightly different from the methods of other ones.

For example, suppose that NodeBody contains 4 key-value pairs, `(7, a), (9, b), (8, c), (6, d)`.

Then, `NodeBody4` and `NodeBody16` can contain them such as `key = [7, 9, 8, 6, ...]`, and `children=[a, b, c, d, ...]`. When we call `extract_children` with this node, the method will zip them using `izip!` and make a vector by pushing zipped one. Therefore, we obtain a vector `[(7, a), (9, b), (8, c), (6, d)]`.

If `NodeBody256` contains above 4 pairs, then `children` is an array such that `children[7] = a`, `children[9] = b`, `children[8] = c` and `children[6] = d`. When we call `extract_children` with this node, the method enumerates `children` by index and make a vector of index-value pairs. Therefore, we obtain a vector `[(6, d), (7, a), (8, c), (9, d)]`.

If `NodeBody48` contains above 4 pairs, then `indexes` may be an array such as `children[7] = 0`, `children[9] = 1`, `children[8] = 2`, `children[6] = 3`, and `children` may be an array `[a, b, c, d, ...]`. When we call `extract_children` with this node, the method iterates the values of `indexes` and make a vector of index-value pairs. But the index part of the vector is not the index of `indexes` but one of `children`. Therefore, we obtain a vector `[(0, a), (1, b), (2, c), (3, d)]`.

I want to know whether I misunderstood the code (and this difference was intended).

**Comment by jeehoonkang** [comment]
Thank you for pointing out the bug.  The bug you reported is just fixed: 9d44178  Sorry for the inconvenience.
