### ISSUE TITLE
[Question]condition for reordering

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#110]
In a live session, professor explained how java causality test#13 is allowed using SC.
But I wonder if there is some condition for reordering. 

What I mean is that in which case we consider reordering to decide whether result is allowed or not.
Or SC is just default behavior of compiler?

**Comment by jeehoonkang** [comment]
- I explained #13 is **forbidden** in the promising semantics using SC.
- SC is not the default behavior.  The DRF theorem is a reasoning principle: if a program doesn't have races assuming the SC semantics, then its semantics in the promising semantics, coincides with that in the SC semantics.

**Comment by wltn0029** [comment]
Oh, I just miswrote **forbidden** to **allowed**! Sorry for confusing.
I understand why you explained using SC. Thank you!
