### ISSUE TITLE
[Question] Promising Semantics with compare and swap

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/cs492-concur#111]
In the slides, the professor showed an example of using promising semantics for fetch_add read-modify-write operations,
but how do we model usages of compare and swap? When using fetch_add, we can say that the result will be a monotonically increasing sequence in all cases, but when using CAS (that does not simply do +1 to the current value, but a more complicated one), it seems that we may have various possible orders. Would we need to consider all cases?

(This is just a question I asked during the live session)

**Comment by jeehoonkang** [comment]
Hmm, sorry, but I don't quite understand the question.  Would you please ask in Korean?

**Comment by travis1829** [comment]
설명을 이상하게 해서 죄송합니다.
47번 슬라이드(https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g62927da2e4_15_14)를 보면, read-modify-write는 항상 연속해서 메시지를 기록하는 식으로 표현하셨는데, fetch_add는 왼쪽 쓰레드가 먼저 실행되든 오른쪽 쓰레드가 먼저 실행되든 항상 X의 결과가 0, 1, 2 순서로 나타나지만, compare-and-swap을 사용하는 경우 프로그램의 실행에 따라 X의 결과가 여러 가지 순서가 가능할 수 있어서, 이 경우 혹시 모든 경우의 수를 다 해보는게 맞는 건지 궁금해서 문의드렸습니다.

**Comment by jeehoonkang** [comment]
@travis1829 Regardless of whether they are CASes or FAAs, RMW instructions' execution order is nondeterministic and you need to **consider all possible orders** among the multiple RMW instructions.

**Comment by travis1829** [comment]
알겠습니다. 어쩌면 당연한 건데 궁금해서 문의드렸습니다.
감사합니다!
