### ISSUE TITLE
[Question] homework1 test thread_pool_drop_propagate_panic()

### ISSUE THREAD

**Issue by us0310306** [kaist-cp/cs492-concur#114]
I passed other tests in thread_pool.rs, but I don't know how can I pass this test case.
In my code, thread receive the function and execute it so it panics, but how can I change the panic location to drop function?

**Comment by tomtomjhj** [comment]
Are you using `JoinHandle::join`? If so, are you `.unwrap()`ping the join result?

**Comment by us0310306** [comment]
I used JoinHandle::join in Worker drop function. 

thread '<unnamed>' panicked at 'explicit panic', src/hello_server/thread_pool.rs:280:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'hello_server::thread_pool::test::thread_pool_drop_propagate_panic' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/hello_server/thread_pool.rs:26:44

If I unwrap it in worker drop, output is like above

**Comment by tomtomjhj** [comment]
That doesnt pass the test??

**Comment by us0310306** [comment]
Yes...

**Comment by tomtomjhj** [comment]
please send me an email with your code

2020년 10월 7일 (수) 오후 9:03, us0310306 <notifications@github.com>님이 작성:

**Comment by us0310306** [comment]
use crossbeam_channel::{unbounded, Sender};
use std::sync::{Arc, Condvar, Mutex};
use std::thread;

In thread_pool.rs, these are imported.
Is it able to import other thing and use?

**Comment by Lee-Janggun** [comment]
I am having the same issue. I also used `JoinHandle::join` and `unwrap()` on join, but got the issue 
```
thread 'hello_server::thread_pool::test::thread_pool_drop_propagate_panic' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/hello_server/thread_pool.rs:25:22
```
If you got this fixed, can you provide a hint on how you managed to fix it?
