### ISSUE TITLE
Instructions for the midterm exam on the 22nd of October (Thu)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#116]
Hi all,

- We will remotely conduct the **midterm exam on the 22nd of October (Thu), 10:15-11:45**.  (**No extension** will be given.)

- For the midterm, students are required to participate in two Google Hangout Meet rooms.  The students should **join the rooms at least at 10:00**.  As soon as you join the rooms, please write down your name and student id in both rooms.

    + [Announcement room](https://meet.google.com/zqd-qmgd-sga):
      Join with your device in which you'll solve the midterm exam problems.
      I will announce important notes in this room.  You don't need to turn on camera or microphone.

    + ["CCTV" room](https://meet.google.com/ckf-upaj-ype):
      For the entirety of the meeting, you need to **turn on your camera** and **show your hand, paper, keyboard, and monitor**.
      I'm attaching the model scene from the experienced TA below.  If you cannot set up a camera like this, please let me know as soon as possible.

- On screen, you can only look at the followings:

    + https://github.com/kaist-cp/cs492-concur/issues/116
    + https://gg.kaist.ac.kr
    + the Google form for exam
    + A simple text editor of your choice (e.g., notepad or gedit, but not vscode)

- For the midterm exam, go to https://gg.kaist.ac.kr/course/6 and check your midterm exam event token.
  Then open the Google form that will be announced in gg and aswer the questions.
  You need to (1) log in with a Google account, and (2) fill out your email, name, student ID, and the event token.

- You can ask questions here: https://gg.kaist.ac.kr/event/2  If your question is not answered for 10 minutes, please let me know in the announcement room's chat.  Questions can be written either in Korean or English.

    + If you want to go to bathroom, please ask a question.  After getting a permission, you may go.  After turning back, please ask a question again that says you returned.

    + If you want to leave early, please ask a question.  After getting a permission, you may leave.

![IMG_5492](https://user-images.githubusercontent.com/1201316/95432855-28d33800-098a-11eb-9b18-b515c34bb2e9.jpg)

**Comment by AnHaechan** [comment]
Will the HW3 be covered in the midterm exam?

**Comment by zhanto97** [comment]
Is it OK if I just setup my phone as shown in the picture and use my laptop for the exam? I assume we will not need Google Meet on laptop

**Comment by jeehoonkang** [comment]
- @AnHaechan The midterm covers everything you learned before the midterm, and it will include the Arc.
- @zhanto97 Yes, you can join Google Meet with your phone and your laptop doesn't need to join Google Meet.  Does it work for you?

**Comment by zhanto97** [comment]
I think it works for me. Thank you!

**Comment by AnHaechan** [comment]
@jeehoonkang Sorry for inconvenience, but 'Arc' means the HW3, 
not just Rust standard library's Arc that we've used in the lecture and HW1, right?

**Comment by jeehoonkang** [comment]
@AnHaechan Yes, I meant the homework 3 Arc.

The correctness grader will soon be provided.  We're going to use [a model checker](https://github.com/tokio-rs/loom).

**Comment by c0m0r1** [comment]
Will the exam be an open-book or closed-book?

**Comment by jeehoonkang** [comment]
@c0m0r1 It'll be closed-book.

**Comment by jeehoonkang** [comment]
The instruction is updated.  Please read it carefully so that you can properly prepare for the tomorrow's practice session (mandatory).

**Comment by minseongg** [comment]
I think I heard it during the practice session, but I'm not sure, so I ask a question. Can we use VSCode during the midterm exam?

**Comment by minseongg** [comment]
I think I heard it during the practice session, but I'm not sure, so I ask a question. Can we use VSCode during the midterm exam?

**Comment by minseongg** [comment]
I think I heard it in the practice session, but I'm not sure, so I ask a question. Can we use VSCode during the midterm exam?

**Comment by jeehoonkang** [comment]
- Everyone, the instruction is updated.  See you tomorrow 10:00.
- @minseongg No, I'd like you to use simpler editors like notepad or gedit.

**Comment by Kalogon** [comment]
The above instruction says we can see "https://github.com/kaist-cp/cs492-concur" website. Is it mean we can see the code in the repository?

**Comment by jeehoonkang** [comment]
@Kalogon Thank you for asking the question.  I ask you to see only **this issue** (#116).  I updated the instruction.

**Comment by sklationd** [comment]
Can we leave early if we finish the exam(submit the google form)?

**Comment by jeehoonkang** [comment]
@sklationd Yes, you can leave early **after getting permission as a question.**  I'll update the instruction.

**Comment by Lee-Janggun** [comment]
Are the rooms not open yet?

**Comment by sonsh04** [comment]
It's 9:59 now, but it's still inaccessible.
