### ISSUE TITLE
[Question] Promising semantics for slides pp.58~60

### ISSUE THREAD

**Issue by j2k0618** [kaist-cp/cs492-concur#117]
In the slides pp.58~60, r1=r2=1 is possible because of certification. I think r1=r2=0 is also possible but X=1 certification in promising semantics makes me confused. Should first instruction of first thread (r1=X) read X=1 certification? Or Certification is just one of the possible choices so is thread can access X=0 too?

**Comment by jeehoonkang** [comment]
The first thread can always read X=0.  Promise enables the first thread to read X=1.

**Comment by j2k0618** [comment]
Then if first thread read X=0 instead of X=1, the view point of first thread for X does not change and located at X=0, right? Promise just enables multiple choices between the view point of thread and certified values because certification locates in readable/writable area which is after the current thread's view. Did I understand correctly?

**Comment by jeehoonkang** [comment]
@j2k0618 Yes right, if you read X=0, your view doesn't change.

Promise (of the other threads) is just inserting a message to the message.  As a reader, you don't chare the message is promised or not; if there's a message, you can read it as far as your view allows it.
