### ISSUE TITLE
[Homework 1] cargo build does not create ./target/debug

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#119]
When I used `cargo build` it should create `./target/debug/*`. However the corresponding files are not created. I checked the Rust book for clarity and it said that running 'cargo build' should create the files. I also remember I had the files the last time I used them, however they are now gone and I cannot debug. What is the problem?

**Comment by jeehoonkang** [comment]
Please paste your log so that we can figure out the reason.

**Comment by Lee-Janggun** [comment]
The log is as follows

""'
s@kaist-cp-cs492:~/cs492-concur/homework/src/hello_server$ cargo build
   Compiling cs492-concur-homework v0.1.0 (/home/s20170827/cs492-concur/homework)
Finished dev [unoptimized + debuginfo] target(s) in 0.15s
"""

After searching the directory from scratch I realized this did create a 'target/debug' directory, but under 'homework'. I feel like it should be under 'hello_server' where I ran 'cargo build', so I was lost.

**Comment by jeehoonkang** [comment]
Yes, the `target` is created at the crate root.  I'm closing this issue because it seems you found `target`.

**Comment by Lee-Janggun** [comment]
Seems like I remembered wrong last time about the position of `target`. Thanks for the help.
