### ISSUE TITLE
[Homework 3] Core Arc (due: 2020-10-30 23:59:59+0900)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs492-concur#120]
# HW3: Core Arc
**Implement a simplified version of `Arc` without the support for `Weak`.**  Submit your `arc.rs` to https://gg.kaist.ac.kr/assignment/22/ .

In this homework, you will practice basic synchronizations in the relaxed memory model by implementing a simplified `Arc`.  Specifically, you will use atomic operations of `AtomicUsize` to synchronize the accesses to the underlying data with its deallocation.  Read the documentation in `src/arc.rs` carefully and fill in the `todo!()`s.  The total lines of code to be written is about 25.

The skeleton code is heavily modified version of `Arc` from the standard library.  I don't recommend reading the original source code before finishing this homework because that version is much more complex and uses some concept that we didn't cover in the lecture yet.

## Grading (50 points)
Run `./scripts/grade-3.sh`.

1. Functionality (25): First, the grader will check if you implementation passes the doc tests and the tests in `tests/arc.rs`. You can manually re-run the test with following commands:
    ```
    cargo test --test arc
    cargo test --doc arc
    RUSTFLAGS="-Z sanitizer=address" RUSTDOCFLAGS="-Z sanitizer=address" cargo +nightly test --target x86_64-unknown-linux-gnu --test arc
    RUSTFLAGS="-Z sanitizer=address" RUSTDOCFLAGS="-Z sanitizer=address" cargo +nightly test --target x86_64-unknown-linux-gnu --doc arc
    ```
2. Correctness (25): Then the grader runs the tests with [loom model checker](https://github.com/tokio-rs/loom) to check all possible executions in the relaxed memory model. If your code doesn't pass these tests, then you need to fix the memory orderings. You can manually re-run the tests with this command.
    ```
    cargo test --features check-loom --test arc -- --nocapture --test-threads 1
    ```
3. Efficiency: Make sure that you don't use `SeqCst` ordering. We'll give 0 point if your solution contains `SeqCst`. However, we will not check if your implementation is optimal (optimal implementation uses some concept we didn't cover in the lecture yet).

## Tips
* Read [`std::sync::atomic::AtomicUsize`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html).
* You may need to use [`std::sync::Ordering::AcqRel`](https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html#variant.AcqRel).
* [`std::ptr::NonNull`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html) is basically a raw pointer that is always non-null (+ some properties that we won't care about in this course). The only method you need in this homework is [`as_ptr`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.as_ptr). But you may use the other methods.
* You may need to use [`std::mem::forget`](https://doc.rust-lang.org/std/mem/fn.forget.html) in `try_unwrap`.
* If the test failure message is not descriptive enough, try adding `-- --nocapture --test-threads 1`.

**Comment by tomtomjhj** [comment]
### Updates
* [Bump rust version to 1.47](https://github.com/kaist-cp/cs492-concur/commit/d472c24603199eed26eac5f7cbe9dccecb4dbf95). This will give you [simpler backtraces](https://blog.rust-lang.org/2020/10/08/Rust-1.47.html#shorter-backtraces).
* [Added correctness tests](https://github.com/kaist-cp/cs492-concur/commit/8a0934c34414ce1845b8a2f8bb3992823f63422c) and updated the instruction.

**Comment by tomtomjhj** [comment]
### FAQ: AddressSanitizer reports memory leak in my Arc implementation.
It might be the case that you're not actually deallocating the heap memory block in your `Drop` implementation. For example, if you call functions like `drop_in_place` on `*mut ArcInner<_>`, it only runs the destructor of `ArcInner` without freeing the memory where that `ArcInner` lived. 

The standard method to free the heap memory block is to convert the pointer `*mut T` to `Box<T>` whose destructor runs the destructor of `T` and frees the heap memory occupied by `T`. For example, `pop_front_node` from HW2 uses `Box::from_raw` to convert the head pointer into `Box<Node<_>>` and returns that box. When this box gets dropped, the destructor of box will free the memory block of the node.

For more information, see https://github.com/kaist-cp/cs492-concur/issues/125 , https://doc.rust-lang.org/reference/destructors.html, and https://doc.rust-lang.org/std/boxed/index.html

**Comment by jeehoonkang** [comment]
Now you can submit here: https://gg.kaist.ac.kr/assignment/22/

**Comment by YujinGaya** [comment]
Current test suite is not covering double drop of the `data: T` in `try_unwrap`. It would be great if we can check it with test case like below

```rust
// check whether canary dropped once
#[test]
fn test_try_unwrap_double_drop() {
    let mut canary = AtomicUsize::new(0);
    let x = Arc::new(Canary(&mut canary as *mut AtomicUsize));
    let _ = Arc::try_unwrap(x);
    assert!(canary.load(Relaxed) == 1);
}

// double drop induces double free hence panic
#[test]
fn test_try_unwrap_double_drop_box() {
    let x = Arc::new(Box::new(0));
    let _ = Arc::try_unwrap(x);
}

```

**Comment by tomtomjhj** [comment]
@YujinGaya Thanks for suggestion! https://github.com/kaist-cp/cs492-concur/commit/ba202629549ed31e06b5e67efbbe532fa2dc9ff3

**Comment by tomtomjhj** [comment]
**Update** `mem::forget` is not needed unless you blindly copied the code from `std::sync::Arc` implementation <sub><sub>like me</sub></sub>. I'm sorry if this confused you.

**Comment by saltylight** [comment]
@tomtomjhj I was about to ask what does it mean with `may need to use`. Thank you!

**Comment by tomtomjhj** [comment]
### Update!! https://github.com/kaist-cp/cs492-concur/commit/ee397d4c575b4d3bb276f38dc3fd619a2e8cb2ae
 I just found out that I forgot to add correctness checker stuff in the skeleton code. This means that the grader didn't actually check if the synchronization is done correctly. If you have already submitted your solution, please resubmit. I apologize for your inconvenience.

**Comment by saltylight** [comment]
@tomtomjhj Can we implement `try_unwrap` without `mem::forget`? Since `T` does not conform `Clone`, I think we must handle ownership(and **also not call destructor of data**) issue and return the value. If not, we will face compile error with ownership problem or destructor called issue in try_unwrap.

**Comment by tomtomjhj** [comment]
@saltylight uh.. sorry again. You actually need `forget`.. BTW `forget` is just a wrapper around `ManuallyDrop::new`

**Comment by tomtomjhj** [comment]
By the way please re-submit your solution when the test cases or the skeleton codes are updated. Currently gg doesn't have functionally to re-trigger the grader. Thanks!

**Comment by tomtomjhj** [comment]
All solutions submitted before 2020-10-16 17:30:00+0900 are nullified. Please re-submit.

**Comment by saltylight** [comment]
@tomtomjhj Should we drop `ArcInner` using Box in `try_unwrap`? 
When I didn't add dropping `ArcInner` in `try_unwrap`, I got following error.
```
test src/arc.rs - arc::Arc<T>::try_unwrap (line 209) ... FAILED

failures:

---- src/arc.rs - arc::Arc<T>::try_unwrap (line 209) stdout ----
Test executable failed (exit code 1).

stderr:

=================================================================
==154582==ERROR: LeakSanitizer: detected memory leaks
```

However, when I passed that test by dropping `ArcInner` using the `Box`, I got other error.
```
test basic::test_try_unwrap_drop_once ... FAILED
test correctness::get_mut_sync ... ok
test basic::test_stress ... ok

failures:

---- basic::test_try_unwrap_drop_once stdout ----
thread 'basic::test_try_unwrap_drop_once' panicked at 'assertion failed: canary.load(Relaxed) == 1', tests/arc.rs:119:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am a bit confused about this issue. Can you give me some advice?

**Comment by tomtomjhj** [comment]
@saltylight please file a new inssue

**Comment by tomtomjhj** [comment]
## Update https://github.com/kaist-cp/cs492-concur/commit/27856ae1411b79a4677e9a905583a3edbc3aa546
Added one more test case suggested by @integerblue. All submissions prior to 2020-10-16 20:41:00+0900 are nullified. Please submit again.

**Comment by workstudy-zero** [comment]
> ## Update [27856ae]

Could you confirm that this is the last nullifying( and modifying) submission? I think we spent too much time on this assignment...
