### ISSUE TITLE
[Question] Using cargo test about linked_list

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#122]
Hello, I'm trying to use AddressSanitizer with homework2 and ran into some problems.
I wanted to use `cargo test` with the linked_list, but the terminal shows it runs 0 test for every file in `homework/src` directory. I wrote the `launch.json` file, and used
`RUSTFLAGS="-Z sanitizer=address" cargo +nightly test linked_list --target x86_64-unknown-linux-gnu`.
Isn't specifying test name enough to run the specific test? I looked up several documents about this issue, but the examples were not enough for me to understand the situation. Sorry if it is a silly question.

**Comment by tomtomjhj** [comment]
`cargo test` command is actually quite confusing. Which test do you want to run?

**Comment by tomtomjhj** [comment]
Try 
* `RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --test linked_list --target x86_64-unknown-linux-gnu`
* `RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --doc linked_list --target x86_64-unknown-linux-gnu`

**Comment by haeeun-14** [comment]
> Try
> 
> * `RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --test linked_list --target x86_64-unknown-linux-gnu`
> * `RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --doc linked_list --target x86_64-unknown-linux-gnu`

Thank you! it worked well. Does `--test linked_list` point toward the test module out of the one I intend to test, or is it something else?

**Comment by tomtomjhj** [comment]
* --test linked_list runs the all test functions in tests/linked_list.rs
file.
* --doc linked_list runs the tests in documentation (the example code) for
the functions that contains substring "linked_list" in their fully
qualified name.

2020년 10월 9일 (금) 오후 12:26, haeeun-14 <notifications@github.com>님이 작성:
