### ISSUE TITLE
[Question] Infinite loop at cache test.

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#124]
When I am trying out `cargo test hello_server -- --skip thread_pool tcp`, the test goes into infinite loop for all cases. When I try to debug it, however, the debug session ends without a loop, but gives the following message.

```
code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" 
```

I thought that if there is a loop at `cargo test` then it should be replicable at a debug session, but apparently not. Did anyone else have similar issue?

**Comment by tomtomjhj** [comment]
Are you making tcp connection in the test?

**Comment by tomtomjhj** [comment]
Try
``` 
cargo test hello_server -- --skip thread_pool --skip tcp
```

**Comment by Lee-Janggun** [comment]
Same result. I forgot to mention above, but I do have a error message
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/hello_server/cache.rs:98:45
```
Come up during the execution of the test. Line 98 is the test `cache_no_block_disjoint`.

**Comment by tomtomjhj** [comment]
Let's discuss here https://meet.google.com/zqd-qmgd-sga

**Comment by Lee-Janggun** [comment]
I am waiting :)

**Comment by tomtomjhj** [comment]
??

**Comment by tomtomjhj** [comment]
oh I don't have the permission to accept someone to the meeting. please wait a sec

**Comment by Lee-Janggun** [comment]
Oh ok.

**Comment by tomtomjhj** [comment]
https://meet.google.com/buq-rxku-pue
