### ISSUE TITLE
[Question] Value inside Some(s) without consuming ownership.

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#126]
My cache type has form similar to `Mutex<HashMap<K, Option<V>>>`. I am not sure how to obtain the value inside Some(s) when obtaining an already existing value. When creating the new value, I could `clone()` the value of the function for later so there was no problem with ownership. But when obtaining the value with `s.unwrap()` where `s` is type `Option<V>`, there is an error as `unwrap()` consumes ownership. To get around this I tried a few things including cloning the `Option` value, wrapping and cloning in `Arc<Mutex<T>>`, etc. However at the end the same problem with `unwrap` seems unavoidable. What am I missing?

**Comment by AnHaechan** [comment]
How about
// v : T
match s {
  Some(ref v) => some_function(v),
  None => (),
}
//where : fn some_function(v : &T) -> ()

**Comment by Lee-Janggun** [comment]
I actually did
```
match s.clone() {
Some(s) => f(s),
None => ()
```
and it somehow worked. I think your option works as well.

**Comment by AnHaechan** [comment]
For your understanding, 
(as far as I am not wrong)
s.unwrap() is almost equivalent to : 

match s {
 Some(s) => s,
 None => panic!()
}

Therefore, it inherently takes the ownership of s.
