### ISSUE TITLE
[Question] how to debug Homework #2

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#128]
Document suggests AddressSanitizer to debug homework#2 but I can't figure out how to use it. 
Could you elaborate on it? I have no idea how to fix my code.. :(

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-696788789
Run `cargo_asan` insteas of tsan. But this is for fixing memory related issue. If you need to inspect your code step-by-step, you should use the debugger.

**Comment by wltn0029** [comment]
I've just found out command to see the result of test,
`cargo test --test linked_list` and `cargo test --doc linked_list`
And it helped me to pick out wrong implementation.

But anyway, debugger would be a fundamental way to debug the code.
Thank you for answering! :)
