### ISSUE TITLE
[Session 12, LIVE, mandatory] October, 15th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#134]
- We'll have a **mandatory live session** on October, 15th.

- **It's the practice for the midterm exam.  Please prepare your environment as instructed in #116.  A failure to do so will automatically give you 0 points for the midterm exam.**  Please [join the room](https://meet.google.com/zqd-qmgd-sga) on time.

- We'll also conduct the Q&A session as usual.

**Comment by ehgus** [comment]
I'm sorry but I didn't know it until I check it now. In my defence, I had a exam today so I was thinking of postponing whating video tonight. 

Do I get 0 points for this midterm exam? Again, I'm very sorry that I noticed it late.

**Comment by jeehoonkang** [comment]
@ehgus as far as you properly conduct the actual midterm exam, you'll not be punished by not attending the practice session.
