### ISSUE TITLE
Java causality test case 6, 7

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#137]
6.
```
Initially A = B = 0

Thread 1
r1 = A
if (r1 == 1)
   B = 1

Thread 2
r2=B
if (r2 == 1)
    A = 1
if (r2 == 0)
    A = 1

Behavior in question: r1 == r2 == 1 allowed?
```

**My solution**
- We need promise A=1 for the behavior.
- Then try to certify A=1 at thread 2.

A |[ 0 ] [666] { 1 } [667]
B |[ 0 ]    [666]    [ 667 ] 
view : (A,0) , (B,0)

= (r2=B) => read 666.
A |[ 0 ] [666] { 1 } [667]
B |[ 0 ]     [666]   [ 667 ]
view :  (A,0), (B,666)
r2 : 666

= if(r2==1) A=1; if (r2==0) A= 1 => nothing happens, promise A = 1 is not certified.

- promise is not certified, and there's no case that satisfy the behavior. Not allowed.

**Solution**

> Decision: Allowed. Intrathread analysis could determine that thread 2 always writes 
> 	1 to A and hoist the write to the beginning of thread 2.
   
**Question**
How can we determine thread 2 always writes 1 to A?

**For certification, do we need _only one possible case_?**

7.
```
Initially, x = y = z = 0

Thread 1:
r1 = z
r2 = x
y = r2

Thread 2:
r3 = y
z = r3
x = 1

Behavior in question: r1 = r2 = r3 = 1.
```

**Possible execution order allowing behavior**
Thread 1 reordered to
``` r2=X ; Y = r2 ; r1 = Z ```
Thread 2 reordered to
``` X=1 ; r3 = Y ; Z=r3 ```

Then execute   (T2) X=1 -> (T1) r2=X -> (T1) Y=r2 -> (T2) r3=Y -> (T2) Z=r3 -> (T1) r1 = Z.

**In promising semantics**
- First, certify promise (X=1) at thread 2.
- Then, certify promise (Y=1) at thread 1
    --> **while certifying the second promise, can I use the first promise?**
       (It seems like when you're certifying multiple promises, you can only use other promises that are certified within the same thread) ( so It seems we cannot use the first promise to prove second promise, then how can we prove this?)

**Comment by integerblue** [comment]
6. I don't get what you mean with 666s. 
7. I think we can promise something using other thread's certification. We can certify x=1 and using that information, we can certify y = r2 because r2 =x beforehand.

**Comment by AnHaechan** [comment]
@integerblue 
6. I did similar to the lecture material, representing arbitrary inference.
 Considering what professor answered to your recent question, it seems like promise is certified if there is only one possible case.

7. But from [https://github.com/kaist-cp/cs492-concur/issues/131](url) ,
it seems like we cannot use promise that is certified from the other threads.
In causality test case #20 , I was able to prove the behavior if I can use promise from another thread. (Even if the correct answer is disallowed)

**Comment by AnHaechan** [comment]
Well I wasn't understanding correctly about recertification process, so that was the reason. 
To sum up :
(1) a thread can use already certified promises from another thread
(2) re-certification of promise must be done **every** execution step, until the message is actually written.
