### ISSUE TITLE
[Question] About promising semantics of thread join & previous midterm problem

### ISSUE THREAD

**Issue by c0m0r1** [kaist-cp/cs492-concur#138]
I have two questions about promising semantics & coursework.

1. How can we express behavior of thread joining as promising semantics? I tried it with global message view (like mfence) + some instruction order restriction. but I don't know if it is correct.
2. Can we get previous midterm problems to practice the exam?

Thanks.

**Comment by jeehoonkang** [comment]
1. You can emulate thread join as release/acquire synchronization via a dedicated location.
1. Sorry, I'll not disclose the previous midterm problems for this time.

**Comment by jeehoonkang** [comment]
Closing; please reopen this issue if you have follow-up questions.
