### ISSUE TITLE
Certification of promise

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#139]
I have 2 questions about promise certification.

1.
- About re-certification
In the lecture slide 54-56,
we only did the initial certification of promise.
Can we consider as 're-certification at every step' of execution' was omitted for simplicity?

2.
- About certification
In the lecture slide 55,
to certify a promise, we assumes 666's represent future interferences.
However, if we re-certify at every step of execution, then is there any reason to consider 666's in certification?
(Since we're recertifying the promise in all actual future steps)

3.
-  In the process of certification,
the cases will diverge because of different loads.  (For example,  X | [ 0 ]   [ 1 ]   and  view_thread1 = (X,0) then we can load either 0 or 1)
In such possibilities, to certify the promise, is it enough to show there is just **one possible case that promise is certifi-able**? (그냥 되는 경우 하나가 존재한다는 것만 보이면 됨, certify 안되는 여러가지 경우 있어도)

**Comment by integerblue** [comment]
1. I agree with you. The executions of thread 1 didn't have an impact on thread 2, so the certification of the initial step was valid at all times.

2. I think the professor just wanted to ensure that any random values could be inserted between timestamps so that we should check the validity of certification without concern of other threads. However, I am also curious that those arbitrary values could ruin certification as I asked in https://github.com/kaist-cp/cs492-concur/issues/136#issuecomment-708383402.

3. I think certification should be possible in any case. Certification is for that a value could be written in some future, and it is promised. If the value couldn't be written at some possibility, then certification fails.

**Comment by AnHaechan** [comment]
@integerblue 
I have question about 3.
```
Initially A = B = 0

Thread 1
r1 = A
if (r1 == 1)
   B = 1

Thread 2
r2=B
if (r2 == 1)
    A = 1
if (r2 == 0)
    A = 1

Behavior in question: r1 == r2 == 1 allowed?

Decision: Allowed. Intrathread analysis could determine that thread 2 always writes 
	1 to A and hoist the write to the beginning of thread 2.
```

To prove this behavior, we need to promise `A=1` in thread 2. 
However, if we assume there is [666]s in the location B, the promise cannot be certified.

Therefore I guess the correct method is either 1 or 2 such that
`1 : consider [666]s at every (re)certification & promise can be certified if there is only one case.`
`2 : do not consider [666]s & promise can be certified if it can be certified(actually written) in all cases.`

How do you think about this?

**Comment by integerblue** [comment]
I have the same question about that in https://github.com/kaist-cp/cs492-concur/issues/136#issuecomment-708383402. 
The dependency of the other variables might cause the impossibility of the certification.
I think I don't get what the professor wants to talk about by showing the possibility of 666's. 
Hoping to get a concrete explanation for it.

**Comment by AnHaechan** [comment]
I think what professor meant by 666s, 'arbitrary interferences' is
the same as 'we need to recertify promise at every step'.

So it is enough to do with the method 2, '2 : do not consider [666]s & promise can be certified if it can be certified in all cases.' 
As 666s are not really 666s but it just represents interferences in memory when we are to recertify at every step.

**Comment by integerblue** [comment]
It seems that we only consider arbitrary values in certification, not recertification, as explained in https://github.com/kaist-cp/cs492-concur/issues/136#issuecomment-712689813.

**Comment by jeehoonkang** [comment]
We need arbitrary values not only in certification but also in re-certification.

**Comment by integerblue** [comment]
@jeehoonkang Then even if the arbitrary value exists, could we choose to advance to another value, to promise it? I thought the promise should be fulfilled in any case, but this choice seems it's not. Could you also answer #161 to clarify this?

**Comment by jeehoonkang** [comment]
@integerblue let's continue the discussion at #161.
