### ISSUE TITLE
[Question] HW3 correctness::drop_sync failed with check-loom

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#143]
I am struggling with correctness::drop_sync with check-loom.
There are two invocations of the test and the second one fails with assertion failed with 1 !== 2
I printed the order of threads and execution of drops, and I figured out that both invocations are the same as the order.
However, the first one succeeds and the second one does not.
I tried with the debugger but it was the same. 

I figured out that fence was recently added to the module imported.
Should we use fence to deal with drop_sync?

Thank you.

**Comment by tomtomjhj** [comment]
* Please read this doc for precise synchronization requirements <https://github.com/kaist-cp/cs492-concur/blob/master/homework/src/arc.rs#L18-L37> You can achieve this by simple release-acquire synchronization similar to locks covered in the lecture.
* `check-loom` will try almost all possible reorderings permitted by the memory model and this can be very hard to understand by printing logs or debugger. Try drawing the view diagram (?) presented in the lectures to understand this behaviors.

**Comment by tomtomjhj** [comment]
* `fence` is not necessary (but the optimal implementation makes use of fence, and we haven't covered this in the lecture yet). Just removed `fence` from the import list. I'm sorry if this confused you.
