### ISSUE TITLE
[Question] The implementation of lock and unlock function in CLH lock

### ISSUE THREAD

**Issue by TonyWild** [kaist-cp/cs492-concur#144]
![image](https://user-images.githubusercontent.com/18462177/96214485-88e36300-0fb6-11eb-908f-f65ae5b7fdf2.png)

In this figure in the lecture, I think the node below is returned by the lock function, but the data in the node above is changed by the unlock function.
Shouldn't be the node below (indicated by "node, token") change?

**Comment by integerblue** [comment]
unlock is triggered by the thread which held prev node, and lock is triggered by the thread which newely created the node.

**Comment by TonyWild** [comment]
Ah, I can finally understand what's happening in there.
I thought there could be a situation where unlock function stores false not at the prev node so the thread cannot lock successfully, but there were none. Thank you!
