### ISSUE TITLE
[Question] about hw2 testing

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#145]
I entered source ./scripts/grade-utils.sh    to grade my hw2, then

![image](https://user-images.githubusercontent.com/47855517/96219824-94d52200-0fc2-11eb-994e-55da087b7dd5.png)
above error happend. What should I do?

**Comment by TonyWild** [comment]
The command uses grade-2.sh, instead of grade-utils.sh

**Comment by tomtomjhj** [comment]
```
./scripts/grade-2.sh
```

**Comment by jessi68** [comment]
Thank you. it was my falut..
