### ISSUE TITLE
about homework2  undeclared module ptr

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#146]
like below image, In src/linkedlist.rs 
std::ptr is imported. But when I graded it then 
I have an error like undeclared module ptr. 

![image](https://user-images.githubusercontent.com/47855517/96223198-7e31c980-0fc8-11eb-97f4-8f29f85457d6.png)

**Comment by tomtomjhj** [comment]
please send me an email with your code

**Comment by jessi68** [comment]
> please send me an email with your code

Thank you I sended mail to you.
