### ISSUE TITLE
[Question] debugging test case

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#148]
is it possible to debug specific test case by using lldb? 

ex) I want to debug the `cargo test --test arc --features check-loom`, but I can't find how to do it.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/143#issuecomment-709748617

**Comment by integerblue** [comment]
You can edit the tests/arc.rs with #cfg[check-loom]. Note that this is not exact.
