### ISSUE TITLE
[Quesion] Raw lock and try_raw_lock principle in spinlock.rs

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#149]
![image](https://user-images.githubusercontent.com/47855517/96259055-f9f73a80-0ff7-11eb-9821-f5d34fa4a8c9.png)
I underatand spinlock code by lecture in 10/13. 
But In raw_lock and try_raw_lock, implementation is different from spinlock.
Can I know why raw_lock and try_raw_lock are implemented such way and its principles?

**Comment by tomtomjhj** [comment]
Can you point out the differences?

**Comment by AnHaechan** [comment]
If lock is free(unacquired by nobody) then you acquire the lock and Ok<()> is returned.
Else, just return Err<()>.

Difference fron .lock() is that you don't go to loop (i.e. wait until that lock is released)

**Comment by integerblue** [comment]
It seems okay to me. Could you elaborate more on it?

**Comment by jeehoonkang** [comment]
No images, please.  Closing; please create a new issue.
