### ISSUE TITLE
[Question] Homework3 make_mut() function borrowing

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#151]
Hello, I have question about writing `make_mut()` function.
I accessed to ArcInner by dereferencing the `this.ptr` and tried to borrow `data` mutably, but compiler does not allow borrowing the `data`.
When accessing the memory pointed by `ptr: NonNull` as an element of the referenced as `&mut Arc`, is it considered as double mutably borrowing to mutably borrow the element? I tried to figure out the reason, and this is the only answer I can think of.

**Comment by tomtomjhj** [comment]
To get the `&mut T`, just do `Self::get_mut_unchecked(this)`. 

> double mutably borrowing to mutably borrow the element?

Can you clarify what that means? Something like this?
```rust
fn fst<T1, T2>(pair: &mut (T1, T2)) -> &mut T1 {
    &mut pair.0
}
fn main() {
    let mut pair = (String::from("0"), String::from("1"));
    println!("{}", fst(&mut pair));
}
```

**Comment by haeeun-14** [comment]
Yes, when there is a struct with several elements, whether the mutable references to the struct and a element would cause error or not, as they both can mutably access to the element. In this case, it would not because the function consumes the mutable reference to the `Arc`?

**Comment by tomtomjhj** [comment]
`fst` is good because having `&mut (T1, T2)` means exclusive access to both fields. However this is not the case for `Arc`. That is, it can be problematic to get `&mut T` from `&mut Arc<T>` because https://github.com/kaist-cp/cs492-concur/issues/150#issuecomment-710755092 . This is why  `get_mut_unchecked` is an `unsafe fn`.
