### ISSUE TITLE
[Question] Sync and Send in lock.rs

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#154]
```rust
unsafe impl<L: RawLock, T: Send> Send for Lock<L, T> {}
unsafe impl<L: RawLock, T: Send> Sync for Lock<L, T> {}
```

In this [code](https://github.com/kaist-cp/cs492-concur/blob/master/lock/src/lock.rs#L27-L28), What I understand is that the data `T` don't have to be Sync, because about `T`, there will not be multiple access from threads. 

```rust
unsafe impl<'s, L: RawLock, T: Send> Send for LockGuard<'s, L, T> {}
unsafe impl<'s, L: RawLock, T: Sync> Sync for LockGuard<'s, L, T> {}
```

Then, In this [code](https://github.com/kaist-cp/cs492-concur/blob/master/lock/src/lock.rs#L87-L88), the `LockGuard`, Why we have to put Sync in `T`? Is it because of dereferencing?

**Comment by AnHaechan** [comment]
Think of the purpose of Lock and LockGuard.

Lock<T> is for making (only) Sendible data T to Sendible+Sync-able data. How did you do that? Using RawLocks we have learnt (spinlock, clhlock, ...).

However, LockGuard<T> is what you get after acquiring a Lock, to access the inner data T. It's purpose is not handling concurrent access of multiple threads. So you cannot make only Sendible T to Sync-able. If T was originally Sendible, then LockGuard is Sendible. If T was originally Sync-able, then LockGuard is Sync-able.
