### ISSUE TITLE
[Question] [Homework3] deallocating the memory in drop function

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#156]
I have problems in writing `drop()` function. To deallocate the memory, I used `Box::from_raw` to take the ownership into the scope and used `mem::drop` function to drop `self` and box in order. I thought it would work because the self will drop its elements in order, including NonNull pointer it has, and the variable which has the ownership of the box will be out of scope when the drop function ends. But the canary test showed me I failed to drop the canary. 
`unning 5 tests
test correctness::clone_drop_atomic ... thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/arc.rs:245:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
....
failures:

failures:
    correctness::clone_drop_atomic`
Can you point out what I got wrong?

**Comment by integerblue** [comment]
I think you understood well except you don't need to drop self, because it is automatically handled when the drop impl finishes.
Correctness test cases are basically based on relaxed behaviors between threads, so I think you could focus on that. Check #143.

**Comment by Lee-Janggun** [comment]
Canary testa are related with ordering. If these are failing it is most likely that
a) You have incorrect orderings
b) You are missing a ordering. 

Make sure that your `Ordering::Release` and `Ordering::Acquire` match properly.

I had a similar problem with `drop_sync`, and for me my problem was b)

**Comment by Jaegoomon** [comment]
@Lee-Janggun  
I have some questions. I think I just use Ordering options in `fetch_and_add` and `fetch_and_sub` in `clone` and `drop` function each. Is there more function or method that I have to deal with? 
I think I just deal with those two function well, but it doesn't work in `drop_sync`. Is there any part that I make some mistakes?

**Comment by integerblue** [comment]
#157 might help you.
You could use other solution than this.

**Comment by Jaegoomon** [comment]
Oh, thank you. It helps me alot!

**Comment by haeeun-14** [comment]
@Lee-Janggun 
I thought the semantics of Aquire and Release was just the allowance of read or write from specified time. Is the number of use of Aquire should be matched with that of Release, even for the function which do not change the shared memory?

**Comment by Lee-Janggun** [comment]
@haeeun-14 I'm very sorry for not answering the question. I didn't realize there was one until now. If you read the [Ordering documentation](https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html), the description for `Release` says that 

- all previous operations become ordered before any load of this value with `Acquire` (or stronger) ordering.

I understood this as this if a load operation with `Acquire` is executed, it is guaranteed that all Ordering executions before this   `Release` ordering was done before this load ordering. The reason this is important especially with `drop_sync` is as mentioned in #157 , the actual execution of the `drop` for the inner element may be re-ordered outside the if statement drop.

**Comment by integerblue** [comment]
It is different with your understanding, it means that the value written by store release should not be read by the threads before.

**Comment by haeeun-14** [comment]
@Lee-Janggun @integerblue 
Ah I missed some points. Thank you for pointing out!
