### ISSUE TITLE
[Question] Clarification on rust's criteria for invalidating SMA (Session 02 slides)

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#160]
(Edit: Sorry for uploading an image.)
```
fn main() {
    let v = vec![1,2,3];

    let p = &v[1];
    v.push(4);
    println!("v[1]: {}",p);
}
```
In slide 25 (in session 02), it says that all variable pairs (regarding the same vector above) that (1) have overlapping lifetime and (2) are not borrowing & borrowed pairs are regarded as SMA's. 

However, consider the following example.
```
fn main() {
    let v = vec![1,2,3];

    let p = &v[1];
    let q = &v[2];
    println!("v[1]: {}",p);
}
```
Although p and q satisfy the above condition to be an SMA, the rust compiler would not detect this as SMA.
Will it be correct to understand the criteria needs an additional condition that 'such pair must contain a mutable reference'?

**Comment by integerblue** [comment]
```
let p = &v[1];
let q = &v[2];
```
These are immutable borrows of v so that multiple borrows can occur at the same time because those immutable borrows cannot affect each other. However, if you change any line to &mut v[], then it wouldn't compile because mutable borrow could affect other immutable or mutable borrows so that only one mutable borrow could exist at the same time.

**Comment by totolacky** [comment]
I agree with you! I was just wondering if the following SMA evaluating criteria (which was given in the lecture, slide 25) should be modified because the criteria also consider the all-immutably-borrowing case as SMA.

Criteria: 
1. Calculate each owner/borrower’s “lifetime”
2. List up the pairs of overlapping lifetimes
3. Ignore borrowed & borrowing ones
4. The remaining pairs are regarded as SMA’s

**Comment by integerblue** [comment]
In the lecture, the professor mentioned about immutable and mutable borrows, but yes, if it was included in the criteria, it would be more clear.

**Comment by jeehoonkang** [comment]
Thank you for pointing out that.  I updated the slides: https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g950aa4a629_95_65  I mentioned "Remove pairs of immutable borrows".

**Comment by totolacky** [comment]
Thanks!
