### ISSUE TITLE
[Question] Promising semantics of Ticket lock and CLH lock

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#162]
I've tried my best to draw an execution in promising semantics for Ticket lock and CLH lock, but I'm not sure if I did it correctly. As I cannot add images here, I created some slides in the following link.

https://docs.google.com/presentation/d/1ttWFnQV_X4XSSA-5cSg_XURqrvALisnsAfkdygHs1xE/edit?usp=sharing

Are the drawings correct? Especially, I'd like to know if I represented pointer swapping in CLH lock correctly.
I'd love to get some feedback either through replies in this issue, or direct comments in the slides (I have enabled the feature!).

Thanks in advance! 😀

**Comment by totolacky** [comment]
Update: I added an alternative drawing of CLH lock, where the 'memory swap' is represented using global views.

**Comment by integerblue** [comment]
In ticket lock representation, why does next and curr start with n? They should start with the same value so that the first thread could escape while loop. You might want to look at fetch_add() because it returns the previous value of AtomicUsize.

Next, in slide 7, you could draw curr n+1 apart from n because they don't need to be adjacent. Arbitrary value could be inserted between them because the store operation is used.

**Comment by integerblue** [comment]
In CLH lock, I think the creation of the node should be inserted before, as T. To elaborate more, as swap executes, another block which is swapped with tail should be there before so that two blue lines could exist.

**Comment by jeehoonkang** [comment]
Thanks for drawing the figure!

## Ticket lock

- page 3: as @integerblue said, I think the initial value must match.
- page 4: it would be easier to understand if the steps for getting the ticket (`next`) and waiting for turn (`curr`) are split.
- page 7: as @integerblue said, curr's `n+1` message doesn't need to be adjacent to the `n` message.

## CLH lock

- `tail` is a pointer, and its value must be pointing to a node.  I think it's eaiser to understand if `tail` messages doesn't contain values.  Also, I think it's better to additionally draw the location for the initial tail.
- page 12: T1's view on data must be on the initial message.
- I don't understand the "alternative" drawing.  Note that **swap is acting on a single memory location**.  You're swapping the memory location's value with a register's value.

**Comment by integerblue** [comment]
@jeehoonkang 
I am not sure how we could express the tail as a pointer. Should the node 1, 2, 3 have the memory location value and use them as the tail's value? This seems to make sense...
Anyway, I am afraid of how these drawings could appear in the midterm exam questions. Should we worry about how to actually draw the picture and submit?

**Comment by totolacky** [comment]
@integerblue @jeehoonkang Thanks for the feedback!
I have modified both locks, and actually re-drew the CLH lock using another representation (representing tail as 'pointers'). Could you please check this out and see if this is correct?

**Comment by integerblue** [comment]
@totolacky It seems okay to me, but except that the tail nodes should be apart because they are swapped in relaxed behavior. 
Great work!

**Comment by totolacky** [comment]
@integerblue I put the tail nodes adjacent because I thought 'swap' was an atomic operation. As the ordering is relaxed, I did not introduce any per-message-view (which must be done for release ordering) nor synchronized the per-thread view with another per-message-vies (which must be done for acquire ordering).

**Comment by integerblue** [comment]
@totolacky Oh, I thought compare_and_swap is an atomic operation, not swap. It seems that swap is an atomic operation too because swap gets value out and puts in another value in an atomic way. Sorry for the confusion!

**Comment by jeehoonkang** [comment]
@totolacky @integerblue 

- Page 17: I think T2 is waiting for the node n to be false, right?
- Page 17: After failing to acquire the lock, I think T2's view on data is not updated.  Because data view is not released at node n's value T.

**Comment by totolacky** [comment]
@jeehoonkang Fixed them. Thanks for your feedback!

**Comment by j2k0618** [comment]
@jeehoonkang  But for Spin Lock in slides, even if T2 failed to acquire the lock, T2's view on data is updated. What is the difference between them?

**Comment by totolacky** [comment]
@j2k0618 It's not about the fact that T2 failed to acquire the lock. It is because the node value that T2 read did not release yet, so there is no release view to synchronize with.
