### ISSUE TITLE
[Question] usize sync Trait

### ISSUE THREAD

**Issue by isyangban** [kaist-cp/cs492-concur#163]
On slide 66 (https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g9b7c2afa6a_0_6) and on lecture ( https://www.youtube.com/watch?v=ja_cdKF72vU ), it says primitive types such as **usize** is **Send** but not **Sync**

However, after reading the documentation

1. [trait.Sync](https://doc.rust-lang.org/std/marker/trait.Sync.html)\
There is auto implementors for Sync for types like usize (`impl Sync for usize`)
and no opt-out code like `impl !Sync for usize`
2. [Rust nomicon](https://doc.rust-lang.org/stable/nomicon/send-and-sync.html) says that 
> Send and Sync are also automatically derived traits. This means that, unlike every other trait, if a type is composed entirely of Send or Sync types, then it is Send or Sync. Almost all primitives are Send and Sync, and as a consequence pretty much all types you'll ever interact with are Send and Sync.

So I am a little confused about which is right or wrong. Also is there a code example that shows if that a type is **Sync** or not?

**Comment by hestati63** [comment]
Currently, `usize` implemented both Sync and Send.
You can identify the `usize`'s traits implementations in the [docs](https://doc.rust-lang.org/std/primitive.usize.html#impl-Send).

Also, you can test whether the type implements the Sync using the generic type bound syntax like below:
```rust
struct A<T>(T) where T: Sync;

fn main() {
    // ok.
    let _ = A(32_usize);
    
    // compile error. *const usize does not implement Sync.
    let v = v_usize;
    let _ = A(&v as *const usize);
}
```

**Comment by jeehoonkang** [comment]
Thank you for pointing out that and I'm sorry to say wrong things.  I just updated the slide: https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g9b7c2afa6a_0_6

I promise that I'll not ask questions related to `usize: Sync` in the midterm exam.  I corrected it too late.
