### ISSUE TITLE
[Question] About Java Causality test 14 and interleaving in semantics

### ISSUE THREAD

**Issue by aujinsky** [kaist-cp/cs492-concur#164]
Initially, a = b = y = 0, // y is volatile // erased
T1:
r1 = a
if (r1 == 0)
  y = 1
else
  b = 1
T2:
do {
  r2 = y
  r3 = b
  } while (r2 + r3 == 0);
a = 1;

Behavior in question: r1 == r3 = 1; r2 = 0

1. Without the condition, "y is volatile", is the behavior in question possible?

In the initial state, promise y=1 can be only made. In order to go pass do { ... } and to make promise a=1, I think taking promise y=1 from T1 is mandatory.
However, using the promise a=1 in T1 makes y=1 unreachable.  So, it is not used in T1. 
In T2, in order to make r2=0, promise y=1 is also not used. However, this makes r2+r3 == 0, so while loop does not terminate. Making an another promise is impossible, at this stage, so I think it is impossible.
It may be possible to get this result if starting from promise T1; b=1 T2; a=1 is possible, but I think it is simply not possible(since it works like reordering 2 lines at once which are located in different threads)  and we should always 'build' our promises from scratch.

2. Why is it okay to make promises which depends on taking another thread's promise or not?

Second question is, every promise should be able to reach in all interleaving of threads.  However, in above case, reaching its promise y=1 in T1 may be impossible by taking another promise a=1 in T2 or not(since it effects the if branch).  In the point of view  of T1, "using the promise of T2 or not" can be understand as "reordering of T1 has occurred or not". It depends on the another thread's manner, so shouldn't it be treated as interleaving, meaning that promise y=1 should be reached whether taking a branch or not?

**Comment by integerblue** [comment]
1. We can build our promises based on what we already promised.

2. I think that is why recertify every step, which means we don't need to care about other cases, vut I'm not completely sure about that. #161.

**Comment by jeehoonkang** [comment]
1. The behavior is forbidden even if they are not volatile (release/acquire).

  > In the initial state, promise y=1 can be only made.

  Yes it is, and y=1 means b=1 is not eecuted and r3=0.

  > In order to go pass do { ... } and to make promise a=1, I think taking promise y=1 from T1 is mandatory.

  You don't need to say that.  Just you can say, in the initial state, T2 cannot promise to write a=1 on its own.

  > In T2, in order to make r2=0, promise y=1 is also not used. However, this makes r2+r3 == 0, so while loop does not terminate.

  I don't quite understand its meaning...

1. Another thread's promise is, from the other threads' point of view, a message that is firmly written to the memory.  The obligation is the promsing thread needs to certify that it can always fulfill the promise.  The other threads, on the other hand, rely on the promising thread and read it without any restrictions.

  I don't quite understand your second question, honestly.  What does it mean by "reaching its promise"?  If it's convenient for you, please ask in Korean.

**Comment by integerblue** [comment]
Ah, you're right. b=1 cannot be promised because it needs a=1 to be promised, but T2 cannot do on its own.

**Comment by aujinsky** [comment]
그러니까 제 말은, 
1번에서 이어지는 말은 먼저 y=1을 promise해야만 a=1를 promise할 수 있으나 r2가 0이 되게 하려면 T2의 instruction r2=y에서 T1의 promise y=1을 참조하면 안되고, 그렇기 때문에 r2+r3==0이 다시 되어버려서 loop가 끝나지 않는거 같다는 의미였습니다. 

2번에서 물어보고 싶었던 것은, 본질적으로 다른 thread T2의 promise를 사용할 지 사용하지 않을지는 (thread T1의 시점에선) interleaving과 다르지 않은데, 모든 interleaving에서 promise의 re-certify를 확인하는 것 처럼, 모든 promise를 사용하는지 사용하지 않는지의 여부에 따라서 promise를 re-certify해야하는 것인지 궁금하다는 것이 었습니다. 그렇게 해야 한다면, 위에서 처럼 y=1과 a=1를 함께 promise하는 것은, T1의 r1=a에서 T2의 promise a=1을 참조하는지에 따라서, y=1을 certify할 수 있을 수도 있고, 할 수 없을 수도 있게 되어서 불가능해지기 때문에 이런 질문을 하게 되었습니다.

감사합니다.

**Comment by jeehoonkang** [comment]
1. 논리를 다소 이해하기 어렵습니다. 실행 순서에 대한 이야기가 없어서 그런데요, https://github.com/kaist-cp/cs492-concur/issues/141#issuecomment-712950417 이 코멘트에서처럼 처음에 실행할 instruction이 무엇인지에 따라 케이스를 나눠서 따져보면 도움이 될 것 같습니다.

    In English: to reason about test cases 14/15, please see the comment linked above.

1. 여전히 무슨 말씀이신지 잘 모르겠습니다... 구체적인 execution을 제시해주시면 그게 가능한지 여부를 말씀드릴 수 있을 것 같습니다.

**Comment by aujinsky** [comment]
일단, 저는 promise가 존재하는 경우에도 그것을 사용하지 않는 경우가 있다고 생각했습니다(re-order가 되지 않고 그냥 원래의 order대로 실행이 될 수도 있으니까 말이죠).
**그렇다면, T1에서 y=1 T2에서 a=1을 동시에 promise하는 것이, 가능한지**에 대해서가 궁금합니다. 왜냐면, T1의 instruction r1 = a에서, a=1이었는지, a=0이었는지에 따라서 후의 execution에(a=1이라면 false branch로 들어가게 되죠) 영향을 끼치고, 결국 T1에서 y=1을 fulfill하지 못하게 되는 결과에까지 이르게 됩니다.

**Comment by jeehoonkang** [comment]
@aujinsky You cannot promise y=1 in T1 and a=1 in T2.  In a single step, only a single thread can promise to write a single message.

**Comment by aujinsky** [comment]
말을 좀 이상하게 한 것 같은데, y=1을 먼저 promise하고, a=1을 이를 이용해서 promise하는 것이 가능한지에 대한 질문이었습니다.

**Comment by jeehoonkang** [comment]
- You can promise to write y=1.
- Then you can promise to write a=1.
- But after that, T1 cannot read a=1 at r=a, because then you cannot fulfill y=1.

**Comment by aujinsky** [comment]
원래 promise는 모든 interleaving에 따라서 fulfill되어야 했습니다(저는 그게 re-certification의 의미라고 생각했습니다). 하지만 그것과는 다르게 promise가 다른 모든 promise의 read의 경우에 따라서 fulfill되지 못하는 경우가 있어도, 괜찮은 이유는 무엇인가요?

**Comment by jeehoonkang** [comment]
@aujinsky I don't understand what you've just said...  Please refer to #161 to understand the meaning of (re-)certification.

**Comment by aujinsky** [comment]
re-certification에 대해서 잘못 이해하고 있었던 것 같습니다. https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713513362를 보고 이해가 되었습니다.
Thank you for the answers.
