### ISSUE TITLE
[Question] Java test case 14 ‘volatile’

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#166]
```

Initially, a = b = y = 0, y is volatile

Thread 1:
r1 = a
if (r1 == 0)
  y = 1
else
  b = 1

Thread 2:
do {
  r2 = y
  r3 = b
  } while (r2 + r3 == 0);
a = 1;

Behavior in question: r1 == r3 = 1; r2 = 0

Decision: Disallowed In all sequentially consistent executions, r1 = 0 and
	the program is correctly synchronized. Since the program is correctly
	synchronized in all SC executions, no non-sc behaviors are allowed.
```

In this case, it seems 'y is volatile' is the key for the answer, but I don't get the meaning of it. What does it mean with `y is volatile` and how does volatile y affects this case?

(It seems that if we erase the term `y is volatile`, this behavior seems to be allowed, right?)

**Comment by integerblue** [comment]
Check #136.
And yes.

**Comment by totolacky** [comment]
Without the volatility condition, how can we promise a=1 using promising semantics? I think T2 cannot certify a=1 as the arbitrary interference of y,b values are not guaranteed to be nonzero, and an infinite loop can occur.

**Comment by integerblue** [comment]
@totolacky You could first promise b = 1 in T1, and then promise a = 1 in T2.

**Comment by totolacky** [comment]
@integerblue How do we promise b=1? Given only T1, 0 is the only value of a present in the memory, so I thought that the best we can do is to promise y=1. However, promising a=1 on top of y=1 doesn't do any help on checking if r1==r3==1, r2==0 is possible.

**Comment by integerblue** [comment]
@totolacky I misunderstood the if statement. Sorry for the confusion.

**Comment by totolacky** [comment]
@integerblue Then, is the behavior r1==r3==1, r2==0 allowed?

**Comment by integerblue** [comment]
@totolacky It is disallowed in any case(with and without the volatility of y)

**Comment by totolacky** [comment]
@integerblue But without considering the promising semantics, a=1 seems to be independent with other instructions in T2. Shouldn't store hoisting of a=1 be allowed here? I'm confused now.

**Comment by integerblue** [comment]
I think because of the while loop, it is not sure that we could escape the infinite loop or not. That seems to be the reason why they're actually dependent.

**Comment by totolacky** [comment]
Makes sense to me!
