### ISSUE TITLE
Promise of release store

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#167]
When we want to promise release store,
do we need to promise(?) per-message view too?

If so, what view should we attach to the promised message?

**Comment by totolacky** [comment]
A promise is 'a message that a thread **can** write (under any interference of other threads)'.
I'm not sure what you mean by 'promise release store'. Can you provide a more concrete example?

**Comment by AnHaechan** [comment]
{X=0 ^ Y=0}
Y=1
X.store(1,release)
{X=1 ^ Y=1}
In this example, (though there is no reason to do)
if we want to promise X.store(1, release),
should we attach release view to the promise message (X,1)?

**Comment by totolacky** [comment]
I agree that some 'per-message-view' effect should be considered in that case. For example,
```
initial values: X=0, Y=0

T1:
  Y=1;
  X.store(1,release)

T2:
  r1 = X.load(acquire)
  r2 = Y

[is r1 == 1, r2 ==0 possible?]
```
If we do not take the release/acquire into account, the behavior seems to be possible in promising semantics. However, it should be forbidden in real situations. @jeehoonkang In these situations, exactly how should we set these per-message-views of promises?

**Comment by tomtomjhj** [comment]
> However, it should be forbidden in real situations.

Because of this, Promising semantics doesn't allow promising a release write (not covered in the lecture).

**Comment by totolacky** [comment]
I think that actually makes sense, as promises are introduced to model store hoisting. If the store is a release store, then the instruction cannot be hoisted anyway!
