### ISSUE TITLE
[Question] Test cases 2&3

### ISSUE THREAD

**Issue by zhanto97** [kaist-cp/cs492-concur#169]
I have a question about test cases 2 & 3
```
# Test case 2
Initially, x = y = 0

Thread 1:
r1 = x
r2 = x
if r1 == r2
  y = 1

Thread 2:
r3 = y
x = r3

Behavior in question: r1 == r2 == r3 == 1

Decision: Allowed, since redundant read elimination could result in simplification
	of r1 == r2 to true, allowing y = 1 to be moved early.

Notes: In SC executions, both reads of x always return the same value (i.e., zero),
	so that r1 == r2 is always true in SC executions.
```
It says in SC executions, both reads of `x` always return the same value so that `r1 == r2` is always true in SC executions.
However, when a third thread appears which just writes some value to `x`, it says that there are SC executions in which `r1 != r2`
```
# Test case 3
Initially, x = y = 0

Thread 1:
r1 = x
r2 = x
if r1 == r2
  y = 1

Thread 2:
r3 = y
x = r3

Thread 3:
x = 2

Behavior in question: r1 == r2 == r3 == 1

Decision: Allowed, since redundant read elimination could result in simplification
	of r1 == r2 to true, allowing y = 1 to be moved early.

Notes: Same as test case 2, except there are SC executions in which r1 != r2
```
Wouldn't the following execution order in test 2 contradict the claim? `r1` reads 0 and `r2` reads 1
```
y=1  ||
r1=x ||
     || r3=y
     || x=r3
r2=x ||
```

**Comment by integerblue** [comment]
Agreed, the same question in https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713331511.

**Comment by tomtomjhj** [comment]
> Wouldn't the following execution order in test 2 contradict the claim?

That is not a SC execution.

**Comment by totolacky** [comment]
What is the definition of an SC execution? Can I understand it as 'an execution order when no thread interleaving happens'? i.e. 'no other thread runs before the currently running thread finishes'?

Also, why are we considering SC execution here? Is it because the SC-executed results are somehow related to the results with thread interleaving enabled? ex> 'if a result p can appear in SC case, then p can also appear in thread interleaving case'?

**Comment by zhanto97** [comment]
@tomtomjhj 
I sort of understand why it is not SC execution but my logic does apply to test case 3.
Can you provide a SC execution of test case 3 where `r1 != r2` and explain why it is a SC execution?

**Comment by tomtomjhj** [comment]
SC execution: there is a globally agreed total order of instructions (= no instruction reordering)

```
r1 = x ||      ||
       ||      || x = 2
r2 = x ||      ||
```

**Comment by zhanto97** [comment]
@tomtomjhj Oh, got it. Thank you! Closing

**Comment by integerblue** [comment]
So, SC executions mean considering all thread interleavings?
Therefore, in Q2, there is no other way of interleavings so that r1 == r2 is always true. Thanks!
