### ISSUE TITLE
[Homework 2] optimistic lock coupling for binary search tree (due 12/23)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#17]
https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g6f8c363340_0_51

- IMPORTANT: implement plain binary search tree, not AVL tree
- Paper: https://stanford-ppl.github.io/website/papers/ppopp207-bronson.pdf
- Skeleton: https://github.com/kaist-cp/cs492-concur/tree/master/homework/src/bst
- Grading: TBA

**Comment by jeehoonkang** [comment]
Skeleton code is uploaded.

**Comment by jeehoonkang** [comment]
I will post a more detailed grading criteria soon.

**Comment by jeehoonkang** [comment]
Here are the answers to the questions:


- There's a duplication of information between `Cursor::find()`'s return value and the resulting cursor's `dir`.

  Yes it is, but I'd like to leave the API as is.


- Maybe recursive cleanup isn't different from one-time cleanup.

  In fact, they are different.  Please implement recursive cleanup.


- How to protect the tree's value in `ConcurrentMap::lookup()`?

  Please protect the reads with `WriteGuard`, not `ReadGuard`.  Yes it's ugly, but let's just strongly protect value reads...

**Comment by jeehoonkang** [comment]
- You can submit here: https://gg.kaist.ac.kr/course/2/
- The new deadline is the next Monday, 9pm.

**Comment by jeehoonkang** [comment]
- This homework turned out to be more difficult than I expected.
- I'll explain hw2 and its solution in class next week.
- I'll postpone the deadline by at least a week.

**Comment by dnkim** [comment]
Do you mean we will implement homework based on solution explanation?

**Comment by jeehoonkang** [comment]
@dnkim The specification remains the same, but I'll explain the homework in more details.

**Comment by jeehoonkang** [comment]
## Invariant

`Bst` and `Cursor` observe the following invariant.

- a `Cursor` contains a traversal history from the root to the current node. 
- In `Cursor`, all pointers to nodes are tagged with zero.
- A detached node from `Bst` has at most one (non-null) children, and it's tagged with one.

## Procedures

Each function proceeds as follows.

### `Cursor::pop()`

- Pop the last element in `self.ancestor` and put them in `self.current` and `self.dir`.
- Acquire a read guard for the new `self.current` and put it in `self.guard`.

### `Cursor::push()`

- Validate `self.guard`. If it fails, restart `self.guard` and `mem::forget()` about the given `guard`.
- Push `self.current` and `self.dir` to the end of `self.ancestor`.
- Put the given `current.with_tag(0)`, `guard`, and `dir` to `self.current`, `self.guard`, and `self.dir`.
  Here, `current` is retagged with zero in order to the observe invariant.

### `Cursor::find()`

- Load the pointer to the child.
- If it's null, return ordering (less or greater).
- Compare the given `key` and the child's key.
- Acquire a read lock for the child.
- `Cursor::push()` the child, child's guard, and the comparison result as direction. If unsuccessful, retry from the beginning.
- If the given `key` equals to the child's key, return.
- Otherwise, loop again from the beginning.

### `Cursor::cleanup()`

- Let A be `self.current`.
- If A has a value or `self` is root, stop.
- If A has two children, stop.
- Upgrade A's read lock to write lock.
- Pop, effectively traversing up one level and acquiring the read lock for the parent. Let B be the parent.
- Upgrade the B's read lock to write lock.
- Check if B still points to A as its child. In particular, the pointer should be tagged as zero; otherwise, B has already been detached.
- Tag A's child pointers with one (to observe the invariant).
- Detach and `defer_destroy()` A.
- Loop again from the beginning with `self.current` = B.

### `Bst::insert()`, `Bst::delete()`, `Bst::lookup()`

`Cursor.find()`, and upgrade `cursor.guard` to a write guard; if it fails, retry from the beginning.

**Comment by jeehoonkang** [comment]
I uploaded the scores.  Grading criteria is as follows.
- A (20pts): sequential stress test (address sanitizer on).
- B (20pts): concurrent stress test without deletions (address sanitizer on).
- C (20pts): concurrent stress test with deletions (address sanitizer on).
- D (20pts): concurrent linearizability test without deletions (address sanitizer off).
- E (20pts): concurrent linearizability test with deletions (address sanitizer off).

If your program leaks memory, you'll get partial credits (10pts); if your program crashes, you'll get no credits.
