### ISSUE TITLE
[Question] When and how to update an SC view (global view)?

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#170]
In the [lecture slides](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g47700261b6_13_13), we learned that **whenever we meet an SC fence, the SC view and the thread view must be updated so that they both become the maximum of them** (I'll call this the 'updating rule'). However, I think that this was true in the example **only because T2 actually **read** a value after the fence**. Would this be a correct thought?

If so, what would be the precise condition to update an SC view, and how should we update it?

[Elaboration of the question, from now on.]

In this 'elaboration' section, I tried to give a counterexample so that applying the 'updating rule' may lead to some problems.

This is the example in the slides.
```
init: X=0, Y=0
X = 1;                ||     if Y.load(relaxed) {
fence(SC);            ||         fence(SC);
Y.store(1, relaxed);  ||         assert(X == 1); 
```
In this example, the 'updating rule' must be applied because T2 reads a value (Y=1) that is after the SC fence. Now consider the following example where T2 does not do so.
```
init: X=0, Y=0
X.store(1, relaxed); || X.store(3, relaxed);
Y.store(1, relaxed); || fence(SC);
fence(SC)            || Y.store(3, relaxed)
X.store(2, relaxed); ||
Y.store(2, relaxed); ||
```
By running T1, we get the following memory state. The '-' denotes that the messages are not adjoint.
```
           | <- SC view
X | [0] - [1] - [2]
           |
Y | [0] - [1] - [2]
           |
```
Now we run the first instruction of T2. X=3 can be written before X=1, so we have
```
                  | <- SC view
X | [0] - [3] -  [1] - [2]
           ┌------┘
Y | [0] - [1] - [2]
           |
```
Then, we meet another SC fence. If we need to update the SC view and the per-thread-view of T2 to the maximum of them, then the following memory state (after executing Y.store(3, relaxed)) would never be permitted (as the per-thread-view of T2 will already be at Y=1).
```
X | [0] - [3] - [1] - [2]
Y | [0] - [3] - [1] - [2]
```
However, this memory state is actually possible to achieve! Consider the following total execution order of instructions.
```
init: X=0, Y=0
                     || X.store(3, relaxed);
                     || X.store(3, relaxed);
Y.store(1, relaxed); ||
X.store(2, relaxed); ||
Y.store(2, relaxed); ||
```
This execution order does not violate the semantics of an SC fence. However, it ends up in the memory state that was suggested to be 'impossible' above. We have a contradiction here, so we may conclude that we shouldn't 'update the per-thread-view and SC view to their maximum'.

Am I understanding something wrong?

**Comment by tomtomjhj** [comment]
> it ends up in the memory state that was suggested to be 'impossible' above

It's impossible only in that specific execution.

**Comment by totolacky** [comment]
@tomtomjhj But in the example above, T2's fence runs before T1's fence (in terms of timestamp), but we end up concluding that the memory state is impossible.

**Comment by tomtomjhj** [comment]
> the example above

What example?

**Comment by totolacky** [comment]
@tomtomjhj The example I used as a counterexample. In the example, the memory looked like this just before running the SC fence.
```
     T2 -> |     | <- SC
X | [0] - [3] - [1] - [2]
     ┌-----┘┌----┘
Y | [0] - [1] - [2]
     |      |
```
T1 denotes the per-thread view of T1, and SC denotes the SC view. Here, I said that T2's fence runs before T1's fence in the sense that the 'per-thread view of T1 when executing its fence' (which is T1 in the above figure) is behind the 'per-thread view of T2 when executing its fence' (which is SC in the above figure).

**Comment by tomtomjhj** [comment]
Well I meant the order of running the fence instruction. With my definition, T1's fence runs runs first. Note that there is a global order of **execution step** (running an instruction (load, store, fence, ...), promising a value, and fulfilling a promise), while views are just partially ordered set with join (⊔) operation.

**Comment by totolacky** [comment]
I think I almost got it. 

Then, when drawing the promising semantics, is it okay to understand that **the SC view you draw earlier** (early, in the sense that you physically draw it earlier than the other SC views) **corresponds to a fence() that was run earlier** (early, in the sense of global order of instructions)?

**Comment by tomtomjhj** [comment]
Yes

**Comment by totolacky** [comment]
Got it! Thanks a lot and have a good night 😁
