### ISSUE TITLE
The plan for the remaining of the semester

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#171]
- First of all, thank you all for taking this class and the midterm exam.  I really appreciate it.

- In the remaining of the semester, we will have 3 more homework assignments and 1 final exam.  I'm announcing this now to help you manage your time.

    + Homework 4: "Lock-coupled linked list"
    + Homework 5: "[Split-ordered lists: Lock-free extensible hash tables](https://ldhulipala.github.io/readings/split_ordered_lists.pdf)"
    + Homework 6: "Safe memory reclamation"
    + Final exam: TBA

- As contrary to what I said right after the midterm exam, we will have a Youtube video lecture on the 27th of October (Tue) to learn "lock coupling", which is necessary for doing Homework 4.

**Comment by Lee-Janggun** [comment]
The due of HW1 lasted 4 weeks, while the due of HW2 and 3 lasted 2 weeks. Can we assume that we will have something similar for HW 4 to 6? That is one heavy homework that will last for 4 weeks and two relatively light homeworks that will last for 2 weeks. Thanks!

**Comment by jeehoonkang** [comment]
@Lee-Janggun All homework assignments will be less than 500 lines of code.  (Please be noted that the number of lines of code is not a good proxy for difficulty, especially for concurrent programming, though...)  Dues are TBA.
