### ISSUE TITLE
[Question] What is "SeqCst"?

### ISSUE THREAD

**Issue by lyra95** [kaist-cp/cs492-concur#173]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

According to [doc](https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html#variant.SeqCst), it says:
SeqCst
[−]
Like Acquire/Release/AcqRel (for load, store, and load-with-store operations, respectively) with the additional guarantee that all threads see all sequentially consistent operations in the same order.

I still don't get what this exactly means. I only see it is another kind of Orderings like Acquire/Release/Relaxed we've learned in class.
Could I get a clear explanation with some examples?
And Why is it not allowed in HW3?

**Comment by tomtomjhj** [comment]
`SeqCst` = sequentially consistent = "SC" in the lecture slide. 
* We have briefly covered SC fence in the lecture (but not SC accesses). We'll see more examples of SC fences in the later part of the lecture.
* SC is the strongest ordering constraint that may incur big performance overhead.

**Comment by lyra95** [comment]
I appreciate it.
