### ISSUE TITLE
[Question] [homework3-arc] tests failed with drop() 

### ISSUE THREAD

**Issue by lyra95** [kaist-cp/cs492-concur#174]
I've failed cargo_asan tests.  The message says(I omitted some):

    Running with cargo_asan...

    running 8 tests
    test src/arc.rs - arc::Arc<T>::ptr_eq (line 175) ... FAILED
    test src/arc.rs - arc::Arc<T>::drop (line 308) ... FAILED
    test src/arc.rs - arc::Arc<T>::clone (line 274) ... FAILED
    test src/arc.rs - arc::Arc<T>::count (line 145) ... FAILED
    test src/arc.rs - arc::Arc<T>::try_unwrap (line 196) ... FAILED
    test src/arc.rs - arc::Arc<T>::get_mut (line 80) ... FAILED
    test src/arc.rs - arc::Arc<T>::make_mut (line 233) ... FAILED
    test src/arc.rs - arc::Arc<T>::get_mut_unchecked (line 119) ... FAILED_

For each methods, I got a message that looks like:

    failures:

    ---- src/arc.rs - arc::Arc<T>::ptr_eq (line 175) stdout ----
    Test executable failed (exit code 1).
    
    stderr:
    
    ===========================351856==ERROR: LeakSanitizer: detected memory leaks
    
    Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x560da26ed8ad  (/tmp/rustdoctestPbs69K/rust_out+0x778ad)
    #1 0x560da270e6be  (/tmp/rustdoctestPbs69K/rust_out+0x986be)
    #2 0x560da270e9ea  (/tmp/rustdoctestPbs69K/rust_out+0x989ea)
    #3 0x560da270ef0a  (/tmp/rustdoctestPbs69K/rust_out+0x98f0a)
    #4 0x560da270d182  (/tmp/rustdoctestPbs69K/rust_out+0x97182)
    #5 0x560da270f4f2  (/tmp/rustdoctestPbs69K/rust_out+0x994f2)
    #6 0x560da270dc62  (/tmp/rustdoctestPbs69K/rust_out+0x97c62)
    #7 0x560da270d8c1  (/tmp/rustdoctestPbs69K/rust_out+0x978c1)
    
    // omitted the other message for Direct leak
    SUMMARY: AddressSanitizer: 32 byte(s) leaked in 2 allocation(s).

What I guess the problem is either, or both :(

1.  Wrong implementation for drop( )
I simply have used `ptr::drop_in_place` on the raw pointer(`*mut`) `self.ptr.as_ptr()`
2.  Wrong implementation for try_unwrap( )
I've used `ptr::read` to get inner data `T` from `this.ptr.as_ptr()`. Then I used `mem::forget` to deallocate `this` but not to drop `T` as the hint says. (This is what I understood so far)

I really can't get through from this point. Could I get some advice?
I'll delete this post if disclosing my solution this way is not allowed.

**Comment by tomtomjhj** [comment]
drop != deallocation. Please take a look at other issues with "homework - arc" label. And you don't need to use anything from `ptr` module (other than `NonNull` stuff).

**Comment by lyra95** [comment]
Thanks a lot. For those who are suffering from the same issue, [#142](https://github.com/kaist-cp/cs492-concur/issues/142) this helped a lot for me.
