### ISSUE TITLE
[Homework 4] Lock-coupling linked list (due: 2020-11-13 23:59:59+0900)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs492-concur#177]
**Implement a concurrent sorted singly linked list using fine-grained lock-coupling.**

This homework is like a combination of HW1-cache and HW2-linked_list. As in HW2, you will build a linked list data structure (but singly-linked and sorted) from the ground up, and as in HW1-cache, you will use locks in a fine-grained manner in order to increase the parallelism of the operations.

## Info
* Fill in the `todo!()`s in `list_set.rs`
* 45 lines of code to write
* To run tests with sanitizers, `source ./scripts/grade-util.sh` and run tests with `cargo_asan` or `cargo_tsan`.

## Grading (80 points)
```
./scripts/grade-4.sh
```
* +10 points if `cargo test [--release]` tests pass.
* +70 points if `cargo_asan [--release]` and `cargo_tsan [--release]` tests pass.

**Comment by tomtomjhj** [comment]
**Update** Added grading script and one more test case. https://github.com/kaist-cp/cs492-concur/commit/b004344d3d2cd4e1913a43e1bf9fa320f65e8878

**Comment by integerblue** [comment]
Hasn't the submission site been updated yet?

**Comment by Lee-Janggun** [comment]
I used 47. I'm not sure which part of your code is long but for my implementation all of the methods used at most 12 lines if that helps.

**Comment by integerblue** [comment]
@Lee-Janggun Thank you!
I didn't know that Cursor could be used in OrderedListSet::insert and remove. 
Using cursor made me reduce the lines of code to 38!
Thanks!

**Comment by jeehoonkang** [comment]
Now you can upload your solution: https://gg.kaist.ac.kr/assignment/23/
