### ISSUE TITLE
[Question] Homework3 loom test memory leak

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#178]
Hello, I have difficulty in debugging code for homework3. I passed the given cargo tests but keeps failing every loom test.
The test says
``` test correctness::try_unwrap_sync ... thread 'main' panicked at 'Internal state mutated during branch. This is usually due to a bug in the algorithm being tested writing in an invalid memory location.```
so I think it is related to `drop()`.
Pondering on the test cases, I figured out some schedule where invalid memory accessing might happen. For now, this is the best I can think of.
```drop_sync
Thread1                                      Thread2
arc1 = Arc::new                           (move)
arc2 = arc1.clone()
arc2.0.fetch_add(1, Relaxed)
                                                   arc1.0.fetch_add(1, Relaxed)
```
I thought _Thread2_ might try to write on the invalid as the `arc1` and `arc2` will be dropped if the _Thread1_ ends. However, in this case, I can't think of any way to prevent this because my drop function can't check the data access. Also is thread spawning can be reordered with other operations using the elements which the thread takes the ownership of?
If I got it right, the loom test tests every possible reorderings of the test code, but I can hardly find such reorderings as each line seem to be related.
Can you point out what I got wrong? Thank you in advance.

**Comment by tomtomjhj** [comment]
> The test says test correctness::try_unwrap_sync ... thread 'main' panicked at 'Internal state mutated during branch. This is usually due to a bug in the algorithm being tested writing in an invalid memory location.

The error message is from `try_unwrap_sync` test but your example schedule seems to be based on `clone_drop_atomic` test. Can you first double-check what test is failing? This command will run the tests one-by-one so that the error messages don't mess up each other.
```
cargo test --features check-loom --test arc -- --nocapture --test-threads 1
```

**Comment by haeeun-14** [comment]
All of the tests, including drop_sync, from loom test got the same error, so I just pasted a random one for an example... Sorry for confusing you.

**Comment by haeeun-14** [comment]
I think I solved it. Sorry for the confusion.
