### ISSUE TITLE
[Question] park and unpark in mcsparkinglock

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#179]
Can I think park and unpark as context switching? 
And is there any reason it is named as park?

**Comment by jeehoonkang** [comment]
- Yes, "park" means switching out and "unpark" means switching in again.
- Regarding the names: honestly, I don't know... The earliest reference I could find is Java's (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/LockSupport.html).

**Comment by jessi68** [comment]
Thank you for your reply! I understand with relating to car's park.
