### ISSUE TITLE
[Question] move occurs when mem::forget 

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#180]
In homework#3, to implement try_unwrap function, I think `mem::forget` is used for arc_inner because `try_unwrap` function gets ownership by calling `Box::from_raw` but not drop it. 
To forget something, move occurs. But in `try_unwrap` function should return arc_inner data. How do I fix it?

**Comment by wltn0029** [comment]
I just solved this problem by referring to the example on rust's doc : https://doc.rust-lang.org/std/mem/fn.forget.html#relationship-with-manuallydrop

**Comment by tomtomjhj** [comment]
note: `forget` is just a wrapper of `ManuallyDrop::new` that discards the created `ManuallyDrop`. https://doc.rust-lang.org/src/core/mem/mod.rs.html#147-149
