### ISSUE TITLE
[Question] HW#4 Find function

### ISSUE THREAD

**Issue by us0310306** [kaist-cp/cs492-concur#187]
In homework #4, we should implement Find function.
What should we do when find fail?
In Cursor, we should move the cursor.
In OrderedListSet, we should return `(bool, Cursor<T>)`
What is the result when we fail to find?

**Comment by tomtomjhj** [comment]
What kind of failure?

**Comment by us0310306** [comment]
When there's no key in OrderedListSet.
Try to find(&self, key: &T) and there's no key in OrderedListSet.
Is it impossible?

**Comment by zzz845zz** [comment]
I implemented `OrderedListSet::find` using the result of Cursor's `find` and its Cursor instance.

In my implementation,  if there is no key in the OrderedListSet, the Cursor returns false and the Cursor's inner reference points to the null pointer.

**Comment by tomtomjhj** [comment]
`Cursor::find` should move the cursor to the position to which the key can be inserted.

**Comment by us0310306** [comment]
Thanks!
