### ISSUE TITLE
[Question] What is the reason using n=e.new in lock-free stack?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#188]
```
        loop {
            let head = self.head.load(Ordering::Relaxed, &guard);
            n.next.store(head, Ordering::Relaxed);

            match self
                .head
                .compare_and_set(head, n, Ordering::Release, &guard)
            {
                Ok(_) => break,
                Err(e) => n = e.new,
            }
        }
```
In this code, push() of the lock-free stack, compare_and_set returns Result, and the error contains to fields, which are current and new, and new is what we previously attempted to store in the atomic pointer. Then why should we change n as e.new since e.new is the same as n? Shouldn't we just proceed to the next loop without doing anything?

**Comment by tomtomjhj** [comment]
`n` is moved into `compare_and_set` and `n` is of type `Owned<Node<T>>` (≈ `Box<Node<T>>`). This means that `n` can't be used after `compare_and_set`. If `compare_and_set` fails, it returns the `Owned<Node<T>>` wrapped inside `CompareAndSetError`. So `n = e.new` restores `n` for later uses. 

Note that `compare_and_set` in `pop` uses `next: Shared<Node<T>>`, which is not associated with the ownership of node and   implements `Copy`.
