### ISSUE TITLE
How about Using Workspace?

### ISSUE THREAD

**Issue by maxtnuk** [kaist-cp/cs492-concur#19]
I see the code and there are two library(art, lock) in same project
I think it would be better by using `workspace` in `Cargo.toml`
like this
``` toml
[workspace]
members = [
    "art",
    "lock",
]
```

**Comment by jeehoonkang** [comment]
Hmm, that's an interesting proposal.  I personally am not eager to make such a change, but am happy to accept an PR on that.  Thank you pointing out this!

**Comment by jeehoonkang** [comment]
Closing it for inactivity, but feel free to reopen this!  Thank you so much for your interest in improving the course material.
