### ISSUE TITLE
Reading list for the upcoming homework 5

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#194]
- Homework 5 will be announced around the 10th of November.  It will be about implementing lock-free, split-ordered linked list.

- For homework 5, you're strongly encouraged to read (at least either of) the following articles:
    + [A paper](https://dl.acm.org/doi/abs/10.1145/1147954.1147958): it's original.
    + Chapter 13.3 of [a book](https://www.amazon.com/Art-Multiprocessor-Programming-Revised-Reprint/dp/0123973376): it's more readable.

- You can think of those articles as "the specification" of homework. The skeleton will be provided.

**Comment by integerblue** [comment]
[pdf](https://dl.acm.org/doi/book/10.5555/2385452) of the book could be downloaded free in KAIST

**Comment by jeehoonkang** [comment]
Superseded by #208
