### ISSUE TITLE
[Question] Returning reference of value created in next

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#195]
In the `next` function for `Iterator`, the return value is `Option<&'T>`. What I was confused about is that as our node's `data` has type `T`, in order to get a reference we would need to create it ourselves in the function, hence need to take ownership of `data` in `next` function. However this seems problematic as then we cannot return the reference to `data` due to ownership problem. Normally we can fix this by wrapping in `Box`, but that will not work in this case. What should we do?

This is probably me just being stupid and not using some good function, but I was unable to find a solution.

**Comment by tomtomjhj** [comment]
If you have `node: &Node<T>`, then you can the reference of the `data` with `&node.data`.

**Comment by Lee-Janggun** [comment]
Ah that indeed worked. Thank you for the answer!
