### ISSUE TITLE
[Question] HW4 next()

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#197]
In `next()` function, I think I have to acquire a lock to change `self` to next node. Then If we make mutiple Iters, I don't have any idea how to avoid the block. Do I have to use `RWlock` instead of `Mutex`?   

Actually in test_case `fn parallel_iter_end()`,  I don't have any idea except for using `read()` to allow read the data in multiple threads......

**Comment by tomtomjhj** [comment]
It' ok to block temporarily while iterating but it shouldn't block is iteration is done (as in `parallel_iter_end`). There is a simple way to prevent unnecessary blocking in `parallel_inter_end`. Hint: `Option` in the definition of `Iter`.

**Comment by Jaegoomon** [comment]
Thank you~ it helps me a lot

**Comment by us0310306** [comment]
I also have same problem.
I'm sorry but is it able to explain in detail?
