### ISSUE TITLE
[Question] HW04 implement insert

### ISSUE THREAD

**Issue by us0310306** [kaist-cp/cs492-concur#199]
I tried several ways to implement insert function.
Using `ptr::swap` or `ptr::replace` made error.
Also, I tried like this *`self.head.lock().unwrap() = Node::new(key, ptr::null_mut());` 
when inserting first value, it didn't work, too.
Am I wrong or should I use another way to change the value in OrderedListSet?
Can you give me some advice?

**Comment by tomtomjhj** [comment]
> it didn't work,

What didn't work?

**Comment by us0310306** [comment]
I wanted to say that `*self.head.lock().unwrap() = Node::new(key, ptr::null_mut());` this didn't work.

**Comment by tomtomjhj** [comment]
I mean the aspect of failure. Type error? Runtime error? Assert failure?

**Comment by us0310306** [comment]
When i use swap or replace,` invalid memory reference` occurs.
When I use `*self.head.lock().unwrap() = Node::new(key, ptr::null_mut());`, 
it does not make error but value is not inserted when I check by contains or remove.

**Comment by tomtomjhj** [comment]
You should use `find` method in `insert`.

**Comment by us0310306** [comment]
Sure, I also used find function when insert and get value like `(a, b)`
and tried to change by `*b.0 = Node::new(key, ptr::null_mut));`
This is same to above code when inserting first value that find will return the head.
And  I also tried like this.

**Comment by tomtomjhj** [comment]
hint: Is `ptr::null_mut()` correct?

**Comment by us0310306** [comment]
```
OrderedListSet -> head : null
insert 1
OrderedListset -> head : node(1) -> null
insert 2
OrderedListset -> head : node(1) -> node(2) -> null
```
Is this structure wrong?
I thought we should make the node that next is null 
and change the OrderedListSet's last null pointer to made node.

**Comment by tomtomjhj** [comment]
The list is supposed to be sorted by the element.

**Comment by us0310306** [comment]
I'll fix to take care about sorting. 
But in first inserting value, there will be no value in OrderedListSet, 
so I think `*self.head.lock().unwrap() = Node::new(key, ptr::null_mut());`
this code should make 
```
OrderedListSet -> null
to
OrderedListSet -> Node(key) -> null
```
Is this wrong, too?
