### ISSUE TITLE
[gg.kaist.ac.kr] Problem with authentication

### ISSUE THREAD

**Issue by temirrr** [kaist-cp/cs492-concur#2]
Dear Professor,

I was not able to log into _gg.kaist.ac.kr_. I don't know how you manage it and whether you manually manage each student's access to the website, but could you please check it and tell me what could we do to solve the problem?

Have other students successfully entered the website?

**Comment by kimjungwow** [comment]
I can't either, when I tried with KAIST student ID for both ID and password.

**Comment by jeehoonkang** [comment]
Send me an email, please. (with your name & student id)
