### ISSUE TITLE
[Question] HW4 drop(), asan

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#200]
I have two questions about `drop()` and `cargo_asan`

1. When I drop `OrderedListSet`, Do I have to drop all the element in the set, similarly in `linked _list.rs`(popping all the element in list)? If so, is there only way to drop mutex is acquiring & drop? Well, I want to use `inner.destroy()` but it didn't work because `inner` is private. 

2. In cargo_asan test case, sanitizer found some memory leak in my code. Do memory leak is related to `drop()`? I mean in `insert` or `remove`, do I have to drop the node that I didn' use anymore manually?

Is there anyone who knows or has ideas about those problems, please comments..... it will help me a lot.. thank you :> !!

**Comment by tomtomjhj** [comment]
1. `drop` should `drop` all elements in the set. You can use [`Mutex::get_mut`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.get_mut) and [`Mutex::into_inner`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.into_inner). 
2. It depends. Please take a closer look at the sanitizer output. It reports some useful info e.g. the source of the leaked memory block in your code.

**Comment by Lee-Janggun** [comment]
How would we use into_inner? I assume the usage is something like `self.head.into_inner`, but self is a mutable reference so we cannot move it.

**Comment by tomtomjhj** [comment]
That's why I also mentioned `get_mut`.

**Comment by Lee-Janggun** [comment]
Ah yes so we use both only in appropriate positions. Thanks for the help!

**Comment by Jaegoomon** [comment]
Thank you, I think the problem was drop(). Now it works.
