### ISSUE TITLE
[Question] Homework4, Cursor for head pointer

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#202]
The comment about the Cursor struct says that : 
"reference to the `next` field of previous node which points to the current node"
Also I read other questions, and found that it should be used for `insert()` and `remove()`. Thus  in the case the key exist, the Cursor points to the previous node of the key node, and if the key does not exist, it should point to the previous node of the node which is going to be inserted.
 However, in the case the `OrderedListSet` contains only one node and it has the key1 and the key2 which is to be inserted should be the previous node to the key1 node, the Cursor's pointer seems to be useless. I have not heard that lock coupled linked list contains dummy node at the head, but is it allowed to use one? Can you point out if I got something wrong?

**Comment by tomtomjhj** [comment]
In that case  "next field of the previous node" is the head field of the list.

**Comment by Jaegoomon** [comment]
```
		+-----+         +-----+      +-----+
		|  A  |   ->    |  B  |  ->  |  C  |
		+-----+         +-----+      +-----+
		                                         
			         Cursor                
```
For example in `remove()`, when you find the node whose data is key. It means `Cursor` has mutextguard which can access the node whose data is key. Then, the main point is mutexguard is the result of lock acquiring of previous node. 

look at the picture if you find the node B, then Cursor is Mutexguard of B, it means you have a lock on node A. So if you access the mutexguard and you change the node than it means you change the next of node A. So you alread have a lock on previous node. 

It's just my case of using Cursor... I hope it will help you....

**Comment by haeeun-14** [comment]
Ah, gaining mutex guard is the same as having the guard for the next node of the previous node. I was missing that. Thank you, it helped a lot!
