### ISSUE TITLE
[Question] About homerwork 4, how to initialize MutexGuard<'l, *mut Node<T>>

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#203]
I want to initialize MutexGuard<'l, *mut Node<T>> as null pointer.

So I used (Mutex::lock(&Mutex::new(ptr::null_mut())).unwrap(), 

but I had an error "cannot infer type for type parameter `T` declared on the function"
how can I handle this?

**Comment by Lee-Janggun** [comment]
If your definition is something like 
`let guard = Mutex::new(...)`

just directly annotate the type with something like

`let guard: MutexGuard<T> = Mutex::new(...)`

**Comment by tomtomjhj** [comment]
Try `null_mut::<Node<T>>()`

**Comment by jessi68** [comment]
Thank you for replies. I will close my question.
