### ISSUE TITLE
[Question] [HW4] A timeout fail for testing `parallel_iter_end`

### ISSUE THREAD

**Issue by lyra95** [kaist-cp/cs492-concur#206]
I've passed all other test functions but `fn parallel_iter_end()`. I've got a timeout fail for  `fn parallel_iter_end()`.

Possible causes I suspects are:
1. `while` loops I put in `drop` and `Cusor::find` functions
- I don't think this is the problem, because all other tests passed anyway without falling into infinite loops. (it took time a lot though...)
2. Somehow threads are blocked, trying to acquire a lock that is already being held. 
- If this is the case, I really do not know how to fix it... Should I use something like `Ordering::Acquire`?

**Comment by yominx** [comment]
#197 may help you. "parallel_iter_**end()**" -> when iter reaches to the end, it hold last node's next mutex(It might hold null ptr): It's very unexpected behavior

**Comment by lyra95** [comment]
Thanks for the comment. I think I already covered the case `self` = `Some(mutex(null_ptr))` to return `None`. I'm not sure if this is what you mean, but I'll try way around. Thanks

**Comment by lyra95** [comment]
Now I got it and fixed the issue.
