### ISSUE TITLE
[Question] HW #4 insert failed

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#216]
test are not passed and I found that insertion didn't work well.
I think I successfully update linked_list using cursor which has mutexguard of previous node's next field as below.
`*cursor.0 = new_node`
But whenever I check linked_list's state after inserting a node, the list does not change at all. :( 
I cannot figure out my mistake..

**Comment by spacebarley** [comment]
I guess you need to check the other part such as does node made correctly or cursor located correctly.
I had no problem with the code that you mentioned.

**Comment by wltn0029** [comment]
Cursor is located at the node whose key is greater or equal to given argument key, so I think it is on the right position...
I just wonder how to check stdout of test. I want to debug my code with stdout.

**Comment by HelloWorld017** [comment]
You can debug with stdout using commands like this:
`$ cargo test --test list_set -- --nocapture`

**Comment by wltn0029** [comment]
I found that even cursor is on the right position and I insert node with `Node::new(key, next_node)`, link_list does not update at all:(
```
 let next_node = unsafe{*cursor.0};
 *cursor.0 = Node::new(key, next_node);
 drop(cursor);
 let head = self.head.lock().unwrap();
 if head.is_null() {
       return Err(());
 }
```
If I run above code, head has still null pointer. Why is that happened? 
I'm stuck in this issue, so it will be appreciated to suggest any idea about it..

**Comment by TonyWild** [comment]
You are changing just the cursor's pointing location, not the real linked list

**Comment by wltn0029** [comment]
But I think cursor's pointing location is real linked list.. Am I wrong?

**Comment by TonyWild** [comment]
I treated cursor as a "navigator" of linked list (i.e. cursor is independent with actual list). Even though cursor is now pointing to the new node, head pointer is still not changed. You have to actually change the head of the list or the next field of the previous node.

**Comment by tomtomjhj** [comment]
MutexGuard holds the reference to the source Mutex. So the cursor is not independent of the list.

**Comment by haeeun-14** [comment]
@TonyWild 
I am using similar method, but didn't drop the cursor (in my case, I verified the list changed with the insert function, but after several operations segmentation error occurs). I thought e.g. when the lock guard is from the head pointer, the change of the content in the lock guard also changes actual content of the head in the lock guard. Where did I get wrong...??

**Comment by TonyWild** [comment]
@haeeun-14 
In fact, I thought the opposite (only changing the content of mutexguard in cursor does not change the content of linked list). But I cannot say more than that because I didn't check whether that implementation works (when the lock guard is from the head pointer, the change of the content in the lock guard also changes actual content of the head in the lock guard), and don't know the detailed implementation of yours.. sorry :(

**Comment by wltn0029** [comment]
I think cursor retains the real linked list's head because it obtains mutexguard of head when it is created. 
Below code works fine.
```
let next_node = unsafe{*cursor.0};
*cursor.0 = Node::new(key, next_node);
drop(cursor);
let head = self.head.lock().unwrap();
if head.is_null() {
   return Err(());
}
```
Actually the wrong implementation was cmp matching. I should use it with Ordering module.
