### ISSUE TITLE
[Question] [HW4] About Mutexguard inside Iter

### ISSUE THREAD

**Issue by nv-quan** [kaist-cp/cs492-concur#218]
Iter is a struct that hold a MutexGuard to a node. When iter.next() is called, the iter must hold the next MutexGuard in the list. However it needs to return the reference of the previous Node (which is already unlocked by the time it returns, as the previous MutexGuard is dropped). Am I understanding it wrong? If not then how is it possible?

**Comment by HelloWorld017** [comment]
Actually, this issue was my main reason of tsan failure, and I have dealt it by adding a new field in Iterator.
But I think this solution is a kind of *hacky* solution and I don't know whether it is accepted or not.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/205

**Comment by hestati63** [comment]
The reason that you can use the `MutexGuard` of the next node even if the previous node of the `MutexGuard` is dropped is that the `Mutex` protects the raw pointer.
The raw pointer does not hold any lifetime. That is, you can get the reference of any lifetime from the raw pointer.
For example:
``` rust
// Let's say p is the reference of Node with lifetime 'a.
let p: &'a Node = ...;
// Lock the next.
let guard: MutexGuard<'a, *mut Node> = p.next.lock();
// Get the protected pointer.
let ptr: &'a *mut Node = guard.next;
// Next's lifetime is not 'a but 'b, where 'b can outlive the 'a.
let next: &'b Node = unsafe { &**ptr };
```

**Comment by nv-quan** [comment]
> The reason that you can use the `MutexGuard` of the next node even if the previous node of the `MutexGuard` is dropped is that the `Mutex` protects the raw pointer.
> The raw pointer does not hold any lifetime. That is, you can get the reference of any lifetime from the raw pointer.
> For example:
> 
> ```rust
> // Let's say p is the reference of Node with lifetime 'a.
> let p: &'a Node = ...;
> // Lock the next.
> let guard: MutexGuard<'a, *mut Node> = p.next.lock();
> // Get the protected pointer.
> let ptr: &'a *mut Node = guard.next;
> // Next's lifetime is not 'a but 'b, where 'b can outlive the 'a.
> let next: &'b Node = unsafe { &**ptr };
> ```

Thank you for your reply. However think the problem is when the MutexGuard of the previous node is dropped, other thread can access into that node and make the data reference unsafe.

**Comment by nv-quan** [comment]
> #205

Thank you. I've read that issue I'm still very confused because the current node's MutexGuard is the only field in the Iter. The only solution I can think of is to create another field as HelloWorld017 did so that I can keep the previous MutexGuard and not free it too early. I would be really appreciate if you can give me some hint on this problem :(

**Comment by tomtomjhj** [comment]
The MutexGuard in Iter protects the node whose reference is returned by `Iter::next`. So the entity protected by `Cursor` and `Iter` are different.

**Comment by Jaechan-So** [comment]
I tried to holding two `MutexGuard`s in the `next()` function and it works. One holds the current node's pointer, and another holds the next node's pointer. So when the control flow escapes out of function, then now the `Iter` holds the next node's pointer, and also it lost the ownership of previous current node's pointer. Maybe reviewing the comment of skeleton will be helpful!
https://github.com/kaist-cp/cs492-concur/blob/b004344d3d2cd4e1913a43e1bf9fa320f65e8878/homework/src/list_set.rs#L24

**Comment by HelloWorld017** [comment]
I'm quite confused as I had a tsan failure when I have used @Jaechan-So 's method.

I did the same thing (in next, hold current and next / after return, hold next) and it seems working well, but in tsan `iter_consistent`, it gave me a failure.

**Comment by Jaechan-So** [comment]
@HelloWorld017 Just to be sure, if you used both `contains()`(that also utilize `find()`) and `find()` in your `insert()` and `remove()`, then you might get the failure since it tries to hold same Mutex twice. If it is not the case, then never mind😥

**Comment by Lee-Janggun** [comment]
> @HelloWorld017 Just to be sure, if you used both `contains()`(that also utilize `find()`) and `find()` in your `insert()` and `remove()`, then you might get the failure since it tries to hold same `Mutex` twice. If it is not the case, then never mind😥

I had this problem originally, and the test just fails at normal `cargo`. Holding the same `Mutex` twice just breaks the code.

**Comment by nv-quan** [comment]
> The MutexGuard in Iter protects the node whose reference is returned by `Iter::next`. So the entity protected by `Cursor` and `Iter` are different.
So here is what I understand from your comment:
The linked list:
A -> B -> Null
When first created, Iter holds MutexGuard of Node A.
When call iter.next(), it returns the reference to Node A's data, and releases the A's Guard while holds the new Guard for Node B

My question is: Node A is now free, what if another thread insert a new node, for example
A -> C -> B -> Null
and then attempt to remove A:
C -> B -> Null
Now the A's reference is dangling. These operations are allowed because A is not locked, so C can be inserted. And then when A and C are not locked, A can be removed. So am I understanding wrong?

**Comment by nv-quan** [comment]
Indeed I tried that approach anyway and getting this error (which I can't trace back to the problem)
`running 1 test                                                                                                                                                               
test iter_consistent ... FATAL: ThreadSanitizer CHECK failed: /checkout/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector.h:67 "((n_all_locks_)) 
< (((sizeof(all_locks_with_contexts_)/sizeof((all_locks_with_contexts_)[0]))))" (0x40, 0x40)                                                                                 
    #0 __tsan::TsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_rtl_report.c
pp:47 (list_set-32ef8a8acdebc947+0x72b15)                                                                                                                                    
    #1 __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitize
r_termination.cpp:78 (list_set-32ef8a8acdebc947+0x8661f)                                                                                                                     
    #2 __sanitizer::DeadlockDetectorTLS<__sanitizer::TwoLevelBitVector<1ul, __sanitizer::BasicBitVector<unsigned long> > >::addLock(unsigned long, unsigned long, unsigned in
t) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector.h:67 (list_set-32ef8a8acdebc947+0x7d1ec)                                        
    #3 __sanitizer::DD::MutexAfterLock(__sanitizer::DDCallback*, __sanitizer::DDMutex*, bool, bool) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_d
eadlock_detector.h:216 (list_set-32ef8a8acdebc947+0x7c75e)                                                                                                                   
    #4 MutexAfterLock /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector1.cpp:169 (list_set-32ef8a8acdebc947+0x7c75e)
    #5 __tsan::MutexPostLock(__tsan::ThreadState*, unsigned long, unsigned long, unsigned int, int) /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_rtl_mutex.cpp:199 (list_set-32ef8a8acdebc947+0x713d8)
    #6 pthread_mutex_lock /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4202 (list_set-32ef8a8acdebc947+0x3c458)
    #7 std::sync::mutex::Mutex<T>::lock :? (list_set-32ef8a8acdebc947+0xadd8e)
    #8 <cs492_concur_homework::list_set::OrderedListSet<T> as core::ops::drop::Drop>::drop :? (list_set-32ef8a8acdebc947+0xa9b14)
    #9 core::ops::function::FnOnce::call_once list_set.cknkz4w7-cgu.2:? (list_set-32ef8a8acdebc947+0x9a98a)
    #10 core::ops::function::FnOnce::call_once /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/core/src/ops/function.rs:227 (list_set-32ef8a8acdebc947+0xd7722)
    #11 test::__rust_begin_short_backtrace /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:517 (list_set-32ef8a8acdebc947+0xd7722)
    #12 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/alloc/src/boxed.rs:1307 (list_set-32ef8a8acdebc947+0xd5bd9)
    #13 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panic.rs:322 (list_set-32ef8a8acdebc947+0xd5bd9)
    #14 std::panicking::try::do_call /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panicking.rs:381 (list_set-32ef8a8acdebc947+0xd5bd9)
    #15 std::panicking::try /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panicking.rs:345 (list_set-32ef8a8acdebc947+0xd5bd9)
    #16 std::panic::catch_unwind /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panic.rs:396 (list_set-32ef8a8acdebc947+0xd5bd9)
    #17 test::run_test_in_process /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:544 (list_set-32ef8a8acdebc947+0xd5bd9)
    #18 test::run_test::run_test_inner::{{closure}} /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:450 (list_set-32ef8a8acdebc947+0xd5bd9)
    #19 test::run_test::run_test_inner /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:475 (list_set-32ef8a8acdebc947+0xd523c)
    #20 test::run_test /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:505 (list_set-32ef8a8acdebc947+0xd33ad)
    #21 test::run_tests /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:284 (list_set-32ef8a8acdebc947+0xc1aaf)
    #22 test::console::run_tests_console /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/console.rs:280 (list_set-32ef8a8acdebc947+0xc1aaf)
    #22 test::console::run_tests_console /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/console.rs:280 (list_set-32ef8a8acdebc947+0xc1aaf)
    #23 test::test_main /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:122 (list_set-32ef8a8acdebc947+0xcf4e6)
    #24 test::test_main_static /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/test/src/lib.rs:141 (list_set-32ef8a8acdebc947+0xd0898)
    #25 list_set::main list_set.cknkz4w7-cgu.2:? (list_set-32ef8a8acdebc947+0x9c71c)
    #26 std::sys_common::backtrace::__rust_begin_short_backtrace :? (list_set-32ef8a8acdebc947+0x979d3)
    #27 _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h5fae76009089976eE.llvm.7419818881258131433 ??:? (list_set-32ef8a8acdebc947+0xadbed)
    #28 core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/core/src/ops/function.rs:
259 (list_set-32ef8a8acdebc947+0x111386)
    #29 std::panicking::try::do_call /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/std/src/panicking.rs:381 (list_set-32ef8a8acdebc947+0x111386)
    #30 std::panicking::try /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/std/src/panicking.rs:345 (list_set-32ef8a8acdebc947+0x111386)
    #31 std::panic::catch_unwind /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/std/src/panic.rs:396 (list_set-32ef8a8acdebc947+0x111386)
    #32 std::rt::lang_start_internal /rustc/9722952f0bed5815cb22cb4878be09fb39f92804//library/std/src/rt.rs:51 (list_set-32ef8a8acdebc947+0x111386)
    #33 main ??:? (list_set-32ef8a8acdebc947+0x9c788)
    #34 __libc_start_main ??:? (libc.so.6+0x28151)
    #35 _start ??:? (list_set-32ef8a8acdebc947+0x191ed)

error: test failed, to rerun pass '--test list_set'

`

**Comment by tomtomjhj** [comment]
> When first created, Iter holds MutexGuard of Node A.

No, it holds the mutexguard from the head (see `OrderedListSet::iter`).
When you first call `Iter::next`, uses jumps to the first node A, lock its mutex, and return the ref to the data of A.

**Comment by wltn0029** [comment]
@tomtomjhj But is head is first node A? 
I think to solve this iter should have two mutexguard, one for node whose data is returned and the other for next node.

**Comment by HelloWorld017** [comment]
Assuming the list is
```
A -A.next-> B -B.next-> C -C.next-> null
^
head
```

If I call the iter() function, it gaves me the Iterator with lockguard of the `head`.

Then if we call the next() and if I dereference it and lock next of it, only the lock of `A.next` remains and  the A, which are subject to be returned, is not protected by any Mutex.

And if I return B, with lockguard of `A.next` is written to self, the problem is resolved but the first node is omitted.

@tomtomjhj So I think that we can't "jump to first node A and lock A", as A is already locked in iter() and to advance the iterator, we should lock `A.next` but then we can't protect A.

**Comment by tomtomjhj** [comment]
I mean the `head` field of `OrderedListSet`

```
           +-- reference returned by Iter::next
           |
           v
         +----+   +----+   +----+
         |data|   |data|   |data|
+----+   +----+   +----+   +----+
|head|-->|next|-->|next|-->|next|
+----+   +----+   +----+   +----+
           ^
           |
         +--------+
         |cursor.0|
         +--------+
```

**Comment by Jaechan-So** [comment]
`
+----+
|head|
+----+
`

**Comment by Jaechan-So** [comment]
1. After `iter()`
```
          +----+    +----+
          |data|    |data|
+----+----+----+----+----+
|head|--->|next|--->|next|
+----+----+----+----+----+
       ^
       |
   Iter holds
```
2. Inside the `next()` function
```
          +----+    +----+
          |data|    |data|
+----+----+----+----+----+
|head|--->|next|--->|next|
+----+----+----+----+----+
       ^         ^
       |         |
       |         +-- Iter holds
Temporarily holds
   this guard
```
3. After the `next()` function
```
           +-- Reference returned
            |
            v
          +----+    +----+
          |data|    |data|
+----+----+----+----+----+
|head|--->|next|--->|next|
+----+----+----+----+----+
                 ^
                 |
                 +-- Iter holds
```
This is scenarios that I expected. Here each arrows (`--->`) can be regarded as a `MutexGuard` from the lefthand `Mutex`.

**Comment by nv-quan** [comment]
I think we all have the same understanding but it's just different in the way we describe it. Also now I realize that this does not cause dangling reference because once the Iter is holding the a node's Mutex (its next field), there is no way to delete that node. It means that my tsan test is failing because of different reason :(

**Comment by tomtomjhj** [comment]
@nv-quan try running the grader on homework server

**Comment by nv-quan** [comment]
> @nv-quan try running the grader on homework server

It failed the same test and has the same output as above.
`cargo_tsan test --test list_set iter_consistent`
```
running 1 test                                                                                                                                                               
test iter_consistent ... FATAL: ThreadSanitizer CHECK failed: /checkout/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector.h:67 "((n_all_locks_)) 
< (((sizeof(all_locks_with_contexts_)/sizeof((all_locks_with_contexts_)[0]))))" (0x40, 0x40)                                                                                 
    #0 __tsan::TsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_rtl_report.c
pp:47:25 (list_set-95c0ef672b92a2e6+0x74a85)                                                                                                                                 
    #1 __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitize
r_termination.cpp:78:5 (list_set-95c0ef672b92a2e6+0x8858f)                                                                                                                   
    #2 __sanitizer::DeadlockDetectorTLS<__sanitizer::TwoLevelBitVector<1ul, __sanitizer::BasicBitVector<unsigned long> > >::addLock(unsigned long, unsigned long, unsigned in
t) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector.h:67:5 (list_set-95c0ef672b92a2e6+0x7f15c)                                      
    #3 onLockAfter /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_deadlock_detector.h:216:11 (list_set-95c0ef672b92a2e6+0x7e6ce)                    
    #4 __sanitizer::DD::MutexAfterLock(__sanitizer::DDCallback*, __sanitizer::DDMutex*, bool, bool) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_d
eadlock_detector1.cpp:169:6 (list_set-95c0ef672b92a2e6+0x7e6ce)                                                                                                              
    #5 __tsan::MutexPostLock(__tsan::ThreadState*, unsigned long, unsigned long, unsigned int, int) /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_rtl_mutex.cpp:
199:14 (list_set-95c0ef672b92a2e6+0x73348)                                                                                                                                   
    #6 pthread_mutex_lock /home/s20180748/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.2/src/dfa.rs:876:18 (list_set-95c0ef672b92a2e6+0x3e458)                  
    #7 std::sys::unix::mutex::Mutex::lock::h58ee37d15953c652 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/sys/unix/mutex.rs:63:17 (list_set-95c0ef672b92a2
e6+0x1000cf)                                                                                                                                                                 
    #8 std::sys_common::mutex::MovableMutex::raw_lock::hcebc82b7c0afdeba /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/sys_common/mutex.rs:76:18 (list_set-
95c0ef672b92a2e6+0x103cd4)                                                                                                                                                   
    #9 std::sync::mutex::Mutex$LT$T$GT$::lock::h95594bac0ff096d1 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/sync/mutex.rs:263:13 (list_set-95c0ef672b92a
2e6+0xef444)                                                                                                                                                                 
    #10 _$LT$cs492_concur_homework..list_set..OrderedListSet$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::hdd548b3d0f56f77d /home/s20180748/cs492-concur/homework/src
/list_set.rs:144:29 (list_set-95c0ef672b92a2e6+0xbbfb2)                                                                                                                      
    #11 core::ptr::drop_in_place::h5fccb8ec5999bfae /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/core/src/ptr/mod.rs:175:1 (list_set-95c0ef672b92a2e6+0xb6677)    
    #12 list_set::iter_consistent::h0dcdcfca330d3503 /home/s20180748/cs492-concur/homework/tests/list_set.rs:314:1 (list_set-95c0ef672b92a2e6+0x935c6)                       
    #13 list_set::iter_consistent::_$u7b$$u7b$closure$u7d$$u7d$::h7e96a1fe17cb57af /home/s20180748/cs492-concur/homework/tests/list_set.rs:272:1 (list_set-95c0ef672b92a2e6+0
xea8e4)                                                                                                                                                                      
    #14 core::ops::function::FnOnce::call_once::h536a9007fa7c3807 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/core/src/ops/function.rs:227:5 (list_set-95c0ef672b
92a2e6+0xb4287)                                                                                                                                                              
    #15 core::ops::function::FnOnce::call_once::h5a2d5be79dfbb3fa /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/core/src/ops/function.rs:227:5 (list_set-95c0ef672b
92a2e6+0x12f7b2)                                                                                                                                                             
    #16 test::__rust_begin_short_backtrace::hc37895a957a28819 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:517:5 (list_set-95c0ef672b92a2e6+0x12f7b2)
    #17 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h2e984eb76fd48d18 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/alloc/src/boxed.rs:1307:9 (list_set-95c0ef672b92a2e6+0x12dc69)
    #18 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h0f6b5d488d670cea /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panic.rs:322:9 (list_set-95c0ef672b92a2e6+0x12dc69)
    #19 std::panicking::try::do_call::hdb3aa512bebe10c5 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panicking.rs:381:40 (list_set-95c0ef672b92a2e6+0x12dc69)
    #20 std::panicking::try::h1f092055c90b1f8d /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panicking.rs:345:19 (list_set-95c0ef672b92a2e6+0x12dc69)
    #21 std::panic::catch_unwind::h8375af0e881b2e9d /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panic.rs:396:14 (list_set-95c0ef672b92a2e6+0x12dc69)
    #22 test::run_test_in_process::h9e242243958ffdec /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:544:18 (list_set-95c0ef672b92a2e6+0x12dc69)
    #23 test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h7f9bd315f38b7711 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:450:39 (list_set-95c0ef672b92a2e6+0x12dc69)
    #24 test::run_test::run_test_inner::h250cc1c65a9a7d86 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:475:13 (list_set-95c0ef672b92a2e6+0x12d2cc)
    #25 test::run_test::h2ec1ef6f4251cfb2 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:505:28 (list_set-95c0ef672b92a2e6+0x12b43d)
    #26 test::run_tests::h738b861a72b22584 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:284:13 (list_set-95c0ef672b92a2e6+0x119b3f)
    #27 test::console::run_tests_console::h9d42a09e5e49aa00 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/console.rs:280:5 (list_set-95c0ef672b92a2e6+0x11
9b3f)
    #28 test::test_main::hdc7a68723ef08ada /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:122:15 (list_set-95c0ef672b92a2e6+0x127576)
    #29 test::test_main_static::h6f0d2a07f121f844 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/test/src/lib.rs:141:5 (list_set-95c0ef672b92a2e6+0x128928)
    #30 list_set::main::h8ad9ea8de14f4fb0 /home/s20180748/cs492-concur/homework/tests/list_set.rs:1:1 (list_set-95c0ef672b92a2e6+0x93682)
    #31 core::ops::function::FnOnce::call_once::h231bcbd7bb014d82 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/core/src/ops/function.rs:227:5 (list_set-95c0ef672b
92a2e6+0xb41c1)
    #32 std::sys_common::backtrace::__rust_begin_short_backtrace::hbf3f828467446883 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/sys_common/backtrace.rs:1
25:18 (list_set-95c0ef672b92a2e6+0xff027)
    #33 std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hadddab5d1dd9774d /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/rt.rs:66:18 (list_set-95c0ef672b
92a2e6+0xd3194)
    #34 core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::h3f3ba5d1e0ce8d49 /rustc/9722952f0bed5815cb22cb4878b
e09fb39f92804/library/core/src/ops/function.rs:259:13 (list_set-95c0ef672b92a2e6+0x1f5836)
    #35 std::panicking::try::do_call::hd7a374fc87b951e7 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panicking.rs:381:40 (list_set-95c0ef672b92a2e6+0x1f58
36)
    #36 std::panicking::try::h068087b173f80a49 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panicking.rs:345:19 (list_set-95c0ef672b92a2e6+0x1f5836)
    #37 std::panic::catch_unwind::h1f8259807e825279 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/panic.rs:396:14 (list_set-95c0ef672b92a2e6+0x1f5836)
    #38 std::rt::lang_start_internal::h8ff82302dd620b52 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/rt.rs:51:25 (list_set-95c0ef672b92a2e6+0x1f5836)
    #39 std::rt::lang_start::hc13870b52e59a1f8 /rustc/9722952f0bed5815cb22cb4878be09fb39f92804/library/std/src/rt.rs:65:5 (list_set-95c0ef672b92a2e6+0xd312d)
    #40 main <null> (list_set-95c0ef672b92a2e6+0x936fa)
    #41 __libc_start_main <null> (libc.so.6+0x270b2)
    #42 _start /home/s20180748/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.2/src/dfa.rs:878:19 (list_set-95c0ef672b92a2e6+0x1b1fd)

error: test failed, to rerun pass '--test list_set'
```

**Comment by tomtomjhj** [comment]
The log says that in your drop implementation, you're locking something and that makes something go wrong. Maybe you're moving/deallocating/dropping the mutex before drop the mutexguard ([Attempting to destroy a locked mutex results in undefined behavior](https://linux.die.net/man/3/pthread_mutex_destroy)).

Suggestion: You don't need to lock the mutex in drop: https://github.com/kaist-cp/cs492-concur/issues/200#issuecomment-722949754

**Comment by nv-quan** [comment]
Thank you guys very much. I passed all the tests :D
