### ISSUE TITLE
[HW4] Error only caused by set.iter()

### ISSUE THREAD

**Issue by SangwooJung98** [kaist-cp/cs492-concur#220]
In the test case of smoke() in homework4, the test case is made with three insert, one remove, for loop with iter, and one remove.
My list_set can handle the insert and remove but it throws signal: 4, illegal instruction in the set.iter() part.
When I delete the for loop in smoke test case, it works well.
Also, my code can go through other test cases which are not using iter().
Should we change some parts in iter() too??
( by making next function, I checked that iter() is not using next function in the for loop )

**Comment by Lee-Janggun** [comment]
We need to fill out the `next` function in `Iter`. Check that you completed all the `todo!()`s.

**Comment by AnHaechan** [comment]
I think the problem is probably the `Iter::next` function.
You said that there's no next function in the for loop of smoke testcase, but it uses internally.
```
for i in set.iter() {
   // something
}
```
Because the return value of `set.iter`, `Iter<T>` implements `Iterator` traits, 
the `Iter as Iterator::next` function is internally used in the for loop.

**Comment by SangwooJung98** [comment]
> I think the problem is probably the `Iter as Iterator::next` function.
> You said that there's no `next` function in the for loop of smoke testcase, but it is used internally.
> 
> ```
> for i in set.iter() {
>    // something
> }
> ```
> 
> Because the return value of `set.iter`, `Iter<T>` , implements `Iterator` traits,
> the `Iter as Iterator::next` function is internally used during iterating the for loop.
> 
> _Conclusion_ : check `Iter::next` function.

oh, you're right. When I return None at next function, the for loop works well. 
thanks!
