### ISSUE TITLE
[Question] cursor find function 

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#222]
I wonder that in find function of cursor,  if element of node of cursor is 
bigger than key then we have to return previous node of cursor. How can we do it..?

**Comment by YujinGaya** [comment]
You don't need to think about that case. If you look at the function signatures, only `new`, `contains`, `insert`, `remove` and `iter` is public. So cursor `find` is only used by you to implement those public methods.

**Comment by jessi68** [comment]
Thank you for your reply.
