### ISSUE TITLE
HW5 return &Atomic<T>

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#225]
In `get()` of `growable_arrays.rs`, I have to return the type `Atomic<T>`. So I understand I have to use `from_usize` and `into_usize` to convert AtomicUsize. And to get `Atomic<T>` for return value. I write down the code like that

```rust
// t: usize
let s = Owned::<T>::from_usize(t);
return &Atomic::new(*s.deref());
```

But the rust blocks that kind of code, because the return value is reference of temporary value. Then how can I extract only `T` without making tempoary variable.

**Comment by tomtomjhj** [comment]
`Atomic::new` allocates a new memory block like `Box::new` and `Owned::new`. You should return the reference to an element of the Segment. If you have `segment: &Segment` and `index: usize`, 
```rust
unsafe { &*(segment.get_unchecked(index) as *const _ as *const Atomic<T>) }
//          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^^^^^^    ^^^^^^^^^^^^^^^^
//             &AtomicUsize   ->   *const AtomicUsize -> *const Atomic<T>
//       ^^                                                      |
//     &Atomic<T> <----------------------------------------------+
```

**Comment by Jaegoomon** [comment]
Oh, thank you. I absolutely don't know there is a kind of method like that. It helps me a lot!!
