### ISSUE TITLE
[Question] (HW5, question about storing the height of growable array tree)

### ISSUE THREAD

**Issue by Gabriel4256** [kaist-cp/cs492-concur#226]
While implementing the growable_array, I've got a question.

I read all the comments and related part of the [paper](https://dl.acm.org/doi/abs/10.1145/1147954.1147958).

In the comment of [growable_array.rs](https://github.com/kaist-cp/cs492-concur/blob/master/homework/src/hash_table/growable_array.rs)
> a segment contains the pointers to the elements **or other segments**. In other words, it is a tree that has segments as internal nodes.

And in this model, I think the height of the tree should be stored in `GrowableArray<T>` to get corresponding element efficiently.
Without it, It could be really inefficient in many cases.

For example, 
```text
                          +----+
                          |root|
                          +----+
                            | height: 2
                            v
                 +---+---+---+---+---+---+---+---+
                 |111|110|101|100|011|010|001|000|     --------  depth 1 segment
                 +---+---+---+---+---+---+---+---+
                   |                           |
                   v                           v
 +---+---+---+---+---+---+---+---+    +---+---+---+---+---+---+---+---+
 |111|110|101|100|011|010|001|000|    |111|110|101|100|011|010|001|000|      -----------  depth 2 segments
 +---+---+---+---+---+---+---+---+    +---+---+---+---+---+---+---+---+
                   |                                            |
                   v                                            v
                 +---+                                        +---+
                 |fox|                                        |cat|
                 +---+                                        +---+
```
In this segment tree, two elements (fox and cat) have been inserted, which have `0b111101` and `0b001` as their indices.

With this tree, assume that someone wants to get element at `0b001`. 
Without height information, it's hard to decide bits of index corresponding to current segment.

At the depth 1 segment, if the height of tree is 1, then it should pick `001`. 
But in this case, it should pick `000` because the height is 2.
In such cases, height information is essential, without it, it may choose wrong slot at each level.

But it seems like there's no variable for storing the height of the segment tree in `GrowableArray<T>` struct.
Or, Is there any other way to do indexing effectively without height information?

Please let me know if I'm missing something.
Thank you

**Comment by tomtomjhj** [comment]
You can tag the pointer to the segment with its height. For example,
```rust
let root = self.root.load(Ordering::Acquire, guard);
let root_height = root.tag();
...
let new_root_height = ...;
let new_root = ...;
self.root.compare_and_set(root, new_root.with_tag(new_root_height), Ordering::AcqRel, guard);
```
See also the tips section of hw5 announcement.

**Comment by Gabriel4256** [comment]
Problem solved. 
Thank you!
