### ISSUE TITLE
[Lecture] Invariant for Michael-Scott's queue 

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#227]
In the synchronization of Michael-Scott's queue,
the invariant is that
`a pointer value has release view ⊒
                 the messages of the pointed node’s value & next pointer`

How is relation ⊒ defined exactly?
I guess it means that the release view has the latest messages of pointed node's data and next pointer, but I'm not sure.

**Comment by Lee-Janggun** [comment]
I think the view is the same as those seen in promising semantics.

**Comment by AnHaechan** [comment]
A view is defined as : view ∈ [shared_var -> message]  
Then : view ⊒ "messages of the node.data & node.next"

I _guess_ ⊒ means that 
'for each message in messages of node.data,
  view(node.data).timestamp ⊒ message.timestamp'

But I asked this question because I was not sure.. can you explain it in more detail??
