### ISSUE TITLE
HW5 insert()

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#229]
In `split_ordered_list.rs` of `insert()`, I write down the code sequence below

step 1. find the node whose key value is same as argument key
step 2. if there is, `return Err(value)`
step 3. if there isn't, insert by using cursor method `insert()`

My question is in step 3, I think we can't guarantee that `insert()` succeed. So I want to make loop step1 ~ step3. But If I do so, because the `value` is moved in step 2, I can't do that. Isn't it wrong??

**Comment by tomtomjhj** [comment]
> But If I do so, because the value is moved in step 2

Step 3? When `insert` fails, it returns the node wrapped in `Err`. Related: https://github.com/kaist-cp/cs492-concur/issues/188#issuecomment-719955851

**Comment by Jaegoomon** [comment]
Ahh... I got it. Thank you. I was a fool :>
