### ISSUE TITLE
HW5 Owned drop

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#230]
```rust
L1: let node = Owned::new(Node::new(reverse, Some(value)));
L2: let failure = node.into_box().into_value();
L3: return Err(failure.unwrap());
```

In `insert()`, I used `into_box().into_value()` to get `V` in Owned memory. Well, in that code the ownership of `node` moved in L2 and the return value is `Err(failure.unwrap())`. 

And my question is __the codes above can make memory leak?__ Becuase of moved data I can't drop the node. I'm little confused that the Owned in heap memory can automatically drop in that cases .... Anyone who knows, give me some advice plz....

**Comment by tomtomjhj** [comment]
no
