### ISSUE TITLE
[Question] Question about relaxed behavior in the Treiber's Stack

### ISSUE THREAD

**Issue by nv-quan** [kaist-cp/cs492-concur#232]
There are 2 places that are the most confusing in the Treiber's Stack: L72 and L45

1. In this line https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/stack.rs#L45
the head is read with relaxed ordering. It was explained in the live session that it is relaxed because it doesn't deref the value. However I still find it not really clear. Here is my explanation about why it can be relaxed, but I don't know if it's correct or not.

It begin with something like this:
```
head:      |A|B|
n.next:
```
First it read the head. With the relaxed ordering, it can read the message A, which is not the latest value. Then n.next is written as A
```
head:     |A|B|
n.next:   |A|
```
Thread view: `head: A, n.next: A`
Then it goes to this line: https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/stack.rs#L50
which will use compare and set and would insert a new message right next to A in the head location. However this is not possible because B is taking that place. This then make the CAS fail and the loop continue until it read the latest value.

2. This line
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/stack.rs#L72
can be explained by the fact that the `next` message already have the release view at the first time it was pushed, so there is no need to release anymore.

Are these explanation correct?

**Comment by jeehoonkang** [comment]
The explanations for the two points seem correct to me.
