### ISSUE TITLE
[Question] Comparison of MPMC channel vs work-stealing deque (in terms of performance)

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/cs492-concur#233]
In the lecture, the professor introduced the work-stealing deque to balance workloads to different threads. However, to me, it seemed that when we want to use a work-stealing deque, we could use a MPMC channel instead of it for the similar purpose.

Then, what are the differences of a MPMC channel and a work-stealing deque? Do they have different performance, such as in terms of contention? By the way, for me, it seems that work-stealing deques will cause smaller contention, since each thread has its own deque and we pop/steal work at different ends of the deque.

**Comment by tomtomjhj** [comment]
[On the Benefits of Work Stealing in Shared-Memory Multiprocessors](https://pdfs.semanticscholar.org/6c8e/eed84703221ed4cdb7458d2f0159b9465bab.pdf)

**Comment by travis1829** [comment]
Thanks! Seems like it can obtain better performance in terms of contention, NUMA, and caches.
