### ISSUE TITLE
[Question] [HW5] About the return type of GrowableArray::get()

### ISSUE THREAD

**Issue by nv-quan** [kaist-cp/cs492-concur#234]
In the get method, it returns a reference to an Atomic<T>. However this method can be called when the array has value 0 at that index, which means a new memory of type T need to be allocated so that the Atomic<T> will be valid. Is there anyway to do that with Atomic<T>?

**Comment by tomtomjhj** [comment]
> a new memory of type T need to be allocated so that the Atomic will be valid.

`Atomic<T>` can be null.
