### ISSUE TITLE
specification of safety and lock coupled linked list

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#236]
I watched [lock coupled linked list] lecture again and I have some questions about that.

1. specification of safety
In the lecture, there are two specifications of CDS's safety : 1) sequentiality 2) synchronization
I understand what synchronization means but I'm quite confused about the meaning of sequentiality. 
I think sequentiality aims to guarantee the order of operation on concurrent data structure. In other words, even though the detail implementation can be interleaved by multiple threads, the final result of operation **should** be ordered. 

2. lock coupled linked list
It is very simple question, but I just clarify the implementation of lock coupling linked list. 
In the lecture, professor said that the head of linked list is immutable, but I think that is not true. As we've already implemented in the homework 4, the head of linked list is also protected by lock to access the first node of linked list. 

I wonder if I understand these two stuffs correctly.

**Comment by jeehoonkang** [comment]
1. I agree with your discussion on the specification of safety.
1. Oh, you're right on the immutability of the head.  To modify the pointer to the first node, you need to acquire the head's lock.  Thanks for clarification!
