### ISSUE TITLE
[Session 22, LIVE invited talk] Younghyo Kim (CEO, Strato IT), November, 26th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#237]
On the 26th of November, Younghyo Kim (CEO, Strato IT) will give us an invited talk.  Strato IT is building a concurrent programming language for managing distributed industrial robots and equipment in the factory environments.  The theory and practice of concurrency is a key ingredient of the company.  Younghyo Kim graduated from KAIST School of Computing in 2013.

It is **mandatory** to (virtually) attend this talk at [Google Hangout Meet](https://meet.google.com/zqd-qmgd-sga).  If you're interested in personally meeting with Younghyo, please [send me an email](mailto:jeehoon.kang@kaist.ac.kr).

**Comment by qawbecrdtey** [comment]
Does the talk start at 10:30 AM, KST?

**Comment by jeehoonkang** [comment]
Yes, 10:30am KST.

**Comment by jeehoonkang** [comment]
Sorry to mention this late: the invited talk will be given in Korean.  If you don't speak Korean, you're not required to attend this talk.

**Comment by jeehoonkang** [comment]
If you speak Korean, please answer this quiz by today: https://gg.kaist.ac.kr/quiz/32/

**Comment by integerblue** [comment]
@jeehoonkang I didn't realize to answer this quiz...... is this a mandatory thing to do?? I thought answering the student number and name in the session would be enough to check the attendance. I attended the session thoroughly but I think I missed your comment about the quiz...

**Comment by sklationd** [comment]
@integerblue Same here..

**Comment by jeehoonkang** [comment]
@integerblue @sklationd I'll also take into account the names and student ids you wrote in the Google Hangout Meet chat.
