### ISSUE TITLE
[Question] lock free linked list

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#238]
After I watched all lectures on lock free linked list, I'm still confused about why some code is ordered release-acquire.

In harris traversing algorithm, next node is aquired.
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L109
But if we just consider relaxed ordered instruction as just pre-occuring, is there any meaningful difference between acquired and relaxed in above code? Even though we can get latest information using acquired, it is **not lastest** from a certain point of view. 
What I mean is that, in some sense, 
```
thread A acquire lastest value of data_1
thread B some operation on data_1
thread A Still it thinks acquired value of data_1 is lastest, but in fact, it is not
```
Then what is benefit of using acquired ordering?

**Comment by nv-quan** [comment]
As far I understand, the data in the linked list is immutable so thread B can't change it. It can try to delete the node or add more nodes of course, but that wouldn't change the data_1.

**Comment by wltn0029** [comment]
yes, but the next field of node can be changed, and how about that case?
Even if the cursor get the lastest value at that time, the gotten value of next field which points to next node can be changed by other threads. And I think it can occur regardless of the ordering.

**Comment by tomtomjhj** [comment]
It ensures that the initialization (the first message) of the node happens before the access.

**Comment by wltn0029** [comment]
how to do so? 
And why it **ensures** the initialization through **Acquire** ordering? 
I think even if `acquire` ordering is used, the initialization of the node is not ensured because it depends on when the instruction is executed. If the next field is accessed before the initialization of the node, thread finish the loop and it is not related with the ordering.

**Comment by tomtomjhj** [comment]
* Why: The `next` field of the node pointed to by `let next = curr_node.next.load(Ordering::Acquire, guard);` is accessed. (`curr_node` originates from `let next = ...` of the previous iteration)
* How: The inserting thread allocates memory block for a node (A) -> initialize (by moving the value on stack constructed by `Node { .. }` to the memory block) -> release-write the pointer to this block to a `next` field of another node (B), making it reachable from other threads -> some thread acquire-loads the `next` field of B and this reads the message that wrote ptr to A -> the thread obtains the initialization message for A.

**Comment by wltn0029** [comment]
But is initialization is ensured by thread B's release-write? 
I think if some thread read newly inserted node pointed by already existed node, it can ensure that newly inserted node is initialized without acquire ordering due to release-write.

**Comment by tomtomjhj** [comment]
Doing initialization and getting the knowledge about the initialization is different. This is basically the same as the release-acquire synchronization example from the lecture .

**Comment by wltn0029** [comment]
Could you please provide some examples on your explanation? 
Still, I'm quite confused about what you want to say. 
In my understanding, release-acquire ordering is just reordering rule. That is, it guarantees the order of instruction is not reordered in some direction by compiler. In the example I brought here, if release is satisfied on commit point, reading side does not need to worried about initialization. Where am I wrong?

**Comment by jeehoonkang** [comment]
Release and acquire always need to be paired to achieve synchronization.  If a write is release but a read is not acquire, then they are not synchronizing with each other.  The slides and videos on the promising semantics deal with it.

Yes, release and acquire are pertaining to reordering, and release indeed forbids reordering; but in this case, to achieve the necessary synchronization, we need to additionally forbid the reordering of read by marking it as acquire.

**Comment by wltn0029** [comment]
I think I almost understand why release-acquire synchronization is needed.
My final question is : 
If read is **relaxed** ordering, is it right that below instruction would occur problem since reading part can read uninitialized node? 
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L305

**Comment by jeehoonkang** [comment]
@wltn0029 yes, the next line may be reordered before the then relaxed read, which may read uninitialized values.

**Comment by wltn0029** [comment]
But is it possible the next line is reordered? I think read-write coherence rule would prohibit that.

**Comment by jeehoonkang** [comment]
@wltn0029 would you please mention specific line numbers?  FYI, different locations are not governed by read-write coherence rules.

**Comment by wltn0029** [comment]
I mean the code which I mentioned above,
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L305
I think this line causes unpredicted access to uninitialized nodes. In order for this happen, this line should be reordered. But since returned value of the line, `node` is read right in the next line, it cannot be reordered.
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L307
As a result, any cursor cannot read uninitialized node even if it has relaxed order. 
Where am I wrong?

**Comment by jeehoonkang** [comment]
@wltn0029 it seems I cannot understand your question... Would you please rewrite your question from the scratch? I specifically want to ask you to write down (1) a complete, concrete, and clear example, and (2) what you expect, and (3) why you expect so.

**Comment by integerblue** [comment]
This is because other operations not regarding node can be reordered too.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions.

**Comment by wltn0029** [comment]
@jeehoonkang 
Actually, I guess my misunderstanding of release-acquire synchronization comes from lack of low-level knowledge. 
I think release and acquire is needed for both side (writing side and reading side) because of cache or some kinds of that. 

My actual question was: 
```
initial state: (thread A get lock)
atomicBool | true 
a          | 1 

for thread A : after writing (release ordering) 
atomicBool | true (false)
a          | 1   (2) 

for thread B : reading (relaxed ordering)
atomicBool | true (false)
a          | 1   (2) <-- it should read latest value of a because thread B read atomicBool's false
```
But now, I think my reasoning of last line `it should read latest value of a because thread B read atomicBool's false` is wrong since relaxed ordering does not guarantee to read latest value of other data structure which is not related to shared data structure. It is because cache does not update for a's value if ordering is relaxed. 

I wonder if my guess is correct.

**Comment by jeehoonkang** [comment]
@wltn0029 Yes, indeed it is correct.
