### ISSUE TITLE
Are we expected to implement lock free logic for writes into AVL tree?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/cs492-concur#24]
Only ReadGuard is imported in the following line: ```use lock::seqlock::{ReadGuard, SeqLock};```. Then, does this mean that writes(inserts and etc) to the tree should be done in lock free way(by using RMW as commit point)? Or are we allowed to use WriteGuard from seqlock? Thank you!

**Comment by jeehoonkang** [comment]
No, you can use `WriteGuard` as well.

**Comment by Shynar88** [comment]
Thank you!
