### ISSUE TITLE
[Question] HW5 Cursor Construction API (for lookup_bucket return value)

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs492-concur#241]
Hello,

For the `lookup_bucket` function in the `split_ordered_list.rs`,
I wonder how can we obtain a Cursor
from the non-null return value of `GrowableArray::get` (which returns `Atomic<Node<...>>`)?

My idea was to dereference the pointer and obtain the `next` value.
However, `Cursor`'s `next` field was not made publicly accessible. I also have looked at constructors of Cursor: (1) `Cursor::from_raw`, and (2) `List::head`, but these constructors cannot accommodate my need. 

Any tips on solving this problem? Thanks a lot.

**Comment by tomtomjhj** [comment]
> My idea was to dereference the pointer and obtain the next value.

You don't need to access `next` for this. Using `Cursor::from_raw` and `Shared::as_raw`, you can create the cursor whose `cursor.curr` is the pointer loaded from `&Atomic` returned by `GrowableArray::get`.

**Comment by jeehoonkang** [comment]
Closing; feel free to reopen it if you have further questions.
