### ISSUE TITLE
[Question] lock-free linked "guard"

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#242]
`let next = curr_node.next.load(Ordering::Acquire, guard); `

in the traversal code, we can see the `guard` is used. What is the detailed role of that `Guard` in this code, which is from crossbeam_epoch?

**Comment by tomtomjhj** [comment]
This is related to safe memory reclamation and will be discussed in the upcoming lectures. Spoiler:  a `Shared` pointer will not be `free()`ed as long as the `Guard` (used in `Atomic::{load, compare_and_set`) is alive (in scope).

**Comment by jeehoonkang** [comment]
Spoiler 2: we'll cover crossbeam-epoch in the next video.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions.
