### ISSUE TITLE
[Session 23] December, 1st

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#243]
Please do the following for the online session.

- Watch the following video(s):
    + https://youtu.be/drXrIVfBKaQ

- Solve the attendance quiz **by 23:59PM**: https://gg.kaist.ac.kr/quiz/33/

**Comment by gunwooterry** [comment]
Just reporting a typo: It's December.

**Comment by j2k0618** [comment]
Is the PDF file available for this lecture?

**Comment by jeehoonkang** [comment]
@j2k0618 slide for garbage collection is here: https://kaistackr-my.sharepoint.com/:p:/g/personal/jeehoon_kang_kaist_ac_kr/ES4ek0KUCzZOoL5Vd7N2oo0Boznax1MTti4TVFS5PhcD0A?e=XT2pBD

**Comment by j2k0618** [comment]
@jeehoonkang Could you give us the permission to print this PDF?

**Comment by travis1829** [comment]
I'm receiving "Server Error (500)" after answering the quiz and every time I try to view the quiz. However, it seems that everything else works fine. Is there something wrong?

**Comment by jeehoonkang** [comment]
@travis1829 would you please send me an email on that issue?
