### ISSUE TITLE
[Question] Asking for HW5 due date

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#244]
Since HW5 is a "bit" harder than other homeworks, the instructor has given 1 month for hw5. At first, it seemed to be enough. However, since we learned about lock-free data structure for few weeks and we started to learn "safe memory reclamation" this week(#242, #243), the due date(2020-12-11) seems a bit harsh for me.

https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-699729497
As instructor mentioned before, I would like to ask for delaying hw5 deadline.
If most of the students or instructor don't agree and seems the deadline is enough, feel free to tell me. I will try hard to meet the deadline 🙂.

**Comment by jeehoonkang** [comment]
- I agree with you that we didn't learn EBR and crossbeam-epoch, and it's a little bit difficult to do the homework without such knowledge.
- I'll extend the deadline to the end of this semester.
