### ISSUE TITLE
[Question] Enough background knowledge to start HW5

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#245]
Hi, I've just started to work on HW5,
but I'm not really confident about using of memory reclamation related functions, such as `crossbeam_epoch::{Owned,Shared,Guard}`. 
It looks like it is crucial to the safety of the program, but didn't dealt enough in the lecture yet.
However, since the professor released this homework weeks ago, is it possible to implement the program for HW5 without deeply understanding about them? 
Sorry for asking lame question, but it's a bit confusing..
Thank you.

**Comment by jeehoonkang** [comment]
We'll cover crossbeam-epoch in the next video.
