### ISSUE TITLE
[Session 24] December, 3rd

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#247]
Please do the following for the online session.

- Watch the following video(s) and article(s):
    + https://youtu.be/cYDMq5FOiw4
    + https://youtu.be/rL9Z8eQEgek
    + https://docs.rs/crossbeam-epoch/0.9.1/crossbeam_epoch/
    + http://aturon.github.io/tech/2015/08/27/epoch/#the-rust-api

- Solve the attendance quiz **by 23:59PM**: https://gg.kaist.ac.kr/quiz/34/

**Comment by YujinGaya** [comment]
Typo report: The quiz answer is not in snake_case. It's a type name so it follows [UpperCamelCase](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#general-naming-conventions)

**Comment by jeehoonkang** [comment]
@YujinGaya Thanks!  It's just fixed.
