### ISSUE TITLE
[Question] Difference between deref() and as_ref()

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#249]
What is the difference of 
`Shared::deref` and `Shared::as_ref`?

Both give a reference to the pointing value, and are used in the lock-free queue implementation.

By the documentation, `deref` **dereferences the pointee and give reference to it**
`as_ref` **converts pointer to reference**.

How those two differs?

**Comment by tomtomjhj** [comment]
`as_ref` returns `None` is the pointer is null.

**Comment by AnHaechan** [comment]
Oh, so nothing more was different then that. Thanks!!
