### ISSUE TITLE
Question about Hazard Pointer

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#250]
In lecture slide of hazard pointer
![image](https://user-images.githubusercontent.com/40551890/101016680-76e07280-35ac-11eb-94a6-f5f77212fbf2.png)

Why do we call `unprotect()` between L16 and L17?

I think that it can make user after-free-error in L17 CAS operation if the other thread do `free()` (or `retire()`) the node.

Is the case that I mentioned above impossible?

**Comment by AnHaechan** [comment]
`cur` is pointer to shared memory location, which is local variable.
As long as it does not dereference it (to access shared memory), the shared memory location that `cur` points does not need to be protected.
L17's CAS operation only use the value of pointer(address value), not the pointee(i.e. the shared memory location)

**Comment by Jaegoomon** [comment]
Ahh... I totally understand what you mean.. I think that your explanation makes sense!! 

Thank you so much~
