### ISSUE TITLE
[Question] The reason of recursive initialization of parent buckets

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#252]
In the required reading of Homework 5: The Art of Multiprocessor Programming 13.3, LockFreeHashSet class has BucketList to be initialized, but it needs the parent bucket to be initialized. 

I am curious why the parent bucket needs to be initialized because it seems that the parent bucket has no relationship with the initializing bucket.
Also, I am curious about the relationship between the parent and the child, because getParent() method is not understood with instinct.

**Comment by tomtomjhj** [comment]
Do you understand what's going on figures 13.12, 13.13 and 13.20?

**Comment by integerblue** [comment]
@tomtomjhj I understood 13.12 and 13.13, but in 13.20, I don't understand why sentinel node 1 is needed to insert sentinel node 3.
Also, by calculation, 0 is the parent of key 1 and key 2, and I don't understand why.

**Comment by tomtomjhj** [comment]
> I don't understand why sentinel node 1 is needed to insert sentinel node 3.

I believe this is for efficiency. By recursively initializing the buckets, it can reduce list traversal for future accesses. For example in 13.20, suppose you don't initialize 1 when inserting 7. Then when 5 is inserted, it has to traverse the list from the start again. I guess this may affect the time complexity (left as an exercise).


> Also, by calculation, 0 is the parent of key 1 and key 2, and I don't understand why.

Please review the definition of *parent* on page 311.
