### ISSUE TITLE
[Question] [Homework 5] Switching the value of a sentinel node

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#253]
Hello, I have a question about how sentinel nodes work. As far as I understand data structure, the sentinel node should not be deleted as it holds the next several nodes so that the time accessing the nodes remains constant, so inserting a value to the node which is sentinel seems to be impossible. I thought about directly changing the value, but the changing the value with `Shared` memory the cursor provides looks unsafe because other threads may also hold it, too. I have no idea how I should deal with this problem. Can you give me some hint or point out where I got wrong if it is okay?

**Comment by tomtomjhj** [comment]
> To avoid an awkward “corner case” that arises when deleting a node referenced by a bucket reference, we add a *sentinel* node, which is never deleted, to the start of each bucket. [..] To distinguish sentinel items from ordinary items, we set the most significant bit (MSB) of ordinary items to 1, and leave the sentinel items with 0 at the MSB.

https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/homework/src/hash_table/split_ordered_list.rs#L62-L64 This assertion ensures that the MSB of the item's key is zero so that we can tag the MSB with 1.
