### ISSUE TITLE
[Homework 5] move occurs in lookup function

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#254]
I have a trouble in implementing lookup function for split order list.
Return value of lookup function is `Option<&'a V>` which can be obtained through node's value. 
But since node's value field is private and `into_value()` takes node, I cannot get node's value. How to do that?

**Comment by tomtomjhj** [comment]
`Cursor::lookup`

**Comment by zhanto97** [comment]
If you look at the `lookup` implementation of `Cursor`, `as_ref` [method](https://doc.rust-lang.org/std/option/enum.Option.html#method.as_ref) of `Option` is used.

**Comment by wltn0029** [comment]
Oh,, that's right. Thank you!!!!!
