### ISSUE TITLE
[Question] Asan failure of stress_concurrent of Growable Array

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#255]
I implemented get() and drop() of GrowableArray.
Basic tests and asan smoke and stress_sequential tests are passed.
However, stress_concurrent leaks memory. 
I thought we do not need to worry about Ordering in drop() because we have a mutable reference of self. 
Because of the failure, I added SeqCst/AcqRel Ordering at loading self.root at the beginning of drop(), but it still failed.
What might have I missed?

**Comment by tomtomjhj** [comment]
Questions: Are you using CAS to install a newly allocated segment? If so, how do you handle the failure case?

**Comment by integerblue** [comment]
@tomtomjhj I used CAS but didn't handle the failure case. Thank you!!!

**Comment by Jaechan-So** [comment]
> Questions: Are you using CAS to install a newly allocated segment? If so, how do you handle the failure case?

I also faced the problem in the question, so I handled the failure case, but there are still asan failures for concurrent test cases. In my failure case, I dropped the `Owned<Segment>` from the `Pointer::from_usize(seg)` which `seg` is from `Pointer::into_usize()` beforehand. Did I miss anything?

**Comment by tomtomjhj** [comment]
Hmm I'm not sure. Have you identified the source of the leaked memory? Asan output tells you where the leak comes from.

**Comment by Jaechan-So** [comment]
Ah I found that I didn't consider the case of 'concurrent modification of the `root`' case, so I guess the leak was from there. Thank you! 😄
