### ISSUE TITLE
[Question] Instructions for final exam.

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#256]
As final in less than two weeks away, I was wondering if details about the final will be posted soon. I assumed that we can essentially modify the dates in #116, but I was wondering if we will have another test session this Thursday, or if there will be any modifications from the midterm. It will be very helpful if the professor can post the announcement soon. Thank you very much!

**Comment by jeehoonkang** [comment]
The test will be in the same format. We will have a practice session next Tuesday or Thursday (TBA).
