### ISSUE TITLE
[Question] Why usize is returned from SplitOrderedList::find()?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#257]
Return type of find() is (usize, bool, Cursor<'s, usize, Option<V>>).
Why usize is returned? I guess that's for key, but &key is input of find().

**Comment by tomtomjhj** [comment]
In our implementation, `find` returns `let size = self.size.load(Ordering::Acquire)` which is necessary for `find` itself and `insert`.

**Comment by YujinGaya** [comment]
I thought the size isn't needed so I removed it from the return type and got full score. Still not sure whether I implemented it right though 🙃

**Comment by tomtomjhj** [comment]
@YujinGaya no problem.
