### ISSUE TITLE
[Question] HW#5 tag max value

### ISSUE THREAD

**Issue by us0310306** [kaist-cp/cs492-concur#258]
I'm trying to do the growable array.
When I use `with_tag`, there's problem that it can save only height 0~7.
Is there way to save over 7 height or should I use another way to save the height bigger than 7?

**Comment by YujinGaya** [comment]
`index` is `usize`, so `0 <= index <= 2^64 - 1`.

Each node represents 10bits so the height is maximum 64 / 10 + 1 = 7.

**Comment by us0310306** [comment]
Oh, `SEGMENT_LOGSIZE` was 10. I confused that example was 3. Thank you!
