### ISSUE TITLE
 Instructions for the final exam on the 17th of December (Thu)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#259]
Hi all,

- We will remotely conduct the **final exam on the 17th of December (Thu), 10:15-11:45**.  (**No extension** will be given.)

- We will have a **mandatory practice session on the 8th of December (Thu), 10:30-11:45**.

- For the final, students are required to participate in two Google Hangout Meet rooms.  The students should **join the rooms at least at 10:00**.  As soon as you join the rooms, please write down your name and student id in both rooms.

    + [Announcement room](https://meet.google.com/zqd-qmgd-sga):
      Join with your device in which you'll solve the final exam problems.
      I will announce important notes in this room.  You don't need to turn on the camera or microphone.

    + "CCTV" rooms for [odd student ids](https://meet.google.com/wst-qiqi-qbb) and [even student ids](https://meet.google.com/caf-hizs-yeh):
      For the entirety of the meeting, you need to **turn on your camera** and **show your hand, paper, keyboard, and monitor**.
      I'm attaching the model scene from the experienced TA below.  If you cannot set up a camera like this, please let me know as soon as possible.

- On the screen, you can only look at the followings:

    + https://github.com/kaist-cp/cs492-concur/issues/259
    + https://gg.kaist.ac.kr
    + the Google form for the exam
    + A simple text editor of your choice (e.g., notepad or gedit, but not vscode)

- For the final exam, go to https://gg.kaist.ac.kr/course/6 and check your final exam event token.
  Then open the Google form that will be announced in gg and answer the questions.
  You need to (1) log in with a Google account, and (2) fill out your email, name, student ID, and the event token.

- You can ask questions here: https://gg.kaist.ac.kr/event/3  If your question is not answered for 10 minutes, please let me know in the announcement room's chat.  Questions can be written either in Korean or English.

    + If you want to go to the bathroom, please ask a question.  After getting permission, you may go.  After turning back, please ask a question again that says you returned.

    + If you want to leave early, please ask a question.  After getting permission, you may leave.

![IMG_5492](https://user-images.githubusercontent.com/1201316/95432855-28d33800-098a-11eb-9b18-b515c34bb2e9.jpg)

**Comment by Lee-Janggun** [comment]
> * On the screen, you can only look at the followings:
>   
>   * #258
>   * https://gg.kaist.ac.kr
>   * the Google form for the exam
>   * A simple text editor of your choice (e.g., notepad or gedit, but not vscode)


I assume the issue we can look at is #259 not #258?

**Comment by wltn0029** [comment]
Where is link to Google Hangout Meet rooms for practice session?

**Comment by jeehoonkang** [comment]
@wltn0029 Please come to https://meet.google.com/zqd-qmgd-sga

**Comment by Lee-Janggun** [comment]
Are the rooms open yet?
