### ISSUE TITLE
[Session 25, LIVE invited talk] Jaeseung Ha (Software Engineer, FuriosaAI), December, 10th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#260]
On the 10th of December, Jaeseung Ha (Software Engineer, FuriosaAI) will give us an invited talk.  [FuriosaAI](https://www.furiosa.ai/) is building "high-performance AI inference coprocessors that can be seamlessly integrated into various computing platforms including data centers, servers, desktops, automobiles and robots."  As it will be evident in the invited talk, the theory and practice of concurrency is a key ingredient of the company.

The talk will be given in Korean. **If you speak Korean, it is mandatory** to (virtually) attend this talk at [Google Hangout Meet](https://meet.google.com/zqd-qmgd-sga).  If you're interested in personally meeting with Jaeseung and FuriosaAI, please [send me an email](mailto:jeehoon.kang@kaist.ac.kr).

**Comment by TonyWild** [comment]
Is there no session tomorrow?

**Comment by jeehoonkang** [comment]
@TonyWild We'll have a practice session for the final tomorrow: #259
