### ISSUE TITLE
[Question] Could cursor.find_harris fail?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#261]
I implemented SplitOrderedList but stress_concurrent sometimes fails with cursor.find_harris().unwrap().
Therefore, I changed unwrap to handle Error as false.
Is this right implementation or have I missed something else?

**Comment by tomtomjhj** [comment]
`find_harris` can return `Err` here.
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L138-L140

Note that this failure doesn't mean the absence of the key. So the wrapper `find` loops until it returns `Ok`:
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L279-L283
