### ISSUE TITLE
[Question] [HW5] Finding position to insert a bucket

### ISSUE THREAD

**Issue by Jaechan-So** [kaist-cp/cs492-concur#263]
I feel confused about implementing `split_ordered_list.rs`. Following is what I understood:

For `lookup_bucket()`, we have to initialize the bucket which are uninitialized. So we have to insert initialized buckets into the `SplitOrderedList.list`. But if there are non-bucket nodes, we have to find proper position to insert it since the invariant (which is mentioned in the paper) must be held for future split ordering.

Then, how can we search the proper position with only given API (such as `Cursor`, `Node`...)? At the first time I tried to implement with accessing the `Node.next`, but since it is a private field, I couldn't do it. Can you give me some hints for this..?

**Comment by AnHaechan** [comment]
If you use appropriate key(that is, split-ordered key explained in the paper) for the list,
`Cursor.find` will automatically tell you the right position.

**Comment by zhanto97** [comment]
You can add private methods for initializing buckets

**Comment by Jaechan-So** [comment]
I got your point.  I missed the break point of  `Cursor.find`. Also now I realized that it could done by recursively. Thank you @AnHaechan @zhanto97 😊
