### ISSUE TITLE
[Homework 6] Hazard Pointers (due: 2020-12-22 23:59:59+0900)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs492-concur#265]
Implement Hazard Pointers.  Please read either [this](https://ieeexplore.ieee.org/document/1291819) or [this](https://erdani.com/publications/cuj-2004-12.pdf).  They are articles by [Maged Michael](https://www.linkedin.com/in/maged-michael-bab1138a/), the original author of hazard pointers and a great pioneer of concurrent programming.

* Fill in the `todo!()`s in [`hazard_pointer/mod.rs`](../blob/master/homework/src/hazard_pointer/mod.rs), [`hazard_pointer/hazard.rs`](../blob/master/homework/src/hazard_pointer/hazard.rs), [`hazard_pointer/retire.rs`](../blob/master/homework/src/hazard_pointer/retire.rs) (approx 70 lines)
* submission: TBA

# Tips
* Use [`thread::current()`](https://doc.rust-lang.org/std/thread/fn.current.html)[`.id()`](https://doc.rust-lang.org/std/thread/struct.Thread.html#method.id)
* [`u8::trailing_zeros`](https://doc.rust-lang.org/std/primitive.u8.html#method.trailing_zeros) is useful when implementing `LocalHazards` and `LocalHazardsIter`.

# grading: (100 pts) 
Run `./scripts/grade-6.sh`.

* Basic (`cargo [--release]`): 30 points
* AddressSanitizer (`cargo_asan [--release]`): 40 points
* Synchronization (`cargo --features check-loom`): 30 points

Submssion:  https://gg.kaist.ac.kr/assignment/25/

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/commit/a62762a246a240f54e6361e7b163d97697894b14
Added one more function to implement.

**Comment by tomtomjhj** [comment]
* https://github.com/kaist-cp/cs492-concur/commit/5877fbd7b93acdb4680be1e4b0fe9008c9985cc1 replaced `Hazards` with a proper lock-free data structure
* https://github.com/kaist-cp/cs492-concur/commit/1353c0da9f50c182f621ee4bcf491c7d348ee369 added a test using lock-free stack

**Comment by tomtomjhj** [comment]
* 227f77391be543acb32997cea612f9ac6b279d1c added note on synchronization using `fence(SeqCst)`
* 21a491699047c204fc4dac878d3d3d5b03e6e8b2 added some tests and grading script. Please run `cargo update` before running the test.

**Comment by totolacky** [comment]
The grader gives a full score even if `validate()` is implemented so that it always returns `true`.

**Comment by tomtomjhj** [comment]
@totolacky does it pass `cargo test --features check-loom --test hazard_pointer sync`?

**Comment by totolacky** [comment]
Sorry, it was my mistake. Some tests were somehow removed from my /tests/hazard_pointers.rs.

**Comment by integerblue** [comment]
Request for the submission.

**Comment by tomtomjhj** [comment]
a9d355cf06323d33af17a9c22e57cb38fae37fe5 added more doc about synchronization and some tests (resolves #291)

**Comment by tomtomjhj** [comment]
submission site is now open: https://gg.kaist.ac.kr/assignment/24/

**Comment by zzz845zz** [comment]
Typo report: `./scripts/grade-5.sh` in grading
