### ISSUE TITLE
[Question] Can a DS be "not lock-free" even though it does not use locks?

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/cs492-concur#266]
From the name "lock-free", it seems as if a DS is a lock-free DS if it does not use locks.
However, according to the definition of lock freedom, we need at least one operation to be always completed someday, and it seems that we can't guarantee this just by not using locks. That is, we can "mimic" locks by using RMW instructions.

For example, in the lock-free list implementations, if we change it to make threads to restart the traversal every time it meets a logically deleted node (and expect the thread that logically deleted it to also physically delete it), then it seems that this will end up with something similar (but not same) to locked data structures.

In such case, is it correct that the DS is "not lock-free" even though it does not use locks?

**Comment by jeehoonkang** [comment]
Yes, you're right.  Yet I don't have a concrete example of blocking data structure without locks...  The reason is lock is the easiest way to implement blocking data structures.

**Comment by travis1829** [comment]
Okay! Thank you for answering! It also seems that if we want a blocking data structure, we would use locks in the first place anyway.
