### ISSUE TITLE
[Question] Is it ok to run asan log_concurrent more than 60s?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#267]
My SplitOrderedList takes more than 60s, about 160s to run the asan log_concurrent test.
Is this ok for grading?

**Comment by tomtomjhj** [comment]
How long does it take on the homework server?

**Comment by YujinGaya** [comment]
@tomtomjhj The homework server does not accepting submissions.

**Comment by tomtomjhj** [comment]
I mean you can ssh into the server we provided and run tests there. Ours take less than 30s with debug build + asan. If it takes that much on the server then there might be some issue in your implementation.

**Comment by integerblue** [comment]
@tomtomjhj basic and asan tests pass, but tsan test does not pass for log_concurrent.
I am working on changing my implementation, but failing to do so.

**Comment by tomtomjhj** [comment]
Are you running tsan test with `--release`? ThreadSanitizer introduces 5x-15x slowdown because of complex checks so the tsan + debug mode is extremely slow. So we are only using
https://github.com/kaist-cp/cs492-concur/blob/78d7e71c714efbd52e255eb0628e75cf667805af/homework/scripts/grade-5.sh#L90
for tsan tests.

**Comment by integerblue** [comment]
@tomtomjhj I didn't know that, but my implementation takes over 60s even in basic tests. I think it succeeds because there is no time limit in basic tests. It is strange because there is no occurrence of shared.is_null() becoming true after sizing up to 8192...
Maybe returned cursor.find_harris takes long... :(

**Comment by tomtomjhj** [comment]
>  because there is no time limit in basic tests

There is a time limit (3m) but this is way too lenient. I'll set the timeout to 3x-5x of the time our implementation took in average.
