### ISSUE TITLE
rustc panic in asan test

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#269]
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/query/mod.rs:235:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (3d6705aa5 2020-12-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', /rustc/3d6705aa5abffe94c83bf09af8c3ba3c599845fc/compiler/rustc_codegen_ssa/src/back/write.rs:1425:21

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (3d6705aa5 2020-12-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `cs492-concur-homework`
```

Is there anyone why those errors occurs? 

I have not revised any code except for project `.rs` file. 

But only in asan sanitizer test, those error occurs. Do I have to reinstall rustc or programs related to asan? 

I have no idea, please help me....

**Comment by integerblue** [comment]
Getting the same error occasionally.

**Comment by travis1829** [comment]
I also had similar errors often. In my case, it worked again after running cargo clean, and then running the commands.

**Comment by Jaegoomon** [comment]
Oh really? Thanks for comments, then I try again few hours later.....

**Comment by integerblue** [comment]
cargo clean fails of removing homework/target/rls/debug/deps/.nfs~~ file.

**Comment by travis1829** [comment]
That also happened to me, but it seems like you can ignore it.
Honestly, I also don't know the precise problem nor solution, but in my case after running
`cargo clean`, and then running
`cargo update`, `cargo build`, and then `cargo_asan ...`,
it worked.

**Comment by integerblue** [comment]
The reason was that I didn't properly exit the test execution and build files could not be removed. 
I terminated the process manually by htop and did cargo clean again.

**Comment by integerblue** [comment]
The error happens continuously even if I correctly terminate the test.

**Comment by tomtomjhj** [comment]
Wow that's interesting. For now, lets use older nightly
```diff
diff --git a/scripts/grade-utils.sh b/scripts/grade-utils.sh
index 5c6b6b7..aea163a 100755
--- a/scripts/grade-utils.sh
+++ b/scripts/grade-utils.sh
@@ -7,7 +7,7 @@
 # * RUNNERS: array of "cargo[_asan | _tsan] [--release]"
 # * TIMEOUT: default 10s
 
-rustup toolchain update stable nightly
+# rustup toolchain update stable nightly
 
 echo_err() {
     echo -e "\033[0;31m\033[1m$@\033[0m" 1>&2
@@ -31,7 +31,7 @@ cargo_asan() {
     local SUBCOMMAND=$1; shift
     RUSTFLAGS="-Z sanitizer=address" \
         RUSTDOCFLAGS="-Z sanitizer=address" \
-        cargo +nightly $SUBCOMMAND --target x86_64-unknown-linux-gnu $@
+        cargo +nightly-2020-09-23 $SUBCOMMAND --target x86_64-unknown-linux-gnu $@
 }
 export -f cargo_asan
 
@@ -41,7 +41,7 @@ cargo_tsan() {
         TSAN_OPTIONS="suppressions=suppress_tsan.txt" \
         RUSTDOCFLAGS="-Z sanitizer=thread" \
         RUST_TEST_THREADS=1 \
-        cargo +nightly $SUBCOMMAND --target x86_64-unknown-linux-gnu $@
+        cargo +nightly-2020-09-23 $SUBCOMMAND --target x86_64-unknown-linux-gnu $@
 }
 export -f cargo_tsan
```

**Comment by integerblue** [comment]
```
s20140600@kaist-cp-cs492:~/cs492-concur/homework$ RUSTFLAGS="-Z sanitizer=address" RUSTDOCFLAGS="-Z sanitizer=address" cargo +nightly-2020-09-23 test --target x86_64-unknown-linux-gnu --test split_ordered_list smoke -- --nocapture
error: toolchain 'nightly-2020-09-23-x86_64-unknown-linux-gnu' is not installed
```

**Comment by tomtomjhj** [comment]
```
rustup toolchain install nightly-2020-09-23-x86_64-unknown-linux-gnu
```

**Comment by jeehoonkang** [comment]
Thank you for the report.  Did anyone report it via https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md ?

**Comment by Jaegoomon** [comment]
No, I didn't..

**Comment by travis1829** [comment]
Me neither

**Comment by bryanswkim99** [comment]
I'm having the same problem, even after fetching upstream and after running the line
'rustup toolchain install nightly-2020-09-23-x86_64-unknown-linux-gnu'

Is there anything more I must do to solve this problem?

**Comment by tomtomjhj** [comment]
@bryanswkim99 have you applied this diff https://github.com/kaist-cp/cs492-concur/issues/269#issuecomment-740670530 ?

**Comment by bryanswkim99** [comment]
Oh, I didn't yet. Should I copy and paste the whole thing? Sorry I'm a little new to git :(

**Comment by jeehoonkang** [comment]
- I'd like to keep it open until the issue is reported to the rust repository.
- If you're inclined to do so, please do it and give me your student id.

**Comment by YujinGaya** [comment]
Seems like the [Issue](https://github.com/rust-lang/rust/issues/79661) is already reported and it was related to incremental compilation. Hence the `cargo clean` worked.

The fix has been [merged yesterday](https://github.com/rust-lang/rust/pull/79721). So it'll be fine after nightly 2020-12-09 I guess?
