### ISSUE TITLE
[Question] insert using list.insert()

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#270]
I wonder if this is a correct implementation.
I inserted a sentinel node in the list using self.list.insert() and traversed through the whole list from the beginning to find the inserted node.
This passed the test but I thought this is not a correct one so I copied and pasted the implementation inside the self.list.insert() and modified to use parent cursor instead of self.list.head().

It was an awkward thing to do because if self.list had a helper function that gets a cursor as an input and returns the cursor as an output, it would be more convenient to implement. Is this correct?

**Comment by tomtomjhj** [comment]
This?
https://github.com/kaist-cp/cs492-concur/blob/91d4f286677a3ec076e9fc046d6454a06e93421d/lockfree/src/list.rs#L213-L229

**Comment by integerblue** [comment]
@tomtomjhj No. I used self.list.harris_insert().

**Comment by tomtomjhj** [comment]
I mean that should be used instead of `harris_insert`, etc..

**Comment by integerblue** [comment]
@tomtomjhj Ah, I meant I almost replicated the code inside of harris_insert, and that seems a little bit awkward.
Anyway, thanks!
