### ISSUE TITLE
[Question] find_harris Acquiring the next node

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#271]
Hello, I have a question about the find_harris function in lock free list.
In the lecture, it is said that using Acquire guarantees that the 'next' have the latest value even during the later stage of the function.
https://github.com/kaist-cp/cs492-concur/blob/91d4f286677a3ec076e9fc046d6454a06e93421d/lockfree/src/list.rs#L109
The thing is, I don't see what 'latest value' means exactly. If it means that we get the 'latest next' node of the curr node, what makes it work so?  I thought other thread B can insert a new node 2 between while the thread A moves through the list, starting at node 1 and then move to node 3.
```
                        threadB (inserts node2)
      node1   ->   node2   -> node3
          ^                        ^
                                threadA
```
Or does it mean that we can safely dereference the 'next' node we got from the line 109 as the load function used guard so that it cannot be deallocated until the thread that used the guard vanishes? In this case, is the node still can be logically deleted?
Thank you for the help in advance.

**Comment by integerblue** [comment]
It guarantees the latest value using a loop, load acquire, compare_and_set. It loads the latest value, compare_and_set so that assures the latest value atomically. If it fails, the loop will do the job again. 
Please let me know if this is not correct. @tomtomjhj @jeehoonkang

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/238#issuecomment-735348254 ?
