### ISSUE TITLE
[Question] homework 5 How do with_tag and tag work?

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#272]
I have trouble understanding the tag for atomic. In Rust document about `Shared`, there is an example about with_tag() function. This is from the document:
```
let p1 = a.load(SeqCst, guard);
let p2 = p1.with_tag(2);

assert_eq!(p1.tag(), 0);
assert_eq!(p2.tag(), 2);
```
There is one Atomic and p1 and p2 get different tag about the same Atomic. The explanation says:
```Returns the same pointer, but tagged with tag. tag is truncated to be fit into the unused bits of the pointer to T.```
This is confusing to me because we use tag to mark the height of the growable array in homework5. If the loaded pointer can have different tags, how is it possible to use it as a fixed value for the memory(In this case, we should mark the tree height which should be the same for all the pointers referencing the atomic)? If we can separately tag to its allocated memory and with_tag() different value, then which one does the tag() function read?
Thanks always for your help.

**Comment by YujinGaya** [comment]
`Atomic` represents the address that we store the pointer, while `Shared` is the pointer that's read from the `Atomic`. You might think of it as a relationship between [`AtomicUsize`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html) and `usize`, or [`AtomicPtr<T>`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html) and`*mut T`


| library           | Where you store pointer  | The pointer |
| -------------| -------------------------| ------------- |
| C-equivalent | `**T`                                | `*T`               |
| std::sync        | `AtomicPtr<T>`              | `*mut T`        |
| crossbeam-epoch | `Atomic<T>`          | `Shared<T>`  |

So here with `p2`, you have a pointer that has been read from `a` and changing what you've read from a place doesn't change what's written in the place.

Note that `Shared` exists to limit the usage of the pointer. If we were to return `*mut T`, it doesn't have lifetime so we will freely access the data even after the guard drop. With `Shared<'g T>`, the lifetime of guard, we can guarantee the pointer won't be used after the guard drop.

**Comment by haeeun-14** [comment]
Thank you for the explanation! It helps me a lot :)
