### ISSUE TITLE
[Question] HW5 trouble in lookup function for split ordered list

### ISSUE THREAD

**Issue by j2k0618** [kaist-cp/cs492-concur#273]
I have a trouble in lookup function for split ordered list.
I made the cursor with self.find and used Cursor::lookup for split ordered linked list.
But there are "returns a value referencing data owned by the current function" error when I just return the result from unwarp() and as_ref() for results from Cursor::lookup function.
Could you give some advice to solve this problem please?

**Comment by tomtomjhj** [comment]
Try `cargo update`

**Comment by tomtomjhj** [comment]
The order version of `Cursor::lookup` had wrong lifetimes for the returned reference. This is the fix. https://github.com/kaist-cp/cs492-concur/commit/7b93570b1d8a6f7f4a32c0379284397969c9c6e1
