### ISSUE TITLE
[Question] growable array invalid memory reference

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#275]
I am having invalid memory reference, when I simply call assert_eq!(list.lookup(&2000, &guard), None); in smoke().
I found out that in the invalid memory reference occurs at let ptr = slot.load(Ordering::Acquire, guard);, however, I couldn't figure out how to solve this problem in my get() function.

Maybe there is a problem with my segment allocation code. Can you give me some help by reviewing my code @tomtomjhj ? It is so hard to figure out the exact reason..

**Comment by tomtomjhj** [comment]
Since the bug can be reliably reproduced, I think the debugger will be helpful. Does your growable array implementation pass the growable array tests?

**Comment by saltylight** [comment]
@tomtomjhj 
No, I get `invalid memory reference` in the growable array test. I am now using this simple code to test the error.
```
fn smoke() {
    let list = ArrayMap::<usize>::default();
    let guard = pin();
    assert_eq!(list.lookup(&2000, &guard), None); // => invalid memory reference
}
```
By debugging, I checked that invalid memory reference occurs when I create `height = 2` growable array. (`height = 1` has no problem)
```
let mut new_segment = Segment::new();
new_segment.inner[0] = AtomicUsize::new(root.into_usize());
let new_atomic = Owned::new(new_segment);
```
I create a new segment and perform CAS with root & new_atomic.(If it is required to do it multiple times, there is a loop for that) This works well for height=1 but for height=2, should I do something else to prevent `invalid memory reference`?

**Comment by tomtomjhj** [comment]
As a sanity check, please first inspect the exact value of the pointer being dereferenced. Is it null or something else?

**Comment by saltylight** [comment]
Checked null pointers. Thank you.
