### ISSUE TITLE
[Question] Hw#5 Ideas about log_concurrent timeout?

### ISSUE THREAD

**Issue by mjkang-estrella** [kaist-cp/cs492-concur#276]
First, current status:
- I succeed in all test cases in `grade-5.sh` for `growable_array`.
- Because `cargo_asan` takes 4.67s and `cargo_tsan` takes 1.97s, it seems there is no problem in `growable_array` implementation.
- However, for `split_ordered_list`, `log_concurrent` make timeout all the time. In self-test, it succeed, but takes about 118 sec.
- Other test cases succeed even in `cargo_asan`.

I tried following approaches to solve timeout issue
- Early return for the situation when CAS can be failed easily, check it before CAS.
- Early return for some break status for loops
- Loosening Orderings
- Tightening recursion in `lookup_bucket`

In my opinion, my timeout can be happen by
- Inefficiency in `lookup_bucket`
- More Loosening for Orderings
- Need more efficiency in `growable_array`

I try to solve my timeout issue for quite a long time, but I can't figure out what circumstance makes this problem. Can I get some common pitfalls that make timeout, or approaches to solve the issue?

Thanks.

**Comment by tomtomjhj** [comment]
That is probably because of unnecessary list traversals. Related: #270

**Comment by mjkang-estrella** [comment]
Problem Solved:
- When there is already bucket in `lookup_bucket`, I was traversing list to find the right cursor.
- I solved this with returning `Cursor::from_raw(atomic_node, shared_node.as_raw())` with only the bucket that I get.
- However, I wonder `atomic_node` that I get and insert is not the right one which I'll found with `cursor.find()`.

Is there any better way to make the cursor with only atomic node?

**Comment by tomtomjhj** [comment]
> returning Cursor::from_raw(atomic_node, shared_node.as_raw()) with only the bucket that I get.

This is correct.

> However, I wonder atomic_node that I get and insert is not the right one which I'll found with cursor.find().

I'm not quite sure what this means. Can you elaborate?

**Comment by mjkang-estrella** [comment]
I was not certain about atomic_node that I get is the same one that previous_node.next have, so I thought there might be a better idea for it.

Since that was the correct implementation, it seems that they are the same one!
