### ISSUE TITLE
[Question] HW5 How to store the key prefix (in growable_array)

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#277]
Hi, I'm wondering about where to store the key prefix in the growable tree. To elaborate, consider the following example. Say that 
```
SEGMENT_LOGSIZE = 8
```
In an empty growable array, insert 'cat' at index 0x0b00 0001. Then, we have
```
         +----+
         |root|
         +----+
            | height: 1
            v
+----+----+----+-   -+----+
| 00 | 01 | 02 | ... | FF |
+----+----+----+-   -+----+
        |
        v
      +---+
      |cat|
      +---+
```
Then, the key suffix (which is 01) is stored in the array. However, we also need to store '0b0000' somewhere to grow the tree later on. Where should we save such prefixes?

The only possible way that I can think of is to add an extra field to the GrowableArray struct, like this.
```
pub struct GrowableArray<T> {
    root: Atomic<Segment>,
    prefix: usize,
    _marker: PhantomData<T>,
}
```
Are we allowed to do this? Or is there any better way to store such prefixes?

**Comment by zhanto97** [comment]
What do you mean by

> the key suffix (which is 01) is stored in the array

01 here is an index so that Segment.inner[1] == address of `cat`. Hope this helps

**Comment by totolacky** [comment]
@zhanto97  I meant that we somehow managed to keep the information '01' in the array, but the information about '0b0000' is lost. We still need '0b0000' to be stored somewhere in order to grow the tree later on, and I'm wondering about how we should store this value.

**Comment by Jaechan-So** [comment]
If I understood your point correctly, then the growable array must have height of 4, with 'cat' is stored in 0b->00->00->01.

**Comment by totolacky** [comment]
@Jaechan-So I got it. Thanks!

**Comment by totolacky** [comment]
@Jaechan-So Can I ask one more question?
If the index is 000b 0001, then how should it be stored? 00->0b->00->01 or 0b->00->01?

**Comment by Jaechan-So** [comment]
If you insert the 'cat' in the empty growable array, then 0b->00->01 will be correct. If you insert the 'cat' in the non-empty (i.e. height > 3), then 00->...->00->0b->00->01 will be correct. (Here '...' means that '00' will be repeated for (height - 3) times)

**Comment by totolacky** [comment]
Thanks a lot!
