### ISSUE TITLE
[Question] log_concurrent fail "Option::unwrap() on a None"

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#278]
```
running 4 tests
test smoke ... ok
test stress_concurrent ... ok
test stress_sequential ... ok
test log_concurrent ... FAILED

failures:

---- log_concurrent stdout ----
thread 'log_concurrent' panicked at 'called `Option::unwrap()` on a `None` value', tests/map/mod.rs:224:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I passed 3 tests, but failed at log_concurrent. I am thinking about how to solve it, but it is a bit challenging.
Did anyone face this error? I literally understood the error message but don't know what to fix.
(In get(), I am currently using `Ordering::SeqCst` everytime. 🤔)

**Comment by tomtomjhj** [comment]
growable array or split ordered list?

**Comment by saltylight** [comment]
@tomtomjhj It is growable_array 😭

**Comment by tomtomjhj** [comment]
`log_concurrent` logs the operations and checks the consistency of the log (the check is not perfect, though). For example, if the key `k` was successfully deleted twice, then `k` must have been inserted at least twice.

**Comment by tomtomjhj** [comment]
`stress_sequential` checks the correctness in single-threaded setting. Since your implementation passed that test, it's correct for single-threaded case.

First thing to check: Are you using `Atomic::store` or `AtomicUsize::store`? Using `store` here is usually wrong. Make sure that important modifications are done using `compare_and_set` or `compare_exchange`.

**Comment by saltylight** [comment]
I was using AtomicUsize::store and changed it to compare_and_swap .
However, same error occurs still 😭 ...

**Comment by tomtomjhj** [comment]
Oh, for `AtomicUsize`, I recommend you to `compare_exchange` so that you can explicitly handle the failure case.
