### ISSUE TITLE
[Question] HW5 Growable Array Not Implemented Error

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#279]
I have implemented everything in growable_array.rs (in the sense that there is no todo!() in the code), but the smoke test gives not implemented error when I run the grading program. My implementation may be incorrect, but I think I shouldn't get such error because I have removed all todo!()s.

Does the smoke test for growable_array require something in split_ordered_list.rs to be implemented?

Thanks in advance!

**Comment by f52985** [comment]
Look at the error message. It tells you panic happens at which line of the which file.

**Comment by totolacky** [comment]
I checked the error message, and running the test somehow seems to execute a test in /tests/art.rs, instead of tests/growable_array.rs.

**Comment by f52985** [comment]
What command did you use for the test?

**Comment by totolacky** [comment]
I've tried two approaches.
1. Run `./scripts/grade-5.sh` in the homework directory
2. Click the 'Run test' button below `#[test]` in /tests/growable_array.rs.

Both approaches gave the same results. However, the second method works well if I change the test name ('smoke') to something else.

**Comment by tomtomjhj** [comment]
huh that's odd. `cargo test --test growable_array` runs `tests/growable_array.rs` only. Try `cargo clean`

**Comment by totolacky** [comment]
`cargo clean` worked. Thanks!
