### ISSUE TITLE
homework#5 memory leak

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#282]
I have trouble in passing split_ordered_list stress_sequential because of memory leak.
I think memory leak is due to I don't free heap memory after use. But I think the only heap memory which is required to be freed is what I make newly for new segment. And I do free if there is CAS failure. 
Why is it happened? I have no idea..

**Comment by tomtomjhj** [comment]
Have you identified the source of the leaked memory? Asan output tells you where the leak comes from.

**Comment by wltn0029** [comment]
Yes, and asan says memory leak occurs in lines `let new_segment = Owned::new(Segment::new());`. 
But it is just allocation memory.. Why is it happened?

**Comment by tomtomjhj** [comment]
Did you implement `Drop`?

**Comment by wltn0029** [comment]
no.. is it needed?
By the way, even if I drop segment's inner, it does not work :(

**Comment by tomtomjhj** [comment]
You should implement this in `Drop`
https://github.com/kaist-cp/cs492-concur/blob/1353c0da9f50c182f621ee4bcf491c7d348ee369/homework/src/hash_table/growable_array.rs#L99-L128

**Comment by wltn0029** [comment]
Yes it is required when array is dropped, but I think it is not needed when segment is dropped. Since newly made segment doesn't have child, it just drop its inner value, I think...

**Comment by tomtomjhj** [comment]
In `stress_sequential` (single-threaded), CAS failure case doesn't occur and the allocated segment will be inserted into the growable array. That's why I think your `impl Drop for GrowableArray` has some problems.

**Comment by tomtomjhj** [comment]
`self.root.load(Ordering::Relaxed, unprotected()).deref_mut().deref_mut()` is `&segment.inner`.

BTW what development environment are you using? If you're using vscode, try the rust-analyzer extension. This will give some helpful info like types of variables, etc.

**Comment by wltn0029** [comment]
rust-analyzer is really great! Thank you :)
Anyway, if `deref_mut` correctly returns `&Segment`, I think my implementation should be right..
Whenever I run `cargo test --test split_ordered_list -- stress_sequential -- nocapture`, terminal says `thread 'stress_sequential' panicked at 'attempt to shift left with overflow`. Do you think it is the reason why I have trouble in? .. 
Also I want to ask you that how I ignore such overflow occurring in shift operator.

**Comment by tomtomjhj** [comment]
Is the overflow intended?

**Comment by wltn0029** [comment]
yes it is intended.

**Comment by tomtomjhj** [comment]
https://doc.rust-lang.org/std/primitive.usize.html#method.overflowing_shl

**Comment by jeehoonkang** [comment]
@wltn0029 do you have follow-up questions?

**Comment by wltn0029** [comment]
no follow-up questions. Thank you 😊
