### ISSUE TITLE
Please evaluate the course TA by 20th of December (Sunday)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#285]
All of you should have gotten emails from the administrative office that ask you to evaluate the course TAs. Your input for this course's TA (@tomtomjhj) will be very much appreciated.

Just in case you don't precisely know the TA's role in this course, he did:
- re-design this course with me;
- prepare some lecture slides;
- prepare the skeleton code for the homework assignments;
- evaluate your submissions to the assignments; and
- answer your questions and run the TA office hour.

**Comment by saltylight** [comment]
Oh, I didn't know there was an office hour. 😭 When is it?

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur#logistics Maybe I should've advertised it more.

**Comment by saltylight** [comment]
OMG. Is there TA office hour next week?

**Comment by tomtomjhj** [comment]
yes

**Comment by nv-quan** [comment]
Does anyone have the link for the evaluation, I clicked on the link on my email and it only says "Disallowed Key Characters."

**Comment by tomtomjhj** [comment]
`https://csta.kaist.ac.kr/assis_est/index.php/users/login/${YOUR_KAIST_EMAIL_ID}%7C%7Ckaist.ac.kr`

**Comment by nv-quan** [comment]
Oh turns out that the link doesn't work with firefox. I can access now from chrome, thank you.

**Comment by jeehoonkang** [comment]
hmm, it works for my Firefox 83.0 64bit, Ubuntu 20.04...  Anyway, it doesn't work, please use other browsers as @nv-quan suggested.

**Comment by integerblue** [comment]
> https://github.com/kaist-cp/cs492-concur#logistics Maybe I should've advertised it more.

OMG, I really didn't realize it...... No one told me there was one... I must've attended if I knew it before.

**Comment by jeehoonkang** [comment]
It's by today. I hope all of you give us feedback.
