### ISSUE TITLE
[Question] Passed stress_concurrent but failed stress_sequential

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#286]
Hello, I am working on growable_array now. I passed smoke test and now have an odd test result on other tests.
```
iteration 1808: lookup(35652674) (non-existing)
thread 'stress_sequential' panicked at 'assertion failed: `(left == right)`
  left: `Some(12456660911310215)`,
 right: `None`', tests/map/mod.rs:51:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- log_concurrent stdout ----
thread 'log_concurrent' panicked at 'assertion failed: inserts.contains_key(v)', tests/map/mod.rs:218:22


failures:
    log_concurrent
    stress_sequential

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```
I have done several tests to get this result. `stress_sequential` test fails sometimes with `log_concurrent` test(log_concurrent fails everytime), but `stress_concurrent` test passed everytime I test them. As I know `stress_concurrent` test is the same as `stress_sequential` except that it uses several threads, I think `stress_concurrent` should fail. However, in the hope that I might have a clue about the error in the code, is there any difference between the two stress tests or possible cause of this kind of result?

**Comment by tomtomjhj** [comment]
* `stress_sequential` checks if your implementation acts like `std::collections::HashMap` in single threaded settings (correctness)
* `stress_concurrent` randomly runs operations with random keys and ignores the results. So it's not like `stress_sequential` (sorry for poor naming).
* `log_concurrent` is the correctness test for multi-threaded setting but it's not perfect. https://github.com/kaist-cp/cs492-concur/issues/278#issuecomment-742667348

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions.
