### ISSUE TITLE
[Question] Why ManuallyDrop in Treiber's stack?

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#287]
In Treiber's stack, 
`Node<T>.data : ManuallyDrop<T>`.

The reason of using `ManuallyDrop` explained in the lecture slide is that :
>  Because data’s ownership is returned by pop(), while Node<T> will be deallocated later

However, I cannot find out clear reason to use it.

```
[Stack::pop]
//---code----//
unsafe {
  guard.defer_destroy(head);
  return Some(ManuallyDrop::into_inner(ptr::read(&(*h).data)));
}
//---code---//
```

In the above code,
(1) head pointer (or node pointed by head pointer) is retired
(2) using `ptr::read`, only `Node.data` inside `Node` is bit-wise copied and returned.

Since `Stack::pop` returns the bit-wise copy of `Node.data`, and the `Node` is stored at heap region, and will be `Drop::drop`ped later by the epoch based garbage collector,
**(1) Why is `ManuallyDrop<T>` is necessary?**
**(2) If it is necessary, why it wasn't used in lock-free list?**

**Comment by integerblue** [comment]
(1) The ownership is the same. Read data from pointer points to the same memory block.
https://doc.rust-lang.org/std/ptr/fn.read.html#ownership-of-the-returned-value
(2) I don't know. @jeehoonkang @tomtomjhj

**Comment by tomtomjhj** [comment]
> If it is necessary, why it wasn't used in lock-free list?

That's a good point. Actually the previous version used `ManuallyDrop` but we removed it in this commit  https://github.com/kaist-cp/cs492-concur/commit/7ca204ff452b756cac1cbf77f1945d609e30d92b . This is ok because `remove` only returns the reference to the value guarded by a `Guard`.

**Comment by integerblue** [comment]
@tomtomjhj Oh, I see. Thanks!

**Comment by totolacky** [comment]
Is the data in Michael-Scott's Queue not marked as ManuallyDrop due to the same reason? The comments say that it is ManuallyDrop, but it is actually MaybeUninit.

**Comment by tomtomjhj** [comment]
> Is the data in Michael-Scott's Queue not ManuallyDrop due to the same reason?

Yeah. `MaybeUninit<T>` is similar to `Option<ManuallyDrop<T>>`.

**Comment by AnHaechan** [comment]
@tomtomjhj  
Why is it possible to occur multiple drops of `T`?
As long as Treiber's stack satisfies the contextual refinement,
pop operation for a single node can only happen once.
Therefore, I think the only reason of multiple drop is because,
`Node<T>` will be dropped by `crossbeam::epoch`'s garbage collector.
If so, isn't it enough to use `Option<T>` for `Node.data`? 
That is by using `Option<T>::take` in the pop operation.

**Comment by tomtomjhj** [comment]
> Therefore, I think the only reason of multiple drop is because, After pop operation that returnsNode.data, the sameNode will be dropped by crossbeam::epoch's garbage collector, and destructor of Node will call destructor of Node.data and Node.next.

Exactly.

> If so, isn't it enough to use Option<T> for Node.data?

In some cases you can use `Option<T>` instead of `ManuallyDrop<T>`. But in this case, we only have `&Node<T>`, not `&mut Node<T>`. `Option::take` takes `&mut self` because in general writing `None::<T>` is not atomic → data race. 

Another advantage of `ManuallyDrop<T>` is that its memory layout is identical to `T` (`#[repr(transparent)]`). This is not true in general for `Option<T>` because it may require a tag (which occupies a word) to discriminate `None` and `Some(...)`. This can be optimized away if `T` is always non-null or non-zero.

**Comment by tomtomjhj** [comment]
Speaking of `MaybeUninit`, in HW5, you can actually use `MaybeUninit<V>` instead of `Option<V>` in the `Node` type. Our first implementation used `MaybeUninit` but I removed it so that students don't need to spend more time on learning less essential stuff for a homework that is already tough.
