### ISSUE TITLE
[Question] HW6 Why do alloc() and dealloc() in hazards.rs need to be unsafe?

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#288]
In hazard.rs, I've notices that `alloc()` and `dealloc()` functions are marked as unsafe.

As far as I understood, the only thing we are doing is to (atomically) change the values of `self.occupied` and the elements in the list `self.elements`. Is there any unsafe operation that needs to be done here?

**Comment by jeehoonkang** [comment]
Because we assume it's called by only one thread.  If two threads are concurrently executing it, there will be a problem.

That constraint is not fully conveyed in the types, so we need to mark it as `unsafe`.

**Comment by totolacky** [comment]
So it's marked as unsafe just to show the existence of an additional constraint (not because we need to perform any unsafe operations like raw pointer dereference)! Thanks a lot 😀
