### ISSUE TITLE
[Question] [Homework6] What is the difference between protect() and get_protected()?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#289]
I passed check-loom protect_collect_sync but not check-loom get_protected_collect_sync.
It seems that both test codes are very similar.
I simply loaded the pointer of atomic in get_protected() and protect(pointer).
Is this not enough? I thought this is okay because validation occurs inside protect().

**Comment by tomtomjhj** [comment]
> validation occurs inside protect().

How do you do this? I think validating the shield inside `protect` is not meaningful because you don't have access to the source `Atomic`.

> passed check-loom protect_collect_sync but not check-loom get_protected_collect_sync

Maybe because you don't `validate` inside `get_protected`. `protect_collect_sync` does (proper) validation after `protect` and `get_protected_collect_sync` expects `get_protected` to do a proper validation.

**Comment by integerblue** [comment]
Thanks! I think that's a problem.
However, if I remove validation inside protect(), protect_collect_sync also fails.
What I did is make a new shield and validate it, return the shield if the validation successes or None if not.
Is this problem somewhere else?

**Comment by totolacky** [comment]
I think when the validation fails, you should try to create a valid shield again instead of returning None. Returning None means that there is no room in the hazard pointer list.

**Comment by integerblue** [comment]
I think I got the point.
The reason was that after making the shield, you should make a fence and return the shield, not directly return the shield.
I fenced and made a shield which was the problem.

**Comment by integerblue** [comment]
@totolacky Thank you! I think you are right.
