### ISSUE TITLE
[Question] HW6 Ordering used in LocalHazards

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#291]
https://github.com/kaist-cp/cs492-concur/blob/21a491699047c204fc4dac878d3d3d5b03e6e8b2/homework/src/hazard_pointer/hazard.rs#L68

I think LocalHazards is thread-local so we don't need AtomicU8 or [AtomicUsize].
Why atomic is used and why acquire is used here?

**Comment by YujinGaya** [comment]
A threads can _read_ other thread's LocalHazards. Each LocalHazards is a single-writer multi-reader data. https://github.com/kaist-cp/cs492-concur/blob/21a491699047c204fc4dac878d3d3d5b03e6e8b2/homework/src/hazard_pointer/hazard.rs#L268-L280

**Comment by tomtomjhj** [comment]
@YujinGaya is right. In fact, there should be a release-acquire synchronization between `LocalHazards::dealloc` and `collect`. I'll add this to the documentation.

**Comment by integerblue** [comment]
@YujinGaya I got the point! Thanks.
@tomtomjhj So the test cases do not cover the release-acquire synchronization between `LocalHazards::dealloc` and `collect`? Thanks!

**Comment by tomtomjhj** [comment]
@integerblue added a test for that https://github.com/kaist-cp/cs492-concur/issues/265#issuecomment-744534506

**Comment by integerblue** [comment]
@tomtomjhj I guess load could be relaxed because the only writes are happening in the same thread, and store should be release because other threads are loading the values, right? But I am still not sure because store is not synchronized with load in the same thread, so that they could be reordered. Is this prevented by RW coherence?

**Comment by tomtomjhj** [comment]
> I guess load could be relaxed because the only writes are happening in the same thread, and store should be release because other threads are loading the values, right?

I don't understand what this means

> store is not synchronized with load in the same thread so that they could be reordered.  Is this prevented by RW coherence?

view?

**Comment by integerblue** [comment]
@tomtomjhj Oh yes. I think you are right.
What I meant was that load could be relaxed because, in promising semantics, the local thread always has the same view when store, so that load could be relaxed. However, store release should be used because other threads should load acquire the values to get the latest view of the data. 
One more question. Then, if there are no other threads, load and store could be both used as relaxed behavior?

**Comment by tomtomjhj** [comment]
>  if there are no other threads, load and store could be both used as relaxed behavior?

yeah, and it's equivalent to not using `AtomicXXX` types at all.
