### ISSUE TITLE
[Question] HW5 lookup 

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#292]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/23091531/102076838-b3815900-3e4b-11eb-992d-d7fc5acbcfa4.png">

I guess `lookup()` function's implementation would be similar to LockFree List's `lookup()`
However, it seems I can't access `cursor.curr` due to private field issue.
I tried to return `Option<&'a V>` by using Cursor's lookup() function but still it fails due to ownership problem.

How can I solve this?

**Comment by tomtomjhj** [comment]
> I tried to return Option<&'a V> by using Cursor's lookup() function but still it fails due to ownership problem.

#273?
