### ISSUE TITLE
[Question] [HW5] SplitOrderedList insert leaks Owned<Node>

### ISSUE THREAD

**Issue by Jaechan-So** [kaist-cp/cs492-concur#294]
In the concurrent test (both stress_concurrent and log_concurrent) of `split_ordered_list.rs`, I got some leaks from `insert()`, with owned pointer of node.  Here, I considered following points:

* If the list already has the element with given key (`find()` says found == true), return `Err` with `into_box().into_value()`
* If insertion fails (return `Err`), recover the owned pointer and continue the loop

From #229 and #230 I checked that `into_box().into_value()` does not make any leaks, so I guessed that my leak is from `delete()` or dropping the elements of `List`.

Since `Drop` of `List` is given API, I think I don't have to care about it. Also my `delete()` is very similar to it from the `List`. Can you give me a little tip here? I'm guessing that I missed some corner cases, since the leaked bytes are not too great (32 bytes per allocation, and almost constantly, only 1~3 allocations have been leaked for stress_concurrent) but I have no idea :(

**Comment by tomtomjhj** [comment]
hmm not sure why. 

* make sure that you correctly handle the failure cases of all CASes.
* try to make an interesting test case, e.g. multiple threads inserting/deleting the same key, etc.

**Comment by tomtomjhj** [comment]
Some students privately reported to me that they had a similar problem and there was something wrong in their `lookup_bucket`.

**Comment by ArshiAAkhavan** [comment]
Hi
Did anyone find any solution to this issue? i also have the same issue and my implementation is similar to what is described in the comments
