### ISSUE TITLE
[Question] About grading options

### ISSUE THREAD

**Issue by BanseokWoo** [kaist-cp/cs492-concur#295]
Hello, I'm curious whether grading for this course will be able to choose between S/U and ABC or will be ABC for all.

I'm hoping there would be some flexibility regarding the grading, considering the circumstances of class being held online.

As much as I hope there wouldn't be such attempts, I can't shake off the fact that someone with the intention might cheat on the upcoming exam.(Someone certainly might have in the midterm too, I think)

And with all due respect, considering the fact that there's only one TA for this course despite the fact that there are 70~ students taking this course, there are high chances of such attempts occur yet not be caught.

I strongly agree that it is the best you could do and I highly appreciate for making the exam environment as fair as possible, but I think it's not enough to ensure fairness as in the offline exam. So I think it's reasonable to give options for choosing between these two options.

Since then, the ones like me, who are concerned about experiencing relative disadvantages because of those who (possibly) cheated, may choose S/U option so that independent on whether such events occurred, one can be sure that damage would be as minimal as possible to individual.

I wish I asked this question earlier, but I started being concerned about it after I realized some other classes I take have exam format with even more vulnerability to cheating. So I figured I should ask it for this course too.

I understand it is totally up to you but I really hope you consider the things I said and I think even if you adopt this, (hopefully) it would be a one time thing for this course since the situation might get way better next fall. But if even considering what I mentioned, S/U is out of the table, may I lastly ask, what are your thoughts on what I mentioned and why are you insisting on ABC grades?

Thank you for your attention.

**Comment by jeehoonkang** [comment]
- Grading is ABC.  I believe it's much more effective than SU in motivating you all to study the subject matter.

- Even though there are only one official TA, we have 3 more helpers and the 4 supervises the exam environment.  I think we can quite completely monitor what you're doing in the exam.

- I'm fully convicted to punish cheaters as harsh as I can, not only giving F but also calling for the official punishment committee of the department.  Again, it's much more effective than the lenient policy in motivating you to study.  If you are aware of any inappropriate activities regarding exam or homework, please send me an email.

I'm not sure I fully covered your questions.  If not, please ask follow-up questions as github issue discussion.

**Comment by BanseokWoo** [comment]
@jeehoonkang Thanks. It pretty much covered everything.
