### ISSUE TITLE
[Question] When would the midterm scores come out?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#297]
I think the score of the midterm exam is quite important.

The first reason is that preparing for the final exam could be a lot easier if we look at the missed questions and answers, we could figure out what we've thought wrong and what we've missed. I think this is very important because an exam is for not only evaluating students but also teach them what they don't know. 

The next reason is that there is not that much time left for the final exam and end of the semester, so I need the chance to claim. If the midterm score doesn't come out, then there would be no guarantee that the final exam score would come out soon too.

Thank you.

**Comment by jeehoonkang** [comment]
I'm marking your solutions, but I don't think I can announce it today or tomorrow.  Sorry for the delay.

**Comment by jeehoonkang** [comment]
Scores for the true/false questions, and the first/second essay questions, are announced: https://gg.kaist.ac.kr/course/6/

**Comment by jeehoonkang** [comment]
- Now the midterm scores are out at https://gg.kaist.ac.kr/course/6/ .
- You will be able to claim on those scores along with those for the final exam.
