### ISSUE TITLE
[Question] What if all other threads end their epochs and a new thread starts in EBR?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#298]
In lecture slides, if T3 does not exist, then e+2 of T1 seems to safely free block b. Then, is it safe to free block even if in e+2 in some circumstances? or in this case, T1 is not in e+2 epoch or rather in e' which can free all other blocks before the thread?

**Comment by jeehoonkang** [comment]
I don't quite follow your question.  Would you please explain the situation in more detail, e.g., by referencing the slide numbers?

**Comment by integerblue** [comment]
@jeehoonkang slide number 9 in https://kaistackr-my.sharepoint.com/:p:/g/personal/jeehoon_kang_kaist_ac_kr/ES4ek0KUCzZOoL5Vd7N2oo0Boznax1MTti4TVFS5PhcD0A?rtime=IfMb1Uqg2Eg

**Comment by jeehoonkang** [comment]
what is "e+2 of T1"?

**Comment by TonyWild** [comment]
I think integerblue meant to say "second active state of T2" (instead of T1)
Assuming T3 does not exist, the second active state of T2 can safely free `b` although it would be labeled as "epoch of e+2"

**Comment by TonyWild** [comment]
uh...wait, if T3 does not exist, the second active state of T2 should be labeled "e+3" instead of "e+2"... I guess...? Is it right?

**Comment by integerblue** [comment]
@TonyWild Yes, that is exactly what I meant.

**Comment by tomtomjhj** [comment]
> Then, is it safe to free block even if in e+2 in some circumstances?

There is no reliable way to check if it is "in some circumstances" so we always have to enforce the rule.

**Comment by integerblue** [comment]
@tomtomjhj Then, how could we know that the current thread should start epoch e+2 or e+3? I thought we could figure out if there are no ongoing epochs or not by finding which epoch to start.

**Comment by tomtomjhj** [comment]
EBR keeps a [data structure](https://github.com/crossbeam-rs/crossbeam/blob/530ebb7452764b4a86a8c68248b9c4b8afff4cf2/crossbeam-epoch/src/internal.rs#L348) that holds the state (epoch, ...) of each thread and iterates the list of them. For efficiency, EBR usually maintains a global epoch so that `set_active` doesn't have to iterate the list every time.

**Comment by integerblue** [comment]
@tomtomjhj Then the global epoch could be set to e+3 if there are no other threads running with the epoch.
Meaning, a thread sets to global epoch + 1 when set_active and compares the global epoch with the thread's epoch when set_quiscent. If they are the same, the global data structure should be iterated to find if the thread is really the last one that has epoch e or not to figure out to increment the global epoch. Therefore, the thread could set the global epoch to e+3 when there are no other threads running with epoch.

**Comment by tomtomjhj** [comment]
Right.
