### ISSUE TITLE
[Question] Hazard Pointer example in the slide

### ISSUE THREAD

**Issue by TonyWild** [kaist-cp/cs492-concur#299]
![image](https://user-images.githubusercontent.com/18462177/102188113-3eb82880-3ef8-11eb-89a6-7fe0e743045f.png)

In this example code of hazard pointer applying to Treiber's Stack, the three lines of code before line 16 needs to be added in order to protect `cur`.
However, if the condition of `if (this->head.load() != cur)` holds, shouldn't we call `unprotect(cur)` before we continue the loop?
I think `cur` will be stayed as `protected` indefinitely if we don't call `unprotect(cur)` inside the `if` statement in the blue box.

**Comment by tomtomjhj** [comment]
Right. BTW in hw6 `unprotect` is `Shield::drop`.

**Comment by TonyWild** [comment]
Thank you! 👍
