### ISSUE TITLE
Attendance for Wednesday 11th of September

### ISSUE THREAD

**Issue by RosieBahrani** [kaist-cp/cs492-concur#3]
On Wednesday, September 11th, the professor did not take attendance for the Concurrent programmng course, but I did attend the class. Now, when I log into my attendance portal, I see a "No" for that Wednesday's class. I was wondering if you could please correct it, because I was indeed present in class.

**Comment by cmpark0126** [comment]
No attendance check Wednesday, September 11th.
All students will be considered attended that day.

To reduce confusion, I have deleted that session page.
