### ISSUE TITLE
[Question] Can a DS be lock-free even if it has locks?

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#300]
There was a similar question(#266) before, asking if a DS can be not lock-free even if it does not have a lock. (The basic idea was that the definition of lock-freedom does not mention anything about the existence of locks.) Similarly, can a DS be lock-free even if it has locks?

For example, the lock-coupled linked list guarantees that at least one operation is finished (as deadlocks and livelocks cannot happen under such construction). Then, is the lock-coupled linked list lock-free, even if it uses locks?

**Comment by tomtomjhj** [comment]
I agree with your point, but they are not called lock-free because the operations will block if the thread holding the lock is suspended. So the definition is "operation is lock-free if some threads (that are not suspended) can make progress even in the presence of other suspended thread".

**Comment by totolacky** [comment]
@tomtomjhj Thanks for your answer! 
Adding to the original question, can deadlock happen for lock-coupled linked lists? The [slides](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.ga50d357ce9_0_269) say that it is possible, but I can't come up with any example of such deadlock.

**Comment by tomtomjhj** [comment]
You can implement lock-coupled list that is deadlock-free (and you can prove it).

**Comment by totolacky** [comment]
Thanks!
