### ISSUE TITLE
[Question] Why &(*h).data is used instead of &h.data in Treiber's stack?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#301]
https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lockfree/src/stack.rs#L75-L78
Why &(*h).data is used instead of &h.data in Treiber's stack?

**Comment by tomtomjhj** [comment]
You can use `&h.data`.
