### ISSUE TITLE
[Question] why MCS parking lock recheck locked value after unparked

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#302]
In the lecture slide, 
`In MCS parking lock, after unparked, why we check if it’s unlocked?`
I think it is because checking unlock instruction contains load operation with acquire ordering. And I guess it leads synchronization between unlocking thread (caller thread.unpark())and unlocked thread (callee thread.unpark()). 
Is it right?

**Comment by totolacky** [comment]
Actually, I was also confused because even the reference code doesn't check it.
https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lock/src/mcsparkinglock.rs#L65-L87

**Comment by integerblue** [comment]
I think you are right. The operations in the critical section before unlock() should be released so that the next thread with lock() can acquire the view.

**Comment by totolacky** [comment]
According to the [Rust docs](https://doc.rust-lang.org/std/thread/fn.park.html), 
```
A call to park does not guarantee that the thread will remain parked forever,
and callers should be prepared for this possibility.
```
So I guess it is because the thread can wake up, even if the previous thread did not call unpark().

**Comment by integerblue** [comment]
**That** is not what I expected...

**Comment by jeehoonkang** [comment]
- @totolacky is right. We need loop because thread may be unparked spuriously.
- It's not because we need (additional) synchronization. If there are no spurious wakups, thread parking/unparking handles the necessary synchronization.
