### ISSUE TITLE
[Question] Could push() & try_pop() in Michael-Scott Queue could be refactored to this?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#303]
https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lockfree/src/queue.rs#L79-L107

```
        loop {
            // We push onto the tail, so we'll start optimistically by looking there first.
            let tail = self.tail.load(Ordering::Acquire, guard);

            let tail_ref = unsafe { tail.deref() };

            match tail_ref
                .next
                .compare_and_set(Shared::null(), new, Ordering::Release, guard)
            {
                Ok(_) => {
                    // try to move the tail pointer forward.
                    let _ = self
                        .tail
                        .compare_and_set(tail, new, Ordering::Release, guard);
                    break;
                }
                Err(e) => {
                    let _ = self
                        .tail
                        .compare_and_set(tail, e.current, Ordering::Release, guard);
                }
            }
        }
```
It seems that `let next = tail_ref.next.load(Ordering::Acquire, guard);` is useless because compare_and_set is already comparing tail_ref.next with null pointer.

**Comment by integerblue** [comment]
In the same fashion, try_pop() in Michael-Scott Queue could be refactored too.
https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lockfree/src/queue.rs#L113-L140
```
    pub fn try_pop(&self, guard: &Guard) -> Option<T> {
        loop {
            let head = self.head.load(Ordering::Acquire, guard);
            let h = unsafe { head.deref() };
            let next = h.next.load(Ordering::Acquire, guard);
            let next_ref = some_or!(unsafe { next.as_ref() }, return None);

            let _ = self.tail.compare_and_set(head, next, Ordering::Release, guard);

            if self
                .head
                .compare_and_set(head, next, Ordering::Release, guard)
                .is_ok()
            {
                unsafe {
                    guard.defer_destroy(head);
                    return Some(ptr::read(&next_ref.data).assume_init());
                }
            }
        }
    }
```

**Comment by zzz845zz** [comment]
> It seems that self.tail.load() is useless because compare_and_set is already comparing tail_ref.next with null pointer.

Do you mean `let next = tail_ref.next.load(Ordering::Acquire)`, not `self.tail.load()`?

**Comment by integerblue** [comment]
@zzz845zz Thank you for letting me know. It is actually `let next = tail_ref.next.load(Ordering::Acquire, guard);`. I updated the comment.

**Comment by zzz845zz** [comment]
I also had doubts about the need for `tail_ref.next.load()` in the push operation.

And I have one more question, 
Is there any counter case if we use relaxed ordering for `tail_ref.next.load()` instead of solution of @integerblue ?

For this reason, I think it is safe to use relaxed ordering for `tail_ref.next.load()`.
Suppose that `T` is the tail what current thread read from https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lockfree/src/queue.rs#L81
1. There is no dereference of `next`
2. The only case where `T`'s next can be changed is from null to new tail.
3. If `T`'s next is old value (the latest value is one of the new tails), the CAS in L98 will be failed.

**Comment by Lee-Janggun** [comment]
I do think refactoring is possible, as the professor did mention the implementation is a straightforward from the algorithm.

However for your version of MS-Queue, I do think it will lead to a bit of deficiency as your version will always preform `self.tail.compare_and_set(head, next, Ordering::Release, guard)` while the original only did it when `tail == head`.

Also for you're  `push()`, what is `new` that you are CASing?

**Comment by integerblue** [comment]
I thought loading and CAS with fail is a actually same, and even if we found that tail does not equal the head, the CAS might fail. Therefore having a only one CAS on the head pointer seemed to be enough.

Also, new is defined in upper part of the function which I did not copy and paste.

**Comment by tomtomjhj** [comment]
* Suggested changes by @integerblue look correct to me. 
* I think @zzz845zz is correct about relaxing `tail_ref.next.load()` in push. Can you send a PR for that?

**Comment by tomtomjhj** [comment]
@zzz845zz I think `tail_ref.next.load()` should be `Acquire` because it's necessary for maintaining the invariant on `self.tail` (together with L91). If you think this is wrong, please open a new issue.
