### ISSUE TITLE
[Question] Homework 6 Validate function 

### ISSUE THREAD

**Issue by irfanariq** [kaist-cp/cs492-concur#307]
Hi! I would like to ask about the validate function.

```text
(T1-1) add b to the hazard list (Shield::new())   | (T2-1) unlink b (and retire b)
(T1-2) check if b is still reachable (validate()) | (T2-2) check if b is in the hazard list
       if so, deref b                             |        if not, free b
(T1-3) remove b from the hazard list              |
       (Shield::drop)                             |
```

in the above explanation, validate() function should check whether b is still reachable or not. Can you explain more how to check whether b is reachable or not?

Thank you.

**Comment by tomtomjhj** [comment]
`b: Shared<T>` and it is returned by `load`ing an `Atomic<T>`. `b` is reachable if the value of source `Atomic<T>` didn't change from `b`.

**Comment by Jaegoomon** [comment]
@tomtomjhj 
> `Atomic<T>` didn't change from `b`.

Then , it means I have to change b in retire function? 

And also, I'm little confused about meaning of `unlink`. Before pushing retire list, do I have to change the value of b by using tagging or something??

**Comment by tomtomjhj** [comment]
before
```
Atomic<T>          b: Shared<T>
+-------+          +--------+
|   b   |--------->|        |
+-------+          +--------+
```
unlinked `b` and linked `b'`
```
Atomic<T>          b: Shared<T>
+-------+          +--------+
|   b'  |          |        |
+-------+          +--------+
    |
    |              b': Shared<T>
    |              +--------+  
    +------------->|        |  
                   +--------+  
```

**Comment by irfanariq** [comment]
based on your visualization, pointer `b: Shared<T>` and `b': Share<T>` is different right?

so, if I still get the value `b: Shared<T>` after `b: Shared<T>` is unlinked, does it means the usage of `fence` in my implementation is incorrect? because the thread that load `b: Atomic<T>` do not get the latest value that is `b': Shared<T>`?

**Comment by tomtomjhj** [comment]
> based on your visualization, pointer b: Shared<T> and b': Share<T> is different right?

yes

> so, if I still get the value b: Shared<T> after b: Shared<T> is unlinked, does it means the usage of fence in my implementation is incorrect?

Even if the implementation is correct, this is possible if `T1`'s fence runs before `T2`'s fence. But it's still safe because `T2` knows that `b` is added to the hazard list. If `T2`'s fence runs first, then `T1` will not read `b`.
