### ISSUE TITLE
[Question] homework#5 attempt to subtract with overflow error

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#308]
In growable_array, I try to calculate the index of each level using bitwise calculation.
And I think to get the index, index should be shifted left. 
```
level_mask = 0x3ff;
level = current growable array's total level
cur_level = current level 
level_index = (index >> (level - cur_level) * segment_size) & level_mask
```
So I calculate index of level as above. But whenever I try this, grader says I'm attempting to subtract with overflow error.. 
But I cannot find my error. :( How could I handle this?

**Comment by Jaechan-So** [comment]
[https://doc.rust-lang.org/std/primitive.usize.html#method.wrapping_sub](https://doc.rust-lang.org/std/primitive.usize.html#method.wrapping_sub)
Perhaps this will be helpful.

**Comment by wltn0029** [comment]
oh, Thank you!
