### ISSUE TITLE
[Question] homework #5 stress sequential don't stop running 

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#309]
Whenever I run `RUSTFLAGS="-Z sanitizer=address" RUSTDOCFLAGS="-Z sanitizer=address" cargo +nightly test --target x86_64-unknown-linux-gnu --test growable_array -- stress_sequential`, the result of test does not come out and is running continuously. I have no idea to handle it :(

**Comment by tomtomjhj** [comment]
Try
<pre>cargo test --test growable_array -- stress_sequential <strong>--nocapture</strong><pre>

**Comment by wltn0029** [comment]
It results same T.T

**Comment by tomtomjhj** [comment]
then there is probably an infinite loop in your implementation

**Comment by tomtomjhj** [comment]
yeah it should print something like
```

running 1 test
iteration 0: lookup(306244774665666624) (non-existing)
iteration 2: lookup(307441336515297348) (non-existing)
iteration 3: insert(4629705089861304384, 10316640976574515211)
iteration 4: insert(4899991179690509380, 6419190074349086563)
iteration 5: delete(4899991179690509380) (existing)
...
```

**Comment by wltn0029** [comment]
infinite loop in my drop function.. Thank you!
