### ISSUE TITLE
[Final exam] on everything you've learned from midterm (12/16)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#31]
### Logistics

- Date & time: 9:00am-11:00am, December 16th, 2019
- Place: Rm. 2111, Bldg. E3-1
- Coverage: everything you’ve learned from midterm
- Bring a black/blue pen and your student ID (no pencil, please)

**Comment by jeehoonkang** [comment]
You can claim on your final scores on December 19th (Thu), 10-11am or 1-2pm.  If you cannot make the time, please send me an email.

**Comment by codingskynet** [comment]
The final score isn't uploaded in my "gg.kaist.ac.kr". But, could I check my own score at claim section?

**Comment by jeehoonkang** [comment]
@codingskynet I'm sorry I couldn't finish marking the exam.  It's my bad.

- You (and everyone) can still come to my office today, 10-11am and 1-2pm, to see your answer sheet and score.  **Please send me your student id and name via email.**

- You can also check the score tomorrow (Friday), 10-11am and 1-2pm.

**Comment by jeehoonkang** [comment]
I finished marking, but couldn't count the score yet.  I'll upload them by the noon today (Friday).  If you want to see your answers and claim on your score, please visit 10-11am and 1-2pm today.

**Comment by jeehoonkang** [comment]
The score is uploaded at gg.kaist.ac.kr .  Average is 64 and standard deviation is 30.  Here's the histogram: https://docs.google.com/spreadsheets/d/e/2PACX-1vTDQOfktv97Ybg-nm0BRP8MCo3y2spJ1E2c14MIG_BO5dws2T8dy2bjM3ZZnx25jNpdgfyEVXGiWrbz/pubchart?oid=201505511&format=interactive

**Comment by jeehoonkang** [comment]
If you want to claim on your score, please send me an email.  Thanks!
