### ISSUE TITLE
[Question] HW5 SplitOrderedList memory leak in concurrent situation

### ISSUE THREAD

**Issue by yominx** [kaist-cp/cs492-concur#310]
Hi, I'm implementing SplitOrderedList(SOL)and I passed all the basic tests and tsan tests but I failed on the cargo_asan: `stress_concurrent` and` log_concurrent`.

cargo_asan says, there are some memory leaks from `SplitOrderedList::insert(key, value, guard).`

I implemented the insert method as below.

1. Make a node that will be insert to the hash table by using `Owned::new(Node::new(key, Some(value)))`
2. in the loop, use `self.find(key, guard)`, and if there is a node, return Err immediately.
3. Else, use `cursor.insert()` to insert the node to the hash table and increase `self.count` atomically, and expand the size if` count > 2 * size`.

 But cargo_asan says,

`AddressSanitizer: 96 byte(s) leaked in 3 allocation(s).`
and it says it was allocated from the first implementation: `Owned::new(Node::new(key, Some(value)))` in the `SplitOrderedList::insert(key, value, guard)`.

I think it is originated from the doubling hash table size when `count > size * LOAD_FACTOR`: because without this size increment, it works well (For sure, it is not right implementation). 

Here's my question.
1. Why my implementation makes memory leak even my SOL have perfect functionality? I mean, I think that if SOL provides perfect functionality, all nodes are in the list or deallocated correctly, so it should be dropped well through `List::Drop()`.
2. Could you advise anything on my implementation?

**Comment by tomtomjhj** [comment]
> cursor.insert()

What do you do when this returns `Err`?

**Comment by yominx** [comment]
@tomtomjhj 
I take similar method with `List::lookup`.
`Err(node) => new_node = node,`
go to the first line of the `loop{}`.

There are only few memory leaks but I don't know where makes this problem...

**Comment by tomtomjhj** [comment]
Maybe you're having the same issue from #294. Closing this issue in favor of that.
