### ISSUE TITLE
[HW5] Cursor::from_raw()

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#311]
`Cursor::from_raw(target as *const _, curr.deref() as *const _)`

I use that function for returning cursor  in split_ordered_list.rs `look_bucket`. But when I use it, it makes memory leak. but I don't know why that funciton makes memory leak. Is there anyone who know about it?

I used that function like that
```rust
let target = self.buckets.get(index, guard);
let curr = target.load(Ordering::Acquire, guard);
if !curr.is_null() {
            return unsafe { Cursor::from_raw(target as *const _, curr.deref() as *const _) };
}
```

**Comment by zhanto97** [comment]
It was mentioned in multiple issues that we should use `Shared::as_raw` (instead of `curr.deref()`). Return type of `curr.deref()` does not seem to be what is expected.
