### ISSUE TITLE
[Question] Homework#5 drop

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#312]
I have difficulty in implementing drop.
At the first time I thought for drop segment, it is enough to drop its inner data `drop(segment.deref().deref())`
But asan tester said there is direct memory leak, so I fix my code to drop entire segment by making it to box `drop(segment.into_box)`. But tester still said there is direct and indirect memory leak where new segment is allocated. 
I wonder what is proper way to drop segment.

**Comment by tomtomjhj** [comment]
Are you dropping the children segments recursively?

**Comment by wltn0029** [comment]
yes.. except for CAS fail case

**Comment by wltn0029** [comment]
it was clearly my drop function did not drop all child segment
