### ISSUE TITLE
[Question] HW5 - grader seems not working properly

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#314]
Among the tests of HW5,

thread sanitizer test for `growable_array` gives different results in the submission server and provided remote server.

I submitted my code (to submission server) total 6 times and the thread sanitizer test for `growable_array` has always passed.

But in the provided server (accessing with vscode), it always results in data race error.

I'm pretty sure my remote server has somewhat gone wrong, so is there any way to initialize everything and configure the same setting as the submission server?

**Comment by tomtomjhj** [comment]
> But in the provided server (accessing with vscode), it always results in data race error.

Can you share the error message? If the error is related to crossbeam-epoch, then `suppress_tsan.txt` might be missing.

> I'm pretty sure my remote server has somewhat gone wrong, so is there any way to initialize everything and configure the same setting as the submission server?

Make a fresh clone of this repository and copy & paste your solution there. This is basically how the grading server works.

**Comment by AnHaechan** [comment]
'''
test stress_concurrent ... ==================
WARNING: ThreadSanitizer: data race (pid=3975373)
  Read of size 8 at 0x7b0400002380 by thread T7:
    #0 core::clone::impls::_$LT$impl$u20$core..clone..Clone$u20$for$u20$usize$GT$::clone::hbcb7370ef9220fdb /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/clone.rs:182:25 (growable_array-ff452807633824e2+0x9cb97)
    #1 _$LT$cs492_concur_homework..map..NonblockingConcurrentMap$LT$K$C$V$C$M$GT$$u20$as$u20$cs492_concur_homework..map..ConcurrentMap$LT$K$C$V$GT$$GT$::delete::_$u7b$$u7b$closure$u7d$$u7d$::h8e3ad5cdc9199c60 /home/s20180368/cs492-concur/homework/src/map.rs:141:47 (growable_array-ff452807633824e2+0xcfa47)
    #2 core::result::Result$LT$T$C$E$GT$::map::h4b257afc0c3dc28e /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/result.rs:508:25 (growable_array-ff452807633824e2+0xded8e)
    #3 _$LT$cs492_concur_homework..map..NonblockingConcurrentMap$LT$K$C$V$C$M$GT$$u20$as$u20$cs492_concur_homework..map..ConcurrentMap$LT$K$C$V$GT$$GT$::delete::h2c9da0a19836f5f0 /home/s20180368/cs492-concur/homework/src/map.rs:141:9 (growable_array-ff452807633824e2+0xcf9db)
    #4 growable_array::map::stress_concurrent::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h074c034235ff44b7 /home/s20180368/cs492-concur/homework/tests/map/mod.rs:175:37 (growable_array-ff452807633824e2+0xadc4c)
    #5 crossbeam_utils::thread::ScopedThreadBuilder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hb7b48fba4e9a5e26 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:439:31 (growable_array-ff452807633824e2+0xb463b)
    #6 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hbcdf1dccc6a92133 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x956d7)
    #7 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h1fd84798961540dd /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9 (growable_array-ff452807633824e2+0x12213b)
    #8 crossbeam_utils::thread::ScopedThreadBuilder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h65b435f8774ac066 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:451:44 (growable_array-ff452807633824e2+0xb44fd)
    #9 std::sys_common::backtrace::__rust_begin_short_backtrace::h1eb635ca564fb8bc /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:125:18 (growable_array-ff452807633824e2+0xafc49)
    #10 std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42fa29ca29ac3a88 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/thread/mod.rs:474:17 (growable_array-ff452807633824e2+0xb2819)
    #11 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h1356025622fc9e24 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:322:9 (growable_array-ff452807633824e2+0xbfe59)
    #12 std::panicking::try::do_call::h7a11f0cac5c83e77 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:379:40 (growable_array-ff452807633824e2+0xbbf7a)
    #13 __rust_try <null> (growable_array-ff452807633824e2+0xbc53b)
    #14 std::panicking::try::had33c0d67fa3caa7 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:343:19 (growable_array-ff452807633824e2+0xbbc68)
    #15 std::panic::catch_unwind::h103bd65c0afa3829 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:396:14 (growable_array-ff452807633824e2+0xc00b9)
    #16 std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h7f821d619c679afa /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/thread/mod.rs:473:30 (growable_array-ff452807633824e2+0xb21f1)
    #17 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hc5d4f41749188248 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x95727)
    #18 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::hea1090dbdcecbf5a /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9 (growable_array-ff452807633824e2+0x1ecfc9)
    #19 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h8d5723d3912bd325 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9 (growable_array-ff452807633824e2+0x1ecfc9)
    #20 std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys/unix/thread.rs:71:17 (growable_array-ff452807633824e2+0x1ecfc9)

  Previous write of size 8 at 0x7b0400002380 by thread T5:
    [failed to restore the stack]

  Location is heap block of size 16 at 0x7b0400002380 allocated by thread T5:
    #0 malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:652:5 (growable_array-ff452807633824e2+0x206b4)
    #1 alloc::alloc::alloc::hcaaa4517c3d7d53a /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/alloc.rs:86:14 (growable_array-ff452807633824e2+0xcf024)
    #2 alloc::alloc::Global::alloc_impl::h079e72e1f11e81fa /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/alloc.rs:166:73 (growable_array-ff452807633824e2+0xcf18d)
    #3 _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::hd670c44094e79e31 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/alloc.rs:226:9 (growable_array-ff452807633824e2+0xcf56e)
    #4 alloc::alloc::exchange_malloc::h0a301bd4689b2538 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/alloc.rs:316:11 (growable_array-ff452807633824e2+0xcef15)
    #5 alloc::boxed::Box$LT$T$GT$::new::hb89f7a900ef4c094 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:186:9 (growable_array-ff452807633824e2+0xba80f)
    #6 _$LT$T$u20$as$u20$crossbeam_epoch..atomic..Pointable$GT$::init::hbfab91de1d27e354 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.1/src/atomic.rs:188:23 (growable_array-ff452807633824e2+0xba80f)
    #7 crossbeam_epoch::atomic::Owned$LT$T$GT$::init::hf1658966ff49d3a7 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.1/src/atomic.rs:861:35 (growable_array-ff452807633824e2+0xb8ffd)
    #8 crossbeam_epoch::atomic::Owned$LT$T$GT$::new::h65031970b22db040 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.1/src/atomic.rs:846:9 (growable_array-ff452807633824e2+0xb8e24)
    #9 _$LT$growable_array..ArrayMap$LT$V$GT$$u20$as$u20$cs492_concur_homework..map..NonblockingMap$LT$u32$C$V$GT$$GT$::insert::hce5833d4d5f10510 /home/s20180368/cs492-concur/homework/tests/growable_array.rs:26:20 (growable_array-ff452807633824e2+0xbab95)
    #10 _$LT$cs492_concur_homework..map..NonblockingConcurrentMap$LT$K$C$V$C$M$GT$$u20$as$u20$cs492_concur_homework..map..ConcurrentMap$LT$K$C$V$GT$$GT$::insert::h8ea59cf49fcd4298 /home/s20180368/cs492-concur/homework/src/map.rs:137:9 (growable_array-ff452807633824e2+0xcfadc)
    #11 growable_array::map::stress_concurrent::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h074c034235ff44b7 /home/s20180368/cs492-concur/homework/tests/map/mod.rs:171:37 (growable_array-ff452807633824e2+0xadbc6)
    #12 crossbeam_utils::thread::ScopedThreadBuilder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hb7b48fba4e9a5e26 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:439:31 (growable_array-ff452807633824e2+0xb463b)
    #13 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hbcdf1dccc6a92133 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x956d7)
    #14 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h1fd84798961540dd /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9 (growable_array-ff452807633824e2+0x12213b)
    #15 crossbeam_utils::thread::ScopedThreadBuilder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h65b435f8774ac066 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:451:44 (growable_array-ff452807633824e2+0xb44fd)
    #16 std::sys_common::backtrace::__rust_begin_short_backtrace::h1eb635ca564fb8bc /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:125:18 (growable_array-ff452807633824e2+0xafc49)
    #17 std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42fa29ca29ac3a88 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/thread/mod.rs:474:17 (growable_array-ff452807633824e2+0xb2819)
    #18 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h1356025622fc9e24 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:322:9 (growable_array-ff452807633824e2+0xbfe59)
    #19 std::panicking::try::do_call::h7a11f0cac5c83e77 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:379:40 (growable_array-ff452807633824e2+0xbbf7a)
    #20 __rust_try <null> (growable_array-ff452807633824e2+0xbc53b)
    #21 std::panicking::try::had33c0d67fa3caa7 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:343:19 (growable_array-ff452807633824e2+0xbbc68)
    #22 std::panic::catch_unwind::h103bd65c0afa3829 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:396:14 (growable_array-ff452807633824e2+0xc00b9)
    #23 std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h7f821d619c679afa /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/thread/mod.rs:473:30 (growable_array-ff452807633824e2+0xb21f1)
    #24 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hc5d4f41749188248 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x95727)
    #25 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::hea1090dbdcecbf5a /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9 (growable_array-ff452807633824e2+0x1ecfc9)
    #26 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h8d5723d3912bd325 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9 (growable_array-ff452807633824e2+0x1ecfc9)
    #27 std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys/unix/thread.rs:71:17 (growable_array-ff452807633824e2+0x1ecfc9)

  Thread T7 (tid=3975387, running) created by main thread at:
    #0 pthread_create /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:966:3 (growable_array-ff452807633824e2+0x21c6b)
    #1 std::sys::unix::thread::Thread::new::h0ad85e32e78fc1a8 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys/unix/thread.rs:50:19 (growable_array-ff452807633824e2+0x1ecce1)
    #2 std::thread::Builder::spawn::h0d0ab046ccddca31 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/thread/mod.rs:381:18 (growable_array-ff452807633824e2+0xb2953)
    #3 crossbeam_utils::thread::ScopedThreadBuilder::spawn::h5e5ead7ca451a7b1 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:451:17 (growable_array-ff452807633824e2+0xb3084)
    #4 crossbeam_utils::thread::Scope::spawn::he0b86b7400eba0cd /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:253:9 (growable_array-ff452807633824e2+0xb4dbd)
    #5 growable_array::map::stress_concurrent::_$u7b$$u7b$closure$u7d$$u7d$::hdd86c216268251ce /home/s20180368/cs492-concur/homework/tests/map/mod.rs:158:13 (growable_array-ff452807633824e2+0xadefb)
    #6 crossbeam_utils::thread::scope::_$u7b$$u7b$closure$u7d$$u7d$::h0599adc17b8763f5 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:162:65 (growable_array-ff452807633824e2+0xb5de4)
    #7 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::he471eea2622090ee /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:322:9 (growable_array-ff452807633824e2+0xbffd0)
    #8 std::panicking::try::do_call::h28a92b9dd6c4475b /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:379:40 (growable_array-ff452807633824e2+0xbbd9e)
    #9 __rust_try <null> (growable_array-ff452807633824e2+0xbc53b)
    #10 std::panicking::try::h4bc4a8420a838bb5 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:343:19 (growable_array-ff452807633824e2+0xbbae7)
    #11 std::panic::catch_unwind::h490f71b7408fc479 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:396:14 (growable_array-ff452807633824e2+0xc01d0)
    #12 crossbeam_utils::thread::scope::he76191ff93209bde /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:162:18 (growable_array-ff452807633824e2+0xb5801)
    #13 growable_array::map::stress_concurrent::h5d044d70750b35a7 /home/s20180368/cs492-concur/homework/tests/map/mod.rs:156:5 (growable_array-ff452807633824e2+0xad70f)
    #14 growable_array::stress_concurrent::h456675afc488f467 /home/s20180368/cs492-concur/homework/tests/growable_array.rs:141:5 (growable_array-ff452807633824e2+0xa008c)
    #15 growable_array::stress_concurrent::_$u7b$$u7b$closure$u7d$$u7d$::h1200835c7e35dc0c /home/s20180368/cs492-concur/homework/tests/growable_array.rs:138:1 (growable_array-ff452807633824e2+0xbb514)
    #16 core::ops::function::FnOnce::call_once::hfc2225f37d2ac68b /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x95927)
    #17 core::ops::function::FnOnce::call_once::hb4968dd9be522dff /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x10bf12)
    #18 test::__rust_begin_short_backtrace::ha2276ea1d26c2ad9 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/test/src/lib.rs:516:5 (growable_array-ff452807633824e2+0x10bf12)
    #19 core::ops::function::FnOnce::call_once::ha96638096d2f99fc /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x95861)
    #20 std::sys_common::backtrace::__rust_begin_short_backtrace::h8b07da8f48504691 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:125:18 (growable_array-ff452807633824e2+0xafcd7)
    #21 std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h322ca6f4463ee4f6 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/rt.rs:66:18 (growable_array-ff452807633824e2+0xd0b84)
    #22 core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::h54c39b9b8451875a /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:259:13 (growable_array-ff452807633824e2+0x1e7706)
    #23 std::panicking::try::do_call::hcdfba51a06e21b42 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:379:40 (growable_array-ff452807633824e2+0x1e7706)
    #24 std::panicking::try::h77386c66889b2066 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:343:19 (growable_array-ff452807633824e2+0x1e7706)
    #25 std::panic::catch_unwind::hc55a0d8aadca44f0 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:396:14 (growable_array-ff452807633824e2+0x1e7706)
    #26 std::rt::lang_start_internal::h97dca9624db2aa85 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/rt.rs:51:25 (growable_array-ff452807633824e2+0x1e7706)
    #27 main <null> (growable_array-ff452807633824e2+0xa01aa)

  Thread T5 (tid=3975381, running) created by main thread at:
    #0 pthread_create /rustc/llvm/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:966:3 (growable_array-ff452807633824e2+0x21c6b)
    #1 std::sys::unix::thread::Thread::new::h0ad85e32e78fc1a8 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys/unix/thread.rs:50:19 (growable_array-ff452807633824e2+0x1ecce1)
    #2 std::thread::Builder::spawn::h0d0ab046ccddca31 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/thread/mod.rs:381:18 (growable_array-ff452807633824e2+0xb2953)
    #3 crossbeam_utils::thread::ScopedThreadBuilder::spawn::h5e5ead7ca451a7b1 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:451:17 (growable_array-ff452807633824e2+0xb3084)
    #4 crossbeam_utils::thread::Scope::spawn::he0b86b7400eba0cd /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:253:9 (growable_array-ff452807633824e2+0xb4dbd)
    #5 growable_array::map::stress_concurrent::_$u7b$$u7b$closure$u7d$$u7d$::hdd86c216268251ce /home/s20180368/cs492-concur/homework/tests/map/mod.rs:158:13 (growable_array-ff452807633824e2+0xadefb)
    #6 crossbeam_utils::thread::scope::_$u7b$$u7b$closure$u7d$$u7d$::h0599adc17b8763f5 /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:162:65 (growable_array-ff452807633824e2+0xb5de4)
    #7 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::he471eea2622090ee /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:322:9 (growable_array-ff452807633824e2+0xbffd0)
    #8 std::panicking::try::do_call::h28a92b9dd6c4475b /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:379:40 (growable_array-ff452807633824e2+0xbbd9e)
    #9 __rust_try <null> (growable_array-ff452807633824e2+0xbc53b)
    #10 std::panicking::try::h4bc4a8420a838bb5 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:343:19 (growable_array-ff452807633824e2+0xbbae7)
    #11 std::panic::catch_unwind::h490f71b7408fc479 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:396:14 (growable_array-ff452807633824e2+0xc01d0)
    #12 crossbeam_utils::thread::scope::he76191ff93209bde /home/s20180368/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.1/src/thread.rs:162:18 (growable_array-ff452807633824e2+0xb5801)
    #13 growable_array::map::stress_concurrent::h5d044d70750b35a7 /home/s20180368/cs492-concur/homework/tests/map/mod.rs:156:5 (growable_array-ff452807633824e2+0xad70f)
    #14 growable_array::stress_concurrent::h456675afc488f467 /home/s20180368/cs492-concur/homework/tests/growable_array.rs:141:5 (growable_array-ff452807633824e2+0xa008c)
    #15 growable_array::stress_concurrent::_$u7b$$u7b$closure$u7d$$u7d$::h1200835c7e35dc0c /home/s20180368/cs492-concur/homework/tests/growable_array.rs:138:1 (growable_array-ff452807633824e2+0xbb514)
    #16 core::ops::function::FnOnce::call_once::hfc2225f37d2ac68b /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x95927)
    #17 core::ops::function::FnOnce::call_once::hb4968dd9be522dff /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x10bf12)
    #18 test::__rust_begin_short_backtrace::ha2276ea1d26c2ad9 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/test/src/lib.rs:516:5 (growable_array-ff452807633824e2+0x10bf12)
    #19 core::ops::function::FnOnce::call_once::ha96638096d2f99fc /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:227:5 (growable_array-ff452807633824e2+0x95861)
    #20 std::sys_common::backtrace::__rust_begin_short_backtrace::h8b07da8f48504691 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:125:18 (growable_array-ff452807633824e2+0xafcd7)
    #21 std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h322ca6f4463ee4f6 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/rt.rs:66:18 (growable_array-ff452807633824e2+0xd0b84)
    #22 core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::h54c39b9b8451875a /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/ops/function.rs:259:13 (growable_array-ff452807633824e2+0x1e7706)
    #23 std::panicking::try::do_call::hcdfba51a06e21b42 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:379:40 (growable_array-ff452807633824e2+0x1e7706)
    #24 std::panicking::try::h77386c66889b2066 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:343:19 (growable_array-ff452807633824e2+0x1e7706)
    #25 std::panic::catch_unwind::hc55a0d8aadca44f0 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panic.rs:396:14 (growable_array-ff452807633824e2+0x1e7706)
    #26 std::rt::lang_start_internal::h97dca9624db2aa85 /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/rt.rs:51:25 (growable_array-ff452807633824e2+0x1e7706)
    #27 main <null> (growable_array-ff452807633824e2+0xa01aa)

SUMMARY: ThreadSanitizer: data race /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/clone.rs:182:25 in core::clone::impls::_$LT$impl$u20$core..clone..Clone$u20$for$u20$usize$GT$::clone::hbcb7370ef9220fdb
==================
ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.61s

ThreadSanitizer: reported 1 warnings
error: test failed, to rerun pass '--test growable_array'
'''

**Comment by AnHaechan** [comment]
+ The results are consistent to submission server after forking a new repository.  Thanks.
(I hope others don't spend a day with this problem.. TT)
