### ISSUE TITLE
[Homework] Is the website homework score our final score?

### ISSUE THREAD

**Issue by ellaide** [kaist-cp/cs492-concur#316]
Do we get for homework the maximum of our submissions in the website? Or are you going to go over multiple iterations of our submissions? I am afraid that some testcases might unexpectedly fail on nth iteration.

**Comment by YujinGaya** [comment]
> only the last submission counts. Please make sure the last line of the "log" says "Score: / 100".

https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-696736049

Might be related to this

**Comment by jeehoonkang** [comment]
@YujinGaya is right about this.
