### ISSUE TITLE
[Question] HW6 Can I get a hint with alloc()?

### ISSUE THREAD

**Issue by ssoymikey** [kaist-cp/cs492-concur#317]
I'm very confused by concept of bitmap, and I understood that it is related with memory allocation. However, I cannot figure out how to search empty slot with U8,,, especially in alloc(). May I ask you any advice to implement it? I'm very frustrated because it is very first step of HW6, but I cannot start it at all ㅠㅠ

**Comment by tomtomjhj** [comment]
`(!00000000).trailing_zeros() == 0`
`(!00000001).trailing_zeros() == 1`
...

**Comment by ssoymikey** [comment]
thank you!!
