### ISSUE TITLE
[Question] HW6 LocalHazardsIter

### ISSUE THREAD

**Issue by ssoymikey** [kaist-cp/cs492-concur#318]
Should next() return all the elements of hazard pointer? Or does it have to return only elements not in use? I'm little bit confused implementing LocalHazardsIter.

**Comment by tomtomjhj** [comment]
if `occupied == 00000101` when `LocalHazardsIter` is created, then 
1. `next() == Some(element[0])`
2. `next() == Some(element[2])` 
3. `next() == None`
4. ...

**Comment by ssoymikey** [comment]
Thank you!
