### ISSUE TITLE
[HW6] get_protected_collect_sync

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#319]
In that test case, my codes go into loop and, it doesn't finish.

I don't understand which condition is needed for passing that test case.

In my program, the test check again and again, and because shield is null, it always pass assertion. 
```rust
if !shield.is_null() {
    // safe to deref a valid pointer via a validated shield
    !(unsafe { *shield.deref() }, 123);   <==== here
}
```

Well, another test cases such as `protected_collect_sync` and `shield_drop_all_hazards_sync` work. But I don't know why only `get_protected` doesn't work, even though validation seems to work well.

**Comment by tomtomjhj** [comment]
If you implemented `get_protected` correctly, there must be a loop. Try this:
```rust
pub fn get_protected<T>(atomic: &Atomic<T>) -> Option<Shield<'static, T>> {
    // ..
    loop {
        // ...
        // add these lines at the end of the loop 
        #[cfg(feature = "check-loom")]
        loom::sync::atomic::spin_loop_hint();
    }
}
```

This tells loom that there is a busy loop that can lead to an infinite loop.
I didn't mention this in the documentation because our solution didn't require this to pass the test.

**Comment by Jaegoomon** [comment]
Holy moly..... Thank you...
