### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#32]
- You can see your scores here: https://gg.kaist.ac.kr/course/2/
- Your attendance score is the number of tokens you input.
- ~Your midterm exam score will be input by December 11th.~
- ~Your final exam score will be input by December 18th.~
- Your homework 1 score will be input by December ~20th~ 23th.
- Your homework 2/3 scores will be input by December 26th.
- You can claim on scores (TBA).

**Comment by Shynar88** [comment]
Even though attendance for today's lecture is 'yes', the total count of attendance wasn't updated.  Could you, please, update the attendance scores? Thank you!

**Comment by jeehoonkang** [comment]
- The attendance score is updated.
- I finished marking the midterm exam.  I'll upload the scores soon.

**Comment by jeehoonkang** [comment]
I uploaded the midterm scores: https://gg.kaist.ac.kr/course/2/

**Comment by jeehoonkang** [comment]
You can claim on attendance and midterm scores tomorrow (12/13), 10am-11am and 1pm-2pm, at E3-1, #4433.  If you cannot make the time, please send me an email.

**Comment by wns3645** [comment]
@jeehoonkang Could you also let me know the average/median score?

**Comment by Shynar88** [comment]
Could you, please, also let us know the standard deviation? Thank you!

**Comment by jeehoonkang** [comment]
@wns3645 @Shynar88 midterm's mean = 71.125, stdev = 9.351.

Here's the histogram: https://docs.google.com/spreadsheets/d/e/2PACX-1vTDQOfktv97Ybg-nm0BRP8MCo3y2spJ1E2c14MIG_BO5dws2T8dy2bjM3ZZnx25jNpdgfyEVXGiWrbz/pubchart?oid=174373468&format=interactive

**Comment by Shynar88** [comment]
Could you, please, tell when our midterm scores will be updated in the system?

**Comment by jeehoonkang** [comment]
@Shynar88 I'll update the midterm scores after marking and uploading final scores.

**Comment by jeehoonkang** [comment]
@Shynar88 I updated the midterm scores at gg.

**Comment by Shynar88** [comment]
Is the maximum score for Final 100 or 105?

**Comment by jeehoonkang** [comment]
@Shynar88 It's those who scored 100-105.

**Comment by kunduzb17** [comment]
@jeehoonkang Have you finished grading homework 1 ? I still have 0 points for it, however my code passed 4 testcases.

**Comment by jeehoonkang** [comment]
@kunduzb17 I sent you an email.

**Comment by jeehoonkang** [comment]
You can claim on your homework 2019/12/30 (Monday) 1-5pm at E3-1 #4433.

**Comment by jeehoonkang** [comment]
- I'm sorry to inform you that I'll be busy until 1:30pm.  I'll be at the office at 1:30-5pm.  Sorry.
- If you cannot come to my office, please send me an email.
