### ISSUE TITLE
[Question] HW#5 growable array, log_concurrent case

### ISSUE THREAD

**Issue by us0310306** [kaist-cp/cs492-concur#320]
I fixed some bugs makes address 0 that I asked.
Thank you for the answering.
However, I get problem with log_concurrent case.
When I test smoke, stress_sequential, stress_concurrent test cases, they success that there are no memory leaks or any other error.
Log_concurrent makes error like this.
```
thread 'log_concurrent' panicked at 'assertion failed: inserts.contains_key(v)', tests/map/mod.rs:218:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test log_concurrent ... FAILED

failures:

failures:
    log_concurrent

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out
```

What can be the problem when I fail only log_concurrent?

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/286#issuecomment-743224368
https://github.com/kaist-cp/cs492-concur/issues/278#issuecomment-742673251

**Comment by us0310306** [comment]
Thank you for answering.
I missed that comments.
I changed `compare_and_swap` to `compare_exchange` after read them, but it still fails...
I used `compare_and_set` when I change the `self.root`.
I used `compare_exchange` when I change `AtomicUsize` of segment.
Is there any other reason that can make this kind of problem?

**Comment by us0310306** [comment]
Can you give me some advice about this problem?
I lost the way...

**Comment by zhanto97** [comment]
Most of the problems with `log_concurrent` is because of incorrect key insertion into hash map. Are you tagging ordinary keys? Are you reversing keys? For example, in the book, implementation ignores most significant **byte** of key. But, in our case, it must be done.

**Comment by us0310306** [comment]
Thank you for answering.
Should I use reversing keys in growable array, too?
For example, if `SEGMENT_LOGSIZE = 3` then 
`list.insert(&6, 1, &guard); // height : 1`
`list.insert(&8, 1, &guard); // height : 2`
`list.lookup(&6, &guard); // height : 2`  is this None?

**Comment by us0310306** [comment]
I used reversing keys that for example, if key is 0b001, it will get 0b100.
I also tried not reversing keys.
Therefore, reversing keys is not problem I think.
What do you mean tagging ordinary keys in growable array?

**Comment by us0310306** [comment]
Oh, i found what I did wrong.
I had problem with key.
Thank you very much for answers!

**Comment by Lee-Janggun** [comment]
I have similar problem. Can you give me a hint on what was wrong with your key?

**Comment by us0310306** [comment]
Well, I'm not sure that my case is same to your case.
My case, 0 key made problem.
For example, when SEGMENT_LOGSIZE = 3,
key is 0b001000111
middle 000 made problem for me.

**Comment by Lee-Janggun** [comment]
I think that my current implementation avoids that :(. Thanks anyway!
