### ISSUE TITLE
[Question] HW stress_concurrent timeout

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#321]
I am currently experiencing occasional timeout in `stress_concurrent`, but do not see why. After some abusive use of print, I found the for some reason my `get()` seems to be able to return successfully, but the program just gets into a deadlock after that. I even tried to modify the `map::stress_concurrent` mention to get some print results and it seems that the map was able to get a result as well. So I am currently very confused, and the fact that it only happens occasionally makes it very hard to debug. The only other thing I know is that the returned value before a deadlock is a null pointer, but I that did not help much. Did anyone have similar problem, and if so, any help?

**Comment by Lee-Janggun** [comment]
I think my logic about CAS fail case may be incorrect... my current logic is that if we are trying CAS a newly made segment to `Atomic<Segment>` and fail, it is ok because it means that another thread has made a new segment for us, so we can just continue. I thought this was logical was with logically deleted nodes. However this feels wrong, but I cannot think of why.

**Comment by tomtomjhj** [comment]
> deadlock

?? Maybe there's an infinite loop somewhere in your code. Put a `println!` at the start of the loop and try to find the infinite loop condition.

**Comment by Lee-Janggun** [comment]
I already tired that. But not sure if (a) the terminal is exhaustive, (b) If (a) is not the case, my loops seems to be able to reach its end.

**Comment by tomtomjhj** [comment]
(a) try `--nocapture`?
<pre>cargo test <strong>-- --nocapture</strong></pre>

(b) loop in `drop`?

**Comment by Lee-Janggun** [comment]
(a) Tried that. Not much help.

(b) drop did not start. I had a println at the start of drop as well.

**Comment by Lee-Janggun** [comment]
I was not considering the case when `index = 0`, and was shifting it left blindly.
