### ISSUE TITLE
[Question] HW5 split_ordered_list initialize_bucket

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#322]
I implemented initialize_bucket by using the flow in book and paper.
When I increase size of the buckets and insert a new bucket, it is inserted in wrong position and I don't know why. (working for hours...)

1. get parent
2. handle bucket_index == parent(which is 0)
3. `let parent_slot = self.buckets.get(parent);`, and `let mut parent_bucket = parent_slot.load(Ordering::SeqCst, guard);` 
4. if load is null, initialize parent and load parent_bucket again
5. make a node with key: dummy_key(bucket_index), value: None
6. initialize parent_cursor, `let mut parent_cursor = unsafe { Cursor::from_raw(parent_slot as *const _, parent_bucket.as_raw()) };`
7. parent_cursor.find_harris_herlihy_shavit(dummy_key(bucket_index))
8. If not found, insert the node.

I am wondering if 6~8 steps have problems.(maybe using cursor wrongly) Can you give me some helpful advice? @tomtomjhj

**Comment by tomtomjhj** [comment]
Does your implementation pass `stress_sequential` test?

> if load is null, initialize parent and load parent_bucket again

Can you elaborate? There should be a recursive call to `lookup_bucket`

> parent_cursor.find_harris_herlihy_shavit(dummy_key(bucket_index))

Please use `find_harris_michael` or `find_harris`. There's a very tricky issue in `find_harris_herlihy_shavit` when it's used for insertion and deletion, which prof didn't mention in the lecture.

**Comment by saltylight** [comment]
@tomtomjhj This is detailed code. I do this in `initialize_bucket` function. I only call `initialize_bucket` once in `lookup_bucket` and call `initialize_bucket` recursively in `initialize_bucket`
```
let parent_slot = self.buckets.get(parent, guard);
let mut parent_bucket = parent_slot.load(Ordering::SeqCst, guard);

if parent_bucket.is_null()  {
      // we need to initialize parent bucket first
      self.initialize_bucket(parent, guard);
      parent_bucket = parent_slot.load(Ordering::SeqCst, guard);
}
```

I removed all `harris_herlihy_shavit` but still fails.
I didn't pass `stress_sequential`. I added new failing case for my implementation and it is below code.
```
    assert_eq!(list.insert(&8, 8, &guard), Ok(())); // success
    assert_eq!(list.insert(&9, 9, &guard), Ok(())); // success
    assert_eq!(list.insert(&13, 13, &guard), Ok(())); // success
    assert_eq!(list.insert(&7, 7, &guard), Ok(())); // success
    assert_eq!(list.insert(&10, 10, &guard), Ok(())); // success (size grows after this.)

    assert_eq!(list.lookup(&8, &guard), Some(&8)); // success
    assert_eq!(list.lookup(&9, &guard), Some(&9)); // success
    assert_eq!(list.lookup(&13, &guard), Some(&13)); // success
    assert_eq!(list.lookup(&10, &guard), Some(&10)); // fail. This inserts bucket with index 2 but doesn't finds &10.
```
🤔

**Comment by saltylight** [comment]
I am still stuck... Can you give me 15 minutes of hangout code review time? 😭 @tomtomjhj

**Comment by tomtomjhj** [comment]
I'm sorry for not being able to help your last effort. For bugs that can be reproduced consistently in single-threaded cases, using a debugger would be very helpful. I'm closing this issue but please feel free to email me for further discussion.
