### ISSUE TITLE
[Question] HW5 Growable Array stress_sequential fails

### ISSUE THREAD

**Issue by 16ypark** [kaist-cp/cs492-concur#328]
stress_sequential test fails with assertion failure, such that using my implementation returns Some(...) while it should return None, and vice versa. I printed out with which indices each segments are accessed, and verified by hand that they are correctly done for all cases (at least from what I can observe). 

Below is an example in which a value inserted to index 537011234 shows up when accessing index 604128290, which should be non-existing. The lines with only numbers show index that was used to access segment at the time.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/46183687/102805689-f2d91800-43fe-11eb-99c0-06f83d14945e.png">

<img width="533" alt="image" src="https://user-images.githubusercontent.com/46183687/102805650-e3f26580-43fe-11eb-9815-beb87fe39726.png">

Could you help me figure out what the problem possibly is?

**Comment by Lee-Janggun** [comment]
For me, when this happened it was that I was storing the pointer at the 0th index of segments all the time by mistake.
