### ISSUE TITLE
[Question] HW5 log_concurrent for growable array

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#329]
I have no idea what I am doing wrong. In #320 it said to check my `index` usage if this continuously fails, and the author said that their problem was when there was a  `SEGMENT_LOGSIZE` local index. I checked my code and this is not the case. The only modification I do to my `index` is after I made it go down appropriate level, I shift it right `SEGMENT_LOGSIZE` times, and I perform `&` with `(1 <<SEGMENT_LOGSIZE) - 1` to get the index at certain level. Other then that `index` is untouched, so I am confused on where I could have made a mistake. Any tips?

**Comment by Lee-Janggun** [comment]
Closing as I gave up.

**Comment by totolacky** [comment]
Try running stress_sequential with large STEPS. The test may pass even for incorrect implementation, as STEPS=4096 as default (which is quite small). If there is no issue in synchronization, this may give some intuition on the error in the parts other than synchronization.

**Comment by Jaechan-So** [comment]
Some quick tips: (not sure for your case but what I had considered)

* Some pre-following bits for additional height (e.g. 0b**000**111001 as height grows)
* CAS handling for self.root

These are what I had found when I was managing growable_array, regardless of your circumstances..

**Comment by Lee-Janggun** [comment]
> Try running stress_sequential with large STEPS. The test may pass even for incorrect implementation, as STEPS=4096 as default (which is quite small). If there is no issue in synchronization, this may give some intuition on the error in the parts other than synchronization.

This was the issue, which unfortunately means that I probably cannot do it in couple of minutes. Still, thanks for letting me know.
