### ISSUE TITLE
[Question] HW6 double free detected in tcache 2

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#331]
When I trying to run test cases, I kept on getting double free error. I think the issue is that two threads have retired pointers pointing to the same memory, and are both called on collect. This seems like natural behavior though, and I am not sure how to deal with this. Any tips?

**Comment by tomtomjhj** [comment]
Yeah, so a pointer must not be retired more than once. The test cases don't do double-retire if the implementation of the hazard pointer is correct.

**Comment by Lee-Janggun** [comment]
In order to avoid this I tired to only add to the retired list when the pointer is not null, but this didn't work as the pointer may have been retired but not yet freed. Should I try tagging?

**Comment by tomtomjhj** [comment]
I believe there's something wrong in your `get_protected`.

**Comment by Lee-Janggun** [comment]
In my `get_protected`, 

1. Get thread id and localhazard
2. loop to get shield and verify. If verification succeeds, escape with Some. If not, drop shield and continue. If None is returned for shield, I return none.

Do I also tag here? But then What should I with `count_tag`?

**Comment by Lee-Janggun** [comment]
I have double free error even in `protect_collect_sync`, where `get_protected` is not used. Could it be that my `validate` is incorrect?

**Comment by Lee-Janggun** [comment]
#326

**Comment by Jaechan-So** [comment]
What was your problem? As you referred to #326: the alignment was a problem? I've stucked double free problem but I cannot find the reason :(

**Comment by Lee-Janggun** [comment]
Sorry for the late reply, I didn't get rid of the tag in `retire` with using alignment.

**Comment by Jaechan-So** [comment]
@Lee-Janggun Thank you! Interestingly my problem was that I didn't check whether the pointer is null or not in `retire()`, following your comment:


> In order to avoid this I tired to only add to the retired list when the pointer is not null, but this didn't work as the pointer may have been retired but not yet freed. Should I try tagging?
> 
> @tomtomjhj I realized we are working with shared so we cannot CAS to change the tag. Any other hints?

**Comment by Lee-Janggun** [comment]
Glad I can help. If you managed to do HW5, any last minute tips on #329?
