### ISSUE TITLE
For those who are running their homework in their local Mac machine.

### ISSUE THREAD

**Issue by poppindouble** [kaist-cp/cs492-concur#338]
If you are doing your homework in your local Mac machine and need to run the grading scripts, there are some modifications you might need to do:

1. `brew install coreutils`, In the `./scripts/` in homework folder, you need to change the `timeout` into `gtimeout`.
2.  In the `grage-utils.sh`, change the target from `x86_64-unknown-linux-gnu` into `x86_64-apple-darwin`
3.  `rustup update`

Also remember to change the target when you run test cases with LLVM sanitizers enabled.

**Comment by jeehoonkang** [comment]
Thank you for the information!  But we'd like to support Ubuntu Linux only to reduce the maintenance burden...

Closing, but I'll make sure students can search for this issue later.
