### ISSUE TITLE
[Question]How to use RWLock in cache.rs(assignment 1)

### ISSUE THREAD

**Issue by poppindouble** [kaist-cp/cs492-concur#339]
Hello guys:

In assignment 1, we need to implement `get_or_insert_with` and its associate data structure `inner`. But I only used `Mutex` and `Option` in the `inner` data structure. I am wondering if the `RWLock` is necessary or not? I mean for sure I can use the write lock in `RWLock` as a `Mutex`, but is there a better way to implemented `get_or_insert_with`  with `RWLock`?

Here is the idea how I implemented it:

1. `Arc`, we need this to make our `inner` sharable, since multi-threads are accessing it.
2. `Mutex`, sometimes we only allow one single thread to access the current data structure.
3. `Option<V>`, I use `Option` type to distinguished if the current key's corresponding value is being calculated. since for the same key, we only execute the `f` for once.

When multi-threads are accessing the `Cache`, I only allow one thread to access the `HashMap` beneath it, if the key is in the `HashMap` and the value of it is `Some()`, then the thread knows this value was calculated before and directly return the value in `Some`.

if the value is `None`, then it means there is another thread working on the current value, so the thread needs to drop the lock and go for looping and fighting for the next chance to access the `HashMap`.

If the key is not in the `HashMap`, the thread knows he is the first one visiting this key in the `HashMap`, so the thread will set the value to `None`, release the lock(So other threads have a chance to insert other key-value pairs, no blocking on insertion), and do the computation. After the computation, this thread will fight for the lock again and write the new value to the `HashMap`.

So anyone have a better solution by using `RWLock`? Different ideas are welcomed!

**Comment by Lee-Janggun** [comment]
`RWLock` is used as one wishes for multiple reads to the hash map non-blocking.  I think that if you use only `Mutex` as the outermost lock, the hash map cannot have this property.

**Comment by poppindouble** [comment]
Ah, I see! 
So I guess you mean change the outer most lock from `Mutex` into `RWLock`. So when there is no other writer, multi-thread should be able to read the `HashMap` concurrently, right?
Then we need to be careful about when should we drop the read lock and write lock.
@Lee-Janggun

**Comment by poppindouble** [comment]
Hmm, interesting, actually I removed the `Mutex` completely, I use `RWLock` in the outer most of the `HashMap`, I am not sure we still need `Mutex` any more. Here is what I did:

1. We allowed multi-thread reading the `HashMap`(read lock)
2. When we need to write a key value pair, we drop the read lock manually and acquire the write lock.
3. Set None
4. drop write lock manually.
5. computation
6. fight for the write lock again and write the key value pair.

I am not sure do we still need the `Mutex` in this way, with this implementation, I still can get the feature of multiple reads to the hash map non-blocking.

@Lee-Janggun

**Comment by Lee-Janggun** [comment]
Yeah you are right in that this implementation can read more efficiently. The problem is efficiency in inserting. In your current implementation, if thread T1 tries to insert a new key1 and T2 tries to insert new key2, there are two possible fights, in 2 and 6.  Depending on the viewpoint this is ok, but as we expect the hash map to be accessed by many threads, it is inefficient to fight for a lock on such a large data structure twice.  

So how to solve this? The key problem is that after we insert `None`, we need to release the access to none as we want to do computation without blocking, so we are in a dilemma. So a solution will be to find a way to release the read lock the hash map, but still have access on the `None` value. To do this you need `Mutex`.

After reading my first comment, I realized that I wrote it as if you you must use `Mutex` you can use `RWLock`, and I actually think it might be slightly more efficient.

**Comment by poppindouble** [comment]
> So a solution will be to find a way to release the write lock to the hash map, but still have access on the None value.

Sorry I can't quite get this idea, I know it is a bit tricky, can you elaborate a bit more? Thanks! 👍 

If you can write down the bullet point like above, that would be awesome!

**Comment by Lee-Janggun** [comment]
Yeah this part is a bit difficult to get if you don't see the solution, and its also pretty hard to give a further hint without just giving it away. I'll try my best to explain the thought process of it without giving the full detail.

1. Get write lock the map.
2. Make `None` value. Thread T has reference to this `None`.
3. Write `None` value to the map. 
4. Release the write lock, losing access to the written `None` value. You still have reference to a `None`, but not the same.
5. Computation of actual value.
6. Get write lock again.

The key part is noting 4. If the written `None` written in the map is reference by the reference that T has, then we wouldn't need step 6.

**Comment by poppindouble** [comment]
Ah, I see Thanks!! I kind of get the idea, I know it is a bit hard to just describe it without seeing the code. I will try to implement   later. :) @Lee-Janggun
