### ISSUE TITLE
Claim for the midterm and final exams

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#340]
- The midterm and final exam scores are uploaded at https://gg.kaist.ac.kr/course/6/ .

- If you want to claim the scores, please **by 12/25 23:59pm send me an email that at least contains**:
    + your student id and name
    + the problem names you want to claim for (with the order of preferences; e.g., "midterm essay 3 > final essay 2 > final essay 3")

- The actual claim will be done in an online meeting (Google meet), next week.
  The details will be announced as a reply to this issue.

**Comment by totolacky** [comment]
Thanks for the quick grading. Can you also provide us some statistics about the exam? (ex> mean, median, stdev, etc.)

**Comment by jeehoonkang** [comment]
@totolacky 

- Midterm mean/stdev: 47.43835616, 12.45323062
- Final mean/stdev: 44.87323944, 17.19130144

**Comment by j2k0618** [comment]
Would you open the answer for midterm and final? It will be very helpful to decide whether claim or not.

**Comment by jeehoonkang** [comment]
@j2k0618 Sorry, I cannot disclose the answers for all students.  But I'll make sure you can check your answers in online claim sessions.
