### ISSUE TITLE
Dropping MSQueue leaks memory

### ISSUE THREAD

**Issue by drzix** [kaist-cp/cs492-concur#36]
## Situation

- If MSQueue is not empty and becomes dropped, memory leaks occur.

## Example

https://github.com/kaist-cp/cs492-concur/blob/865fa04e6e4baea3c8b467e3637f03092000a0bd/lockfree/src/queue.rs#L201-L203

If these lines are commented, memory leaks are detected from LeakSanitizer command:
`RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --target x86_64-unknown-linux-gnu`

## My adhoc

from this code: 
https://github.com/kaist-cp/cs492-concur/blob/865fa04e6e4baea3c8b467e3637f03092000a0bd/lockfree/src/queue.rs#L136-L148

```rust
use crossbeam_epoch::pin; // ADDED
impl<T> Drop for Queue<T> {
    fn drop(&mut self) {
        unsafe {
            // let guard = unprotected(); // COMMENTED
            let guard = &pin(); // ADDED

            while let Some(_) = self.try_pop(guard) {}

            // Destroy the remaining sentinel node.
            let sentinel = self.head.load(Ordering::Relaxed, guard);
            drop(sentinel.into_owned());
        }
    }
}
```

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/helpdesk/issues/93 ?

**Comment by jeehoonkang** [comment]
As @tomtomjhj suggested, it's a bug in upstream which is now fixed.  Closing
