### ISSUE TITLE
About the best solution in HW

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs492-concur#38]
I want to study Rust programming on these lecture's HWs comparing my answer. Could you upload the best solution(Professor ver.) on github?

**Comment by jeehoonkang** [comment]
Sorry for late response.  I'm sorry I cannot provide my answer (which is defninitely not the "best" :) online.  If you're interested in studying Rust, I suggest you to visit my lab for e.g. a week, if your time permits.
