### ISSUE TITLE
First things you should do

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#42]
- **Please make sure you can log on https://gg.kaist.ac.kr/course/6/ .**
    + Purpose: for submitting homework submissions and attendance tokens.
    + ID: your student number (e.g., 20071163)
    + Password: If you already have an account, the password is not changed.  If not, the initial password is your student number.  Please change it ASAP.
    + Troubleshooting: If you cannot log on, it's probably because you've enrolled late.  I'll add your id soon.

- **Please sign the [honor code](https://gg.kaist.ac.kr/quiz/17/) by September 11th.**
    + Purpose: It is a standardized form from the School of Computing.  Academic integrity is one of the most important values in academia.

- **Please make sure you can log on `ssh s<student-id>@cp-service.kaist.ac.kr -p14000`.**
    + Purpose: homework may require a beefy machine with many cores.  If necessary, use the provided server.
    + ID: `s<student.id>` (e.g., `s20071163`)
    + Password: `1234598765`  WARNING: please change it ASAP.
    + SSH key: I strongly recommend you to register public SSH keys to the server.  See [this tutorial](https://serverpilot.io/docs/how-to-use-ssh-public-key-authentication/) for more information on SSH public key authentication.  Use `ed25519`.

**Comment by haeeun-14** [comment]
Could you clarify the step that "ed25519" is used, please? I can't find such an allusion in any tutorial.

**Comment by YujinGaya** [comment]
I followed [this tutorial](https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54).

**Comment by nv-quan** [comment]
Is it ok if I just use "normal" key? I didn't do anything with the "ed25519" stuff.

**Comment by sonsh04** [comment]
@jeehoonkang
My student number is 20140294, and I couldn't log in to https://gg.kaist.ac.kr/course/6/.
(Maybe because I enrolled this class yesterday.)
Could you add it please?

**Comment by jeehoonkang** [comment]
- @nv-quan you can use keys with other encryption algorithms, but I recommend you to create new keys with `ed25519`.
- @sonsh04 I added you to both gg and the ssh server.

**Comment by lyra95** [comment]
@jeehoonkang 
I've enrolled in this class and couldn't log in to gg.
Would you mind adding me to gg and the ssh server? My student number is 20140555.

**Comment by jeehoonkang** [comment]
@lyra95 I made accounts on gg and the ssh server.

**Comment by dnlwnsqhd** [comment]
Hi, I think I changed my password of my assigned server(cp-service.kaist.ac.kr) but I forgot and cannot access to it.
I'm really sorry but could you please reset my password? My student ID is 20180401.

**Comment by tomtomjhj** [comment]
@dnlwnsqhd Done.

**Comment by nv-quan** [comment]
After the midterm practice session I realized that I forgot to sign the honor code, now that it has passed the deadline I can't sign it anymore. Is there any disadvantage for me? And could you please open it again so I can sign it?

**Comment by jeehoonkang** [comment]
@nv-quan I extended the deadline: https://gg.kaist.ac.kr/quiz/17/
