### ISSUE TITLE
[Question] 'VS code server fail to start' issue

### ISSUE THREAD

**Issue by sjh200212** [kaist-cp/cs492-concur#44]
I have keep failing to reconnect the VS code server.

>connect to the server via ssh and remove ~/.vscode-server entirely, and then retry. Also look at sklationd's comments.

I tried to follow your instructions

![sshserver](https://user-images.githubusercontent.com/57136815/91795234-101f8600-ec58-11ea-9716-80510089627c.png)

(I put my student id in the student id)
But after I try to connect server, and choose Linux,
 
![코드](https://user-images.githubusercontent.com/57136815/91795316-4e1caa00-ec58-11ea-980c-1931c6051293.png)
error occurs.

And I can't type any command on the terminal.

Is there other way to remove vscode-server folder, or can you explain me the way to connect to the server via ssh?
I'm very sorry to keep asking questions but I don't have much experience handling ssh.

**Comment by jeehoonkang** [comment]
- I assume you're on Windows.  Install [putty](https://www.putty.org/), and use it to connect to the server.  You'll get an ssh shell.
- Then remove `~/.vscode-server` entirely, and then retry on vscode.

**Comment by sjh200212** [comment]
> * I assume you're on Windows.  Install [putty](https://www.putty.org/), and use it to connect to the server.  You'll get an ssh shell.
> * Then remove `~/.vscode-server` entirely, and then retry on vscode.

I installed putty but how can I connect the server? How can I find the host name or IP address?
Should I generate key first?(I didn't generate keys at VS code)

**Comment by YujinGaya** [comment]
IP address, id, and default password are in #42. You don't need ssh key to connect to server.

**Comment by sjh200212** [comment]
> Hostname, id, and default password are in #42. You don't need a ssh key to connect to the server.

I'm really sorry, but which one is the host name?
I tried s(student id)@cp-service.kaist.ac.kr or just cp-service.kaist.ac.kr as a host name, but it doesn't connect.

I'm currently using PulseSecure to use kvpn of kaist, so I don't think there is other issue.

**Comment by jeehoonkang** [comment]
@sjh200212 

- When asking a question, please say what you did more explicitly.  "how can I connect the server?" is too broad a question.  I want you to search for how to connect to the server using search engines, and try with some configurations and say what you tried in your question.

- Probably you should specify the port number: 14000.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen if you have follow-up questions!
