### ISSUE TITLE
[Question] gg.kaist login issue

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/cs492-concur#45]
I can't login to gg.kaist, and I think it's because I enrolled late. Hence, I can't do the attendance quiz (or connect to the server), but is it fine anyway since its during the course add and drop period?

Sorry if I'm asking this too late. I know the professor wrote "Troubleshooting: If you cannot log on, it's probably because you've enrolled late. I'll add your id soon." so I waited, but it seems that I still can't login.

**Comment by tomtomjhj** [comment]
I just sent the reply. Sorry for late response.
