### ISSUE TITLE
[Question] The server doesn't accept my password

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#46]
Hello, I have a problem with the initial step.
Before working on VScode, I tried connecting to the server using putty.
I typed "s<student-id>@cp-service.kaist.ac.kr" on host name and port number 14000.
The server screen showed up and ask my password, but the assigned initial(1234598765) password didn't work - access denied.
Now I can't figure out what I did wrong.
![concur02](https://user-images.githubusercontent.com/70534276/91869939-6967d380-ecb1-11ea-9389-b0a8c3e6bdf7.PNG)

**Comment by HelloWorld017** [comment]
I think the username should be `s20160325`, not `s<20160325>`

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen if you have follow-up questions!
