### ISSUE TITLE
[Question] How can I download (and apply) crossbeam?

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs492-concur#47]
![image1](https://user-images.githubusercontent.com/70640395/91976968-d3898280-ed5c-11ea-9fb3-e9b56e92f082.jpg)

In video 1, there is crossbeam in red box, but I don't have it.
In pervious issue's comments, some student said we can clone it from link below.
https://github.com/crossbeam-rs/crossbeam

From above link, which file should I download?
And how can I apply that file so that I can see same crossbeam like video 1?

Thank you.

**Comment by jeehoonkang** [comment]
- You can open a shell by Terminal > New Terminal.
- Go to a directory you want to put crossbeam on, and run `git clone <crossbeam-repo-addr>`.
