### ISSUE TITLE
[Question] Couldn't start client Rust Language Server

### ISSUE THREAD

**Issue by SangwooJung98** [kaist-cp/cs492-concur#48]
![캡처](https://user-images.githubusercontent.com/48044261/91978420-09c80180-ed5f-11ea-91ee-4682bbb84e38.PNG)

Although I installed Rust, codell at vscode while connected to ssh server and rustup to my laptop, I'm still getting same error message everytime I try to build the atomic.rs file. 
I tried reconnecting the ssh server, deleting the .vscode-server folder but there's no difference. 

My development environment is windows10. 
Is there anyone who figured out a solution for this problem??

**Comment by jeehoonkang** [comment]
- You should install codelldb at the server.
- Open a terminal (#47), install rustup, and run `rustup component add rls`.

**Comment by integerblue** [comment]
I tried the solution, but it does not work.
I installed codelldb and rust vscode extensions on the server, and ran rustup component add rls to install rls.

**Comment by integerblue** [comment]
I found the reason why. Check this issue on rust vscode extension github.
[https://github.com/rust-lang/vscode-rust/issues/814](url)

**Comment by Lee-Janggun** [comment]
Hello. Can I ask if you managed to get it to work? I read the issue but I do not think we can edit setting.json on the server. I instead trying what was mentioned here https://github.com/rust-lang/vscode-rust/issues/620, but this did not resolve the issue.

**Comment by tomtomjhj** [comment]
1. Ensure that you have `~/.cargo/bin/rustup`.
2. Ensure that your `~/.profile` contains following line:
   ```sh
   export PATH="$HOME/.cargo/bin:$PATH"
   ```
3. Create a file `~/.bash_profile` with following line:
   ```sh
   source ~/.profile
   ```

This way, vscode will read the `PATH` set in `~/.profile` without changing `bash`'s behavior.


Reference
* https://github.com/microsoft/vscode-remote-release/issues/83#issuecomment-542300538
* bash man page:
  > When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login  option,  it  first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile,  in that order, and reads and executes commands from the first one that exists and is readable. 

Caveat:
I haven't tested it.

**Comment by Lee-Janggun** [comment]
This solved the issue. Thank you very much!
