### ISSUE TITLE
[HW1] How to check server behavior on remote environments?

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs492-concur#51]
I'm nowhere near this stage on the homework, but for future testing purposes:

In the HW1 specifications video, prof. uses a browser to check the behavior of the server;
is there a way to achieve this while using remote environments like VSC?
Or should we use low-level network programs like `telnet` to test?

**Comment by tomtomjhj** [comment]
Launch a terminal in vscode and use `curl` there. Note that if you want to run it on the lab server, you may need to change the port number specified in `bin/hello_server.rs`.
