### ISSUE TITLE
[Question] Request for improving recording environment

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#52]
Professor, your recording environment is not very good in terms of sound.
Noises are mixed to your voice, which makes it hard to increase the volume.
I hope a better microphone could make the sound clear. 
Thank you.

**Comment by jeehoonkang** [comment]
I'd like to ask if today's video is better (#59).

**Comment by integerblue** [comment]
A lot better! Thank you, professor!
