### ISSUE TITLE
[Question] Dealing with debugger on VScode

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#54]
Hello, I have problem with debugging code on VScode.
I followed up the video about runnig rust code on VScode. I installed rust/codelldb/rls and running the code had no problem. But when I tried debugging, the error message appeared.
![concur03](https://user-images.githubusercontent.com/70534276/92127297-21c18300-ee3c-11ea-80b0-b618038c4983.PNG)
Also, the editor cannot hold more than one sheet of code - it switches the file if I click another file.
What could be the problem?

**Comment by tomtomjhj** [comment]
* Do what the dialog says. Open launch.json and fix the executable name.
* Double click the filename. Note that the filename on the tab title is in italic. This will change once you double click the name.

**Comment by jyjy1229** [comment]
So how did you solve that problem..? Can you tell me?

**Comment by haeeun-14** [comment]
> So how did you solve that problem..? Can you tell me?

If you mean by launch.json file, I wrote the file as the video shows: https://www.youtube.com/watch?v=TTVuUIhdn_g
at 6:34
