### ISSUE TITLE
[Question] std::sync::Arc example

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#65]
Can you help me for understanding a example?
![concur07](https://user-images.githubusercontent.com/70534276/92702376-14504f80-f38c-11ea-8202-29c4aaf1a61d.PNG)
I thought this example should print 5 five times-spawning thread in each iteration and cloning the five from the outer five and printing it, and the cloned five goes out of scope when the iteration is over- but running the example actually printed 5 twice.

**Comment by tomtomjhj** [comment]
The main thread terminated before the spawned thread finished printing `five`.

To fix it, you have to `join` the `JoinHandle`s returned by `thread::spawn` to wait for the spawned thread to terminate. See [Rust book §16.1](https://doc.rust-lang.org/book/ch16-01-threads.html) for details.

Or you can simply add `thread::sleep_ms(1000);` to wait for 1 second before terminating the main thread.

**Comment by jeehoonkang** [comment]
@haeeun-14 Please don't paste code as images.
