### ISSUE TITLE
[HW1] About Ctrl+c handler

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#66]
According to skeleton comment in tcp.rs file.

I understand the why I have to change the atomic flag but, I can't understand yet, why I have to (or it is good to) use `TcpListener::local_addr` and `TcpStream::connect` . Why are those two functions related to cancel the stream? Can you explain it?

**Comment by YujinGaya** [comment]
The comment says
> to wake up the listener blocked in `accept`.
