### ISSUE TITLE
"unresolved import 'parking_lot'" while building the example

### ISSUE THREAD

**Issue by aujinsky** [kaist-cp/cs492-concur#67]
When I execute the example from mutex, this error occurs.
Should I modify something to buid it correctly?
![image](https://user-images.githubusercontent.com/44969741/92722324-5e443000-f3a2-11ea-9c25-87ab496a8d81.png)

**Comment by hestati63** [comment]
You need to add `parking_lot` crate into the dependency of your crate.
Add the below lines into your `Cargo.toml` file.

```
[dependencies]
parking_lot="0.1"
```

**Comment by jeehoonkang** [comment]
@aujinsky please don't paste code as image.
