### ISSUE TITLE
[Question] Attendance check on 9/10

### ISSUE THREAD

**Issue by chaeyoonjeong** [kaist-cp/cs492-concur#68]
I see that 9/10 video is still not uploaded. Is the attendance check on 9/10 is valid?
I read the announcement that the video will be uploaded that day, and I waited the video  to be uploaded. 
Today I realized that there were an attendance quiz of 9/10, and I did not solve it.
Will the quiz due be extended up to upload date? Or will it be just counted as usual attendance point?

**Comment by chintanrabadiya** [comment]
This is up to your professor.

**Comment by jeehoonkang** [comment]
The quiz is cancelled: https://github.com/kaist-cp/cs492-concur/issues/62#issuecomment-691847731  Sorry.
