### ISSUE TITLE
[Question] Cache.rs implementation 

### ISSUE THREAD

**Issue by isyangban** [kaist-cp/cs492-concur#69]
In the given code

```rust
use std::collections::hash_map::{Entry, HashMap};
use std::hash::Hash;
use std::sync::{Arc, Mutex, RwLock};
```
Do I have to use all the imported values when implementing the cache?
(Such as Entry & RwLock). 
Or is it enough just to use a subset of the imports.

**Comment by tomtomjhj** [comment]
I used all of them in my reference solution but you may ignore some of them if you think they are unnecessary.
