### ISSUE TITLE
[Session 05, LIVE] September, 17th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#71]
We'll have a **LIVE session** on September, 17th.

- Please visit https://meet.google.com/zqd-qmgd-sga at 10:30am.
- Before the session, please watch all the videos uploaded so far, and read the homework 1 specification.
- It's meant to be a Q&A and discussion session.  Please ask questions in the issue tracker so that the communication can be more efficient.

**Comment by integerblue** [comment]
Is it a mandatory session for students?
Are you gonna record it?
Thank you!

**Comment by jeehoonkang** [comment]
- Let's say the first live session is mandatory.
- I'll not record it.

**Comment by Ngiong** [comment]
I can't join :eyes:

**Comment by saltylight** [comment]
Me too 👀

**Comment by jeehoonkang** [comment]
would you please try again?  refreshing your browser, please.
