### ISSUE TITLE
[Question] Question on Condvar example on official doc

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs492-concur#72]
This is the example code for `Condvar` in https://doc.rust-lang.org/nightly/std/sync/struct.Condvar.html:
```rust
use std::sync::{Arc, Mutex, Condvar};
use std::thread;

let pair = Arc::new((Mutex::new(false), Condvar::new()));
let pair2 = Arc::clone(&pair);

// Inside of our lock, spawn a new thread, and then wait for it to start.
thread::spawn(move|| {
    let (lock, cvar) = &*pair2;
    let mut started = lock.lock().unwrap();
    *started = true;
    // We notify the condvar that the value has changed.
    cvar.notify_one();
});

// Wait for the thread to start up.
let (lock, cvar) = &*pair;
let mut started = lock.lock().unwrap();
while !*started {
    started = cvar.wait(started).unwrap();
}
```
If main thread is executed first, main thread acquires lock, then sleeps from `wait`.
If this is the case, can spawned thread acquire lock, since the main thread is sleeping with lock?

**Comment by YujinGaya** [comment]
Inside `wait`, it releases lock and then wait for other threads to use the lock, and then it acquires the lock back when it woken up by other thread. This mechanism of `CondVar` was coveded [here](https://youtu.be/4ke7RUfDY-g?t=785).
