### ISSUE TITLE
[Question] (Homework #1 ctrlc handler)

### ISSUE THREAD

**Issue by zhanto97** [kaist-cp/cs492-concur#74]
When I press ctrl-c, my thread pool receives an empty request (with key as None). My guess is that it is because I make a bogus connection to itself when I want to shut the server. In professor's video explanation of Homework #1, his implementation does not receive such empty request. I just wonder whether anyone is getting the same problem.

**Comment by tomtomjhj** [comment]
Maybe you're not using `is_canceled` flag properly.

**Comment by zhanto97** [comment]
I am using `is_canceled` as instructed in the skeleton code. What might be my problem?
```
pub fn cancel(&self) -> io::Result<()> {
        self.is_canceled.store(true, Ordering::Release);
        TcpStream::connect(self.inner.local_addr().unwrap());
        Ok(())
}
```

**Comment by tomtomjhj** [comment]
Please don't post homework code on public board.

**Comment by Jaegoomon** [comment]
Maybe I also had a similar problem like you. In my case, when I ran hello_server, and visited web server, the two threads in the listener thread pool waked up per one request. I mean for-loop in listener implemented twice, so one of two threads got accept request well, but the other thread didn't work properly. 

Anyway, If you think that you write the code correctly(1. bogus connection 2. change flag), check your browser. If you check your server in chrome or other things, try to do same action in *fire fox* or other browsers that you don't use much time.

**Comment by zhanto97** [comment]
I found my problem. Accepting connections and listener `is_canceled` checking should be properly ordered.
