### ISSUE TITLE
[Question] kill process on remote 

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#75]
I want to kill process running in port 7878, but I cannot get pid.
How can I get pid to kill process even if I'm not in root?

**Comment by sklationd** [comment]
You can get a pid with `ps` command.
You can use below command to kill specific process.
```
// -9 is for force option
$ kill -9 [PID]
```

**Comment by jeehoonkang** [comment]
Or you can run your process with a different port.  It's a better solution because the server is shared among multiple users.

**Comment by wltn0029** [comment]
`ps` command works fine :) Thank you!
