### ISSUE TITLE
[Question] The way to take T from immutably borrowed Option<T>

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#76]
I'm trying to write a function given immutable borrowed reference of some Option<T>. Here, I cannot use take() or cloned() function because it is immutably borrowed. I want to make use of the T here, but, as I understand, I should break Option in order to use T.

I looked through the document on Option implementations but couldn't find the proper one-or maybe I didn't understand in the right way-. Is there any way to use T in case only the Option<T> is given?

**Comment by tomtomjhj** [comment]
You should wrap your option in something that gives you safe interior mutability.

**Comment by lomotos10** [comment]
You can convert `&Option<T>` to `Option<&T>` using [`as_ref()`](https://doc.rust-lang.org/beta/std/option/enum.Option.html#method.as_ref).

Before:
```rust
#[derive(Clone, Debug)]
enum A {
    A,
    B,
}

fn main() {
    let a = Some(A::A);
    let b = &a;
    let c = b.unwrap().clone();
    println!("{:?}", c);
    println!("{:?}", a.unwrap());
}
```
Error message:
```
error[E0507]: cannot move out of `*b` which is behind a shared reference
  --> src/main.rs:10:13
   |
10 |     let c = b.unwrap().clone();
   |             ^
   |             |
   |             move occurs because `*b` has type `std::option::Option<A>`, which does not implement the `Copy` trait
   |             help: consider borrowing the `Option`'s content: `b.as_ref()`
```
Fix: 
```rust
#[derive(Clone, Debug)]
enum A {
    A,
    B,
}

fn main() {
    let a = Some(A::A);
    let b = &a;
    let c = b.as_ref().unwrap().clone();
    println!("{:?}", c);
    println!("{:?}", a.unwrap());
}
```
