### ISSUE TITLE
[Question] When to create a new worker

### ISSUE THREAD

**Issue by nv-quan** [kaist-cp/cs492-concur#77]
In the skeleton comments, it says "create a new worker for each connection", does that mean I need to create a new worker for every new connection, or create all workers before hand as the book did? And also if I need to create a new worker for every new connection, what happen when a new connection arrives while the number of workers has reached the limit?

**Comment by tomtomjhj** [comment]
You should create all workers in `ThreadPool::new` as the book did. I'll fix the comment soon.
