### ISSUE TITLE
[Question] About testing

### ISSUE THREAD

**Issue by Gabul99** [kaist-cp/cs492-concur#78]
Hello, Ta.
I wonder that there is a way to test or compile each .rs file. I didn't implement cache.rs yet, but I want to check that I make threadpool.rs or tcp.rs correctly. Can we only test when we write all files enough? Thank you.

**Comment by tomtomjhj** [comment]
```
cargo test hello_server -- --skip cache
```
Note: `hello_server` is passed to `cargo-test` and `--skip cache` is passed to the test binaries (e.g. `target/debug/deps/hello_server-44f2a46e3b14ef01`). For more information,
```
cargo test -h
cargo test -- -h
```

**Comment by Gabul99** [comment]
Thank you for answer. But I still have a problem..
I didn't modify any of cache.rs, and I use `cargo test hello_server -- --skip cache` command
but I get error below.
```
error[E0392]: parameter `K` is never used
 --> src/hello_server/cache.rs:9:18
  |
9 | pub struct Cache<K, V> {
  |                  ^ unused parameter
  |
  = help: consider removing `K`, referring to it in a field, or using a marker such as `std::marker::PhantomData`

error[E0392]: parameter `V` is never used
 --> src/hello_server/cache.rs:9:21
  |
9 | pub struct Cache<K, V> {
  |                     ^ unused parameter
```

**Comment by tomtomjhj** [comment]
Oh. Temporary fix I mentioned in https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-690955970
```diff
pub struct Cache<K, V> {
-    inner: ()
+    inner: Mutex<HashMap<K, V>>
}
```
