### ISSUE TITLE
[Question] How to debug concurrent rust program

### ISSUE THREAD

**Issue by nv-quan** [kaist-cp/cs492-concur#79]
I have passed all the test but the `thread_pool_drop_propagate_panic`. The program just hangs when executing that test. Is there some advice for debugging a concurrent program? I tried println! but sometimes it just not print the message.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-696038652

For this type of problem, you should first figure out the points at which the thread may block.

**Comment by YujinGaya** [comment]
<img width="254" alt="Screen Shot 2020-09-22 at 8 02 34 AM" src="https://user-images.githubusercontent.com/13472245/93830041-111d6380-fcaa-11ea-8dd1-136187f242ec.png">

CodeLLDB supports multithreaded debugging. Set the breakpoint and run until the program hits the breakpoint. It'll show which variables are set to what value, call stack, etc.

In my case, I intentionally set breakpoint a little bit before the suspicious line. Then hitted `step over` button to execute one line at a time until the thread blocks. This way you'll be able to figure out exactly which line the thread blocks.

**Comment by nv-quan** [comment]
Thank guys, I found the bug that causes my program to hang. For those who curious, I waited for all the jobs to finish before dropping the Threadpool, which makes it hang when a thread panic and the job was never finished.
