### ISSUE TITLE
[Question] Homework #1 ctrl-c handler

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#81]
I've already read closed issues about ctrl-c handler, but for me it's hard to get a handle on it.

Comment says that
> make a bogus connection to itself to wake up the listener blocked in `accept`.

What is `bogus connection`? Is it just connecting server and sending some message to listener that ctrl-c is called?

**Comment by nv-quan** [comment]
I think that comment means "Make a **fake connection** to itself"

**Comment by wltn0029** [comment]
What is difference between **send error message** and **fake connection** ? 
By the way, how stream can find out ctrl-c handler is called by accepting **fake connection**?

I have difficulty in building `cancel` method, so it will be appreciated to explain what you mean more ..

**Comment by Jaegoomon** [comment]
As far as I know, the process of Ctrl+c handler in this project is like these
1. change flag
2. bogus connection

then, we have to know why we change "flag". In the Iterator, you can see the code
```rust
let stream: io::Result<TcpStream> = self.listener.inner.accept().map(|p| p.0);
```
in that line, there is accept(), and it blocks until new connection is requested. And when the accept() get new request then, check the atomicbool, and if you change the flag it will return None than the hello_server is getting cancelled. 

So, our goal is changing flag and *unblock the accep() function in next() right after cancel function is done or while cancel function is acting* by connecting fake connection. That means make abnormal connection to pass the accept() by force.

Actually this is what I understand in bogus connection. Of course those are not perfectly correct..... But I wish it will help you :)

**Comment by nv-quan** [comment]
> What is difference between **send error message** and **fake connection** ?
> By the way, how stream can find out ctrl-c handler is called by accepting **fake connection**?
> 
> I have difficulty in building `cancel` method, so it will be appreciated to explain what you mean more ..

I'm not TA, but as far as I understand, fake connection means fake Tcp connection, as I can see there's some hint about `TcpStream::connect` and `TcpListener::local_addr`

**Comment by wltn0029** [comment]
Maybe I got some understanding about this issue.. 
Thank you for answering my question!
