### ISSUE TITLE
[Question] Threadpool.join() when there is a panicked thread

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#83]
For the homework1,
what is the desired behavior of following case:

```
let pool = ThreadPool::new(NUM_THREADS);
pool.execute(move || panic!(); );
pool.join();

```

Intuitively it seems that the main thread need to panic, too.
However (in my opinion) implementing this makes the code quite complex. 
Should we consider this case, too?
Thanks.

**Comment by tomtomjhj** [comment]
No.

**Comment by AnHaechan** [comment]
> No.

Thanks!
