### ISSUE TITLE
[Question] Assignment 1, about thread interleaving after thread::spawn

### ISSUE THREAD

**Issue by Gabul99** [kaist-cp/cs492-concur#86]
Hello, TA.
My codes stuck in loop during `cargo test` and I recognized it happens in ThreadPool::new.
In my implementation of ThreadPool::new, it `calls thread::spawn` ->` generate struct Worker with id, thread` -> `Push the Worker in vector`. This series of process is repeated 'size' times to make number of threads. (It is very similar to process of textbook)
so I check that when it fall in loop by panic!(), and I find that loop occurs when `generate struct Worker with id, thread`. For example, it is stuck in this line : `let work = Worker {id : i, thread : Some(thread),};`.
So I thought about it, and the loop exists only in the new spawned thread at this time. Therefore when `let work` is declared, the switching to new thread can be occurred and there may be a problem.
I wonder that it is possible execution, and is there any way not to occur context switch during ThreadPool::new runs.
Thank you.

**Comment by tomtomjhj** [comment]
Which test is failing?

**Comment by Gabul99** [comment]
I failed in all test of thread_pool.rs. It seems problem of my ThreadPool::new implementation.
Through more debugging, I recognize that context switching to new spawned thread occurs immediately, so ThreadPool::new(which running on main thread) is not end.
I think it is not so different with the code in textbook.... but context switching happen. I wonder that anything I missed.

```
...
let threadA = thread::spawn(move || ~~~ );
(A)
let work = Worker{id, thread,};
...
```
It is switched to new spawned threadA in (A) from main thread in my case

**Comment by tomtomjhj** [comment]
@Gabul99 please send me an email with your code

**Comment by Jaechan-So** [comment]
I'm struggling to solve the problem similar as you. Can you share me rough way to resolve your problem(not too specific)? Or can I send an email to TA?

**Comment by tomtomjhj** [comment]
I had a look at @Gabul99's code. Here are some relevant materials for fixing your solution:
1. https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-690955970, especially the paragraph starting with "We `join()` each thread in ...".
2. https://docs.rs/crossbeam-channel/0.4.4/crossbeam_channel/struct.Receiver.html#method.recv
3. https://github.com/kaist-cp/cs492-concur/issues/85#issuecomment-696888546
