### ISSUE TITLE
[Question] Is `empty_condvar` absolutely necessary?

### ISSUE THREAD

**Issue by saltylight** [kaist-cp/cs492-concur#87]
In my thread_pool.rs, I didn't even touch `empty_condvar` and passed all tests(& score 100/100).
Is `empty_condvar` absolutely necessary? Or would it be used in upcoming homeworks?

**Comment by tomtomjhj** [comment]
Condvar is not absolutely necessary but implementation without it can be sub-optimal.

**Comment by ellaide** [comment]
I think you solve wait_empty either using condvar or busy waiting. I assume you did the latter. I am not sure though

**Comment by saltylight** [comment]
@tomtomjhj Thank you. Since it can be sub-optimal, I implemented thread_pool with `empty_condvar`.
@ellaide Definitely right. I did the latter, but I modified the solution with condvar 😄
