### ISSUE TITLE
[Question] Tcp listener connection to itself

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#88]
Could you help me understand the meaning of signaling the listener to stop accept connection?
The implication says
"Set the flag first and make a bogus connection to itself to wake up the listener blocked in `accept`."
Does it mean that the server should make connection to itself?
Also, it is not clear for me that the listener is blocked in 'accept', because I thought the listener was still accepting the client and then this function commands the listener to stop 'accept'ing.
Thank you for the help in advance.

**Comment by nv-quan** [comment]
I believe this is a duplicate question. Please see if this [issue](https://github.com/kaist-cp/cs492-concur/issues/81) answer your question
