### ISSUE TITLE
[Question] What is the difference between cargo_tsan and cargo?

### ISSUE THREAD

**Issue by castlecowrice** [kaist-cp/cs492-concur#89]
I executed `./scripts/grade-1.sh` and it failed at these test cases

```
Running with cargo_tsan...
Testing cache.rs...
Test failed:    cargo_tsan test hello_server::cache::test::cache_no_block_disjoint 
Test timed out: cargo_tsan test hello_server::cache::test::cache_no_duplicate_concurrent 
Test failed:    cargo_tsan test hello_server::cache::test::cache_no_duplicate_sequential
```

so I tried `cargo_tsan test hello_server::cache::test::cache_no_block_disjoint` but then the terminal said that there is no command named `cargo_tsan`. Then I tried `cargo test hello_server::cache::test::cache_no_block_disjoint` and it passed every time I tried it. 
I want to know why they give me different outcomes.

**Comment by YujinGaya** [comment]
If you look at the `./scripts/grade-utils.sh` there are the definitions of `cargo_tsan` and `cargo_asan`. They basically run cargo command with some environment variables set to certain values. Resulting commands are same with the one in [this comment](https://github.com/kaist-cp/cs492-concur/issues/49#issuecomment-695281384).

**Comment by castlecowrice** [comment]
Oh I didn't know that the manual for HW1 has been updated. Thank you, I solved the problem.
