### ISSUE TITLE
[Midterm exam] on everything you've learned in this course (10/21)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#9]
### Logistics

- Date & time: 9:00am-11:00am, October 21th, 2019
- Place: Rm. 2111, Bldg. E3-1
- Coverage: everything you’ve learned in this course
    + Including the code of locks and ART, and the ART paper
    + Not asking you to program in Rust in the paper
- Bring a black/blue pen and your student ID (no pencil, please)

### Study guide

- You are asked to “explain” the reasons of a phenomena.  Your explanation should be an informal proof with a few gaps.  In other words, your argument should be clear and precise.

**Comment by Shynar88** [comment]
Can I write exam with a pencil? Or only pen is allowed?

**Comment by jeehoonkang** [comment]
I'd like you to write it with a pen.  Because pencil can be erased.
