### ISSUE TITLE
[Question] tsan cache.rs test

### ISSUE THREAD

**Issue by Jaegoomon** [kaist-cp/cs492-concur#90]
Well, if I implement the tests individually, then the test of `tsan cache_no_duplicate_concurrent` is passed although it take some times. But in checker, it failed because of timeout.

Why do `tsan-test` take much time...? I mean what makes the tsan option take much time.....

**Comment by tomtomjhj** [comment]
> [Typical slowdown introduced by ThreadSanitizer is about 5x-15x.](https://clang.llvm.org/docs/ThreadSanitizer.html)
