### ISSUE TITLE
[Question] Could not create zip file

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#95]
When I tried to create a new zip file according to https://gg.kaist.ac.kr/assignment/18/, I got the following error.

```
s@kaist-cp-cs492:~$ cd cs492-concur/homework
s@kaist-cp-cs492:~/cs492-concur/homework$ ./scripts/submit.sh
zip I/O error: No such file or directory
zip error: Could not create output file (target/hw1.zip)
```
What is the problem here? I had originally copied the repo into the server with `git clone https://github.com/kaist-cp/cs492-concur`, and thinking this might be the problem. If not, how should I fix it?

**Comment by tomtomjhj** [comment]
Maybe there is no `./target` directory.

**Comment by Lee-Janggun** [comment]
I had a `./target`. For some reason it works now. I got a file.
