### ISSUE TITLE
[Question] Homework1 ThreadPool join() function semantics

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#96]
Currently I'm getting "test failed" in the middle of the `cargo test`, I guess it's due to the join function or drop function because the test notified that the process didn't exit successfully.
Now I'm trying to figure out the exact purpose of the `ThreadPool::join()` function.
There is a `ThreadPoolInner::wait_empty()` function which seems to do the same work, because it also waits for all the jobs to be completed.
What could be the difference between the purpose of the two functions?

**Comment by tomtomjhj** [comment]
`ThreadPool::join` is a public wrapper for `ThreadPoolInner::wait_empty` and it shouldn't do anything other than that. https://github.com/kaist-cp/cs492-concur/issues/85#issuecomment-696888546 this will be helpful if the failed test is `thread_pool_join_block`
