### ISSUE TITLE
[Question] Due of HW1

### ISSUE THREAD

**Issue by Jaechan-So** [kaist-cp/cs492-concur#98]
I just want to clarify this; The entire course management website says the due of HW1 is 09/25 11:59:59. The assignment submission page says the due of HW1 is 09/25 02:59:59. I think the exact due of HW1 is 09/25 23:59:59, is it right? I will close this issue asap, thanks in advance!

**Comment by tomtomjhj** [comment]
The due is 09/25 23:59:59.
