### ISSUE TITLE
[Question] Cannot fix ownership problem of `Threadpool::new`

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#99]
I am trying to implement 'Threadpool::new' as in the book. As we do not have `Worker::new`, I simply moved the aspects of the `Worker::new` function. Essentially I moved
```
impl Worker {
    fn new(id: usize, receiver: Arc<Mutex<mpsc::Receiver<Job>>>) -> Worker {
        let thread = thread::spawn(|| {
            receiver;
        });

        Worker { id, thread }
    }
}
```

into

```
for id in 0..size {
    workers.push(Worker::new(id, Arc::clone(&receiver)));
}
```
inside of `Threadpull::new`. However I have a new ownership problem `use of moved value: receiver`. I thought that using `Arc<Mutex<T>>` in the book, and `Arc<T>` for us, was to solve this specific problem. What am I doing wrong?

**Comment by YujinGaya** [comment]
> ## Major differences between HW1 and Rust book §20
> * We use [`crossbeam_channel`](https://docs.rs/crossbeam-channel/) instead of [`std::sync::mpsc`](https://doc.rust-lang.org/std/sync/mpsc/index.html). Since crossbeam channel is mpmc, you don't need to wrap the `Receiver` inside a `Mutex`. - #49

As TA said in above tips, we don't use `std::sync::mpsc`, and we don't need `std::sync::Arc` and `std::sync::Mutex` for the receiver. To share `crossbeam::channel::Receiver`, you only need to clone it.
Here's an example from the crossbeam documentation. [Sharing channels in crossbeam](https://docs.rs/crossbeam/0.7.3/crossbeam/channel/index.html#sharing-channels)

```Rust
use std::thread;
use crossbeam_channel::bounded;

let (s1, r1) = bounded(0);
let (s2, r2) = (s1.clone(), r1.clone());

// Spawn a thread that receives a message and then sends one.
thread::spawn(move || {
    r2.recv().unwrap();
    s2.send(2).unwrap();
});

// Send a message and then receive one.
s1.send(1).unwrap();
r1.recv().unwrap();
```

**Comment by Lee-Janggun** [comment]
Oh lol I thought the TA meant we don't need ONLY the mutex. Thank you very much for the clarification.

**Comment by Lee-Janggun** [comment]
Actually even after I just cloned it I have the same problem. So I tried making an additional reference to the cloned element and that worked.
So for me,
```
let rec = receiver.clone();
let work = Worker {id, thread : thread::spawn(move || {rec...});
```
worked while

```
let work = Worker {id, thread : thread::spawn(move || {receiver.clone()...});
```
failed to compile. Interestingly VSCode recommends changing the first to the second, so I think this may be a compiler problem?

**Comment by YujinGaya** [comment]
What's the error message for the second case? How is rls explaining about the recommendation from the first to the second?

**Comment by Lee-Janggun** [comment]
The error message for the first case is
```
use of moved value: `receiver`

value moved into closure here, in previous iteration of loop
```
The recommendation from rls was that my call to rec was

```
path statement with no effect
```

I added some more code and now this recommendation is gone, and on reading it again I think the cause was just that I didn't implement the function enough.
